<a href="https://colab.research.google.com/github/naga-dheeraj-p/Assignments/blob/main/Quant_Final_printing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Options

In [79]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [360]:
import glob
import csv
import os
import time

start = time.time()

path = "/content/gdrive/MyDrive/bank_nifty data/csv"
all_files = glob.glob(os.path.join(path, "*.csv"))
cols = ['time', 'symbol', 'open', 'high', 'low', 'close', 'volume', 'oi', 'expiry', 'strike', 'instrument_type', 'Date']

output_file = 'dataset.csv'
with open(output_file, 'w', newline='') as out:
    writer = csv.writer(out)
    writer.writerow(cols)

for file in all_files:
    date = os.path.basename(file).split('.')[0]
    year = date[-6:]
    if year == '042018':
        with open(file, 'r') as f, open(output_file, 'a', newline='') as out:
            reader = csv.reader(f)
            writer = csv.writer(out)
            next(reader)  # Skip the header row
            for row in reader:
                row.append(date)
                writer.writerow(row)

end = time.time()
print("Execution time:", end - start)

Execution time: 2.3785951137542725

In [361]:
'''import glob
import csv
import os
import time

start = time.time()

path = "/content/gdrive/MyDrive/bank_nifty data/csv"
all_files = glob.glob(os.path.join(path, "*.csv"))
cols = ['time', 'symbol', 'open', 'high', 'low', 'close', 'volume', 'oi', 'expiry', 'strike', 'instrument_type', 'Date']

output_file = 'dataset.csv'
with open(output_file, 'w', newline='') as out:
    writer = csv.writer(out)
    writer.writerow(cols)

for file in all_files:
    date = os.path.basename(file).split('.')[0]
    year = int(date[-6:])
    if year == 012018:
        with open(file, 'r') as f, open(output_file, 'a', newline='') as out:
            reader = csv.reader(f)
            writer = csv.writer(out)
            next(reader)  # Skip the header row
            for row in reader:
                row.append(date)
                writer.writerow(row)

end = time.time()
print("Execution time:", end - start)'''

'import glob\nimport csv\nimport os\nimport time\n\nstart = time.time()\n\npath = "/content/gdrive/MyDrive/bank_nifty data/csv"\nall_files = glob.glob(os.path.join(path, "*.csv"))\ncols = [\'time\', \'symbol\', \'open\', \'high\', \'low\', \'close\', \'volume\', \'oi\', \'expiry\', \'strike\', \'instrument_type\', \'Date\']\n\noutput_file = \'dataset.csv\'\nwith open(output_file, \'w\', newline=\'\') as out:\n    writer = csv.writer(out)\n    writer.writerow(cols)\n\nfor file in all_files:\n    date = os.path.basename(file).split(\'.\')[0]\n    year = int(date[-6:])\n    if year == 012018:\n        with open(file, \'r\') as f, open(output_file, \'a\', newline=\'\') as out:\n            reader = csv.reader(f)\n            writer = csv.writer(out)\n            next(reader)  # Skip the header row\n            for row in reader:\n                row.append(date)\n                writer.writerow(row)\n\nend = time.time()\nprint("Execution time:", end - start)'

In [362]:
import pandas as pd
data1=pd.read_csv("/content/dataset.csv")
print(data1.shape)
data1.tail()

(557604, 12)

,time,symbol,open,high,low,close,volume,oi,expiry,strike,instrument_type,Date
557599,10:29:00,BANKNIFTY31MAY1825000CE,270.0,270.0,270.0,270.0,40,360,31-05-2018,25000,CE,23032018
557600,11:31:00,BANKNIFTY31MAY1825000CE,270.0,270.0,240.1,240.1,40,360,31-05-2018,25000,CE,23032018
557601,12:25:00,BANKNIFTY31MAY1825000CE,240.1,272.9,240.1,272.9,40,360,31-05-2018,25000,CE,23032018
557602,13:41:00,BANKNIFTY31MAY1825000CE,273.0,273.0,273.0,273.0,40,400,31-05-2018,25000,CE,23032018
557603,13:58:00,BANKNIFTY31MAY1825000CE,273.0,273.0,260.0,260.0,40,440,31-05-2018,25000,CE,23032018

In [363]:
import pandas as pd
def preprocess_date(date_string):
    date_str = str(date_string)
    if len(date_str) == 8:
        # If the date string is in the format 'DDMMYYYY', convert it to 'DD-MM-YYYY'
        return date_str[:2] + '-' + date_str[2:4] + '-' + date_str[4:]
    else:
        date_str = '0' + date_str
        return date_str[:2] + '-' + date_str[2:4] + '-' + date_str[4:]
data1['Preprocessed_Date'] = data1['Date'].apply(preprocess_date)

In [364]:
sorted_data = data1.sort_values(by=['Preprocessed_Date', 'instrument_type', 'strike', 'time']).reset_index(drop=True)
sorted_data.head(60)

,time,symbol,open,high,low,close,volume,oi,expiry,strike,instrument_type,Date,Preprocessed_Date
0,11:05:00,BANKNIFTY28MAR1823300CE,1909.25,1912.50,1909.25,1912.50,200,6720,28-03-2018,23300,CE,1032018,01-03-2018
1,11:06:00,BANKNIFTY28MAR1823300CE,1912.50,1912.50,1911.05,1911.05,80,6720,28-03-2018,23300,CE,1032018,01-03-2018
2,11:07:00,BANKNIFTY28MAR1823300CE,1911.05,1911.05,1884.90,1884.90,80,6720,28-03-2018,23300,CE,1032018,01-03-2018
3,11:30:00,BANKNIFTY28MAR1823300CE,1884.90,1884.90,1835.00,1835.00,40,6520,28-03-2018,23300,CE,1032018,01-03-2018
4,11:51:00,BANKNIFTY28MAR1823300CE,1835.00,1878.00,1835.00,1878.00,40,6480,28-03-2018,23300,CE,1032018,01-03-2018
5,12:37:00,BANKNIFTY28MAR1823300CE,1878.00,1891.65,1878.00,1891.65,40,6440,28-03-2018,23300,CE,1032018,01-03-2018
6,14:03:00,BANKNIFTY28MAR1823300CE,1891.65,1891.65,1845.00,1845.00,40,6440,28-03-2018,23300,CE,1032018,01-03-2018
7,14:44:00,BANKNIFTY28MAR1823300CE,1845.00,1845.00,1790.00,1790.00,40,6480,28-03-2018,23300,CE,1032018,01-03-2018
8,15:09:00,BANKNIFTY28MAR1823300CE,1790.00,1790.00,1679.60,1679.60,80,6440,28-03-2018,23300,CE,1032018,01-03-2018
9,15:25:00,BANKNIFTY28MAR1823300CE,1679.60,1679.60,1655.55,1655.55,200,6520,28-03-2018,23300,CE,1032018,01-03-2018
10,15:28:00,BANKNIFTY28MAR1823300CE,1655.55,1655.55,1650.00,1650.00,40,6680,28-03-2018,23300,CE,1032018,01-03-2018
11,09:24:00,BANKNIFTY28MAR1823500CE,1790.00,1790.00,1790.00,1790.00,40,149040,28-03-2018,23500,CE,1032018,01-03-2018
12,09:26:00,BANKNIFTY28MAR1823500CE,1790.00,1795.00,1790.00,1795.00,240,149080,28-03-2018,23500,CE,1032018,01-03-2018
13,09:27:00,BANKNIFTY28MAR1823500CE,1795.00,1795.00,1795.00,1795.00,2360,149080,28-03-2018,23500,CE,1032018,01-03-2018
14,09:28:00,BANKNIFTY28MAR1823500CE,1795.00,1795.00,1785.00,1785.00,280,149080,28-03-2018,23500,CE,1032018,01-03-2018
15,09:53:00,BANKNIFTY28MAR1823500CE,1785.00,1785.00,1707.75,1707.75,80,146480,28-03-2018,23500,CE,1032018,01-03-2018
16,10:05:00,BANKNIFTY28MAR1823500CE,1707.75,1710.00,1707.75,1710.00,40,146480,28-03-2018,23500,CE,1032018,01-03-2018
17,10:10:00,BANKNIFTY28MAR1823500CE,1710.00,1710.00,1660.00,1660.00,40,146440,28-03-2018,23500,CE,1032018,01-03-2018
18,10:52:00,BANKNIFTY28MAR1823500CE,1660.00,1700.00,1660.00,1700.00,40,146400,28-03-2018,23500,CE,1032018,01-03-2018
19,11:31:00,BANKNIFTY28MAR1823500CE,1700.00,1700.00,1650.00,1650.00,80,146440,28-03-2018,23500,CE,1032018,01-03-2018
20,13:25:00,BANKNIFTY28MAR1823500CE,1650.00,1715.00,1650.00,1715.00,40,146440,28-03-2018,23500,CE,1032018,01-03-2018
21,13:26:00,BANKNIFTY28MAR1823500CE,1715.00,1715.00,1710.00,1710.00,40,146400,28-03-2018,23500,CE,1032018,01-03-2018
22,14:34:00,BANKNIFTY28MAR1823500CE,1710.00,1710.00,1606.00,1606.00,120,146320,28-03-2018,23500,CE,1032018,01-03-2018
23,14:38:00,BANKNIFTY28MAR1823500CE,1606.00,1620.00,1606.00,1620.00,40,146320,28-03-2018,23500,CE,1032018,01-03-2018
24,15:00:00,BANKNIFTY28MAR1823500CE,1620.00,1620.00,1540.00,1540.00,80,146360,28-03-2018,23500,CE,1032018,01-03-2018
25,15:05:00,BANKNIFTY28MAR1823500CE,1500.00,1540.00,1500.00,1500.00,160,146320,28-03-2018,23500,CE,1032018,01-03-2018
26,15:06:00,BANKNIFTY28MAR1823500CE,1500.00,1500.00,1500.00,1500.00,80,146320,28-03-2018,23500,CE,1032018,01-03-2018
27,15:04:00,BANKNIFTY28MAR1823600CE,1444.00,1444.00,1444.00,1444.00,40,2880,28-03-2018,23600,CE,1032018,01-03-2018
28,15:20:00,BANKNIFTY28MAR1823700CE,1350.00,1350.00,1350.00,1350.00,40,29480,28-03-2018,23700,CE,1032018,01-03-2018
29,09:21:00,BANKNIFTY01MAR1824000CE,1150.00,1150.00,1150.00,1150.00,40,1400,01-03-2018,24000,CE,1032018,01-03-2018
30,09:22:00,BANKNIFTY28MAR1824000CE,1330.00,1330.00,1330.00,1330.00,80,286040,28-03-2018,24000,CE,1032018,01-03-2018
31,09:25:00,BANKNIFTY01MAR1824000CE,1150.00,1200.00,1150.00,1200.00,40,1440,01-03-2018,24000,CE,1032018,01-03-2018
32,09:28:00,BANKNIFTY28MAR1824000CE,1330.00,1330.65,1330.00,1330.65,40,286040,28-03-2018,24000,CE,1032018,01-03-2018
33,09:33:00,BANKNIFTY28MAR1824000CE,1330.65,1330.65,1320.00,1320.00,40,286040,28-03-2018,24000,CE,1032018,01-03-2018
34,09:38:00,BANKNIFTY01MAR1824000CE,1200.00,1200.00,1187.25,1187.25,40,1480,01-03-2018,24000,CE,1032018,01-03-2018
35,09:51:00,BANKNIFTY28MAR1824000CE,1320.00,1320.00,1275.00,1275.00,40,286080,28-03-2018,24000,CE,1032018,01-03-2018
36,09:53:00,BANKNIFTY28MAR1824000CE,1275.00,1275.00,1266.70,1266.70,80,286120,28-03-2018,24000,CE,1032018,01-03-2018
37,09:59:00,BANKNIFTY28MAR1824000CE,1266.70,1276.00,1266.70,1276.00,40,286120,28-03-2018,24000,CE,1032018,01-03-2018
38,10:12:00,BANKNIFTY01MAR1824000CE,1187.25,1187.25,1050.00,1050.00,40,1480,01-03-2018,24000,CE,1032018,01-03-2018
39,10:17:00,BANKNIFTY28MAR1824000CE,1276.00,1276.00,1220.00,1220.00,40,286080,28-03-2018,24000,CE,1032018,01-03-2018
40,10:46:00,BANKNIFTY01MAR1824000CE,1050.00,1050.00,1050.00,1050.00,40,1520,01-03-2018,24000,CE,1032018,01-03-2018
41,11:23:00,BANKNIFTY28MAR1824000CE,1220.00,1220.00,1214.75,1214.75,160,286120,28-03-2018,24000,CE,1032018,01-03-2018
42,11:26:00,BANKNIFTY28MAR1824000CE,1214.75,1230.00,1214.75,1230.00,40,286000,28-03-2018,24000,CE,1032018,01-03-2018
43,11:36:00,BANKNIFTY28MAR1824000CE,1230.00,1230.00,1202.30,1202.30,200,285960,28-03-2018,24000,CE,1032018,01-03-2018
44,11:44:00,BANKNIFTY28MAR1824000CE,1202.30,1229.50,1202.30,1229.50,40,285960,28-03-2018,24000,CE,1032018,01-03-2018
45,12:05:00,BANKNIFTY28MAR1824000CE,1229.50,1240.30,1229.50,1240.30,40,285960,28-03-2018,24000,CE,1032018,01-03-2018
46,12:15:00,BANKNIFTY28MAR1824000CE,1238.00,1238.00,1238.00,1238.00,40,285920,28-03-2018,24000,CE,1032018,01-03-2018
47,12:29:00,BANKNIFTY28MAR1824000CE,1238.00,1246.00,1238.00,1246.00,40,285960,28-03-2018,24000,CE,1032018,01-03-2018
48,12:31:00,BANKNIFTY08MAR1824000CE,1082.85,1082.85,1082.85,1082.85,40,0,08-03-2018,24000,CE,1032018,01-03-2018
49,12:32:00,BANKNIFTY08MAR1824000CE,1082.85,1089.70,1082.85,1087.10,280,40,08-03-2018,24000,CE,1032018,01-03-2018
50,12:33:00,BANKNIFTY08MAR1824000CE,1087.10,1087.10,1086.55,1086.55,40,40,08-03-2018,24000,CE,1032018,01-03-2018
51,12:35:00,BANKNIFTY28MAR1824000CE,1246.00,1257.00,1246.00,1257.00,80,286000,28-03-2018,24000,CE,1032018,01-03-2018
52,12:36:00,BANKNIFTY28MAR1824000CE,1257.00,1265.00,1257.00,1265.00,120,286000,28-03-2018,24000,CE,1032018,01-03-2018
53,12:37:00,BANKNIFTY01MAR1824000CE,1050.00,1103.30,1050.00,1103.30,40,1480,01-03-2018,24000,CE,1032018,01-03-2018
54,12:37:00,BANKNIFTY28MAR1824000CE,1265.00,1270.00,1265.00,1270.00,40,286000,28-03-2018,24000,CE,1032018,01-03-2018
55,12:48:00,BANKNIFTY01MAR1824000CE,1103.30,1103.30,1089.70,1089.70,40,1480,01-03-2018,24000,CE,1032018,01-03-2018
56,12:54:00,BANKNIFTY01MAR1824000CE,1089.70,1089.70,1086.10,1086.10,40,1440,01-03-2018,24000,CE,1032018,01-03-2018
57,12:55:00,BANKNIFTY01MAR1824000CE,1086.10,1090.00,1086.10,1090.00,40,1440,01-03-2018,24000,CE,1032018,01-03-2018
58,12:56:00,BANKNIFTY08MAR1824000CE,1086.55,1115.00,1086.55,1115.00,360,360,08-03-2018,24000,CE,1032018,01-03-2018
59,12:58:00,BANKNIFTY01MAR1824000CE,1090.00,1092.15,1090.00,1091.40,80,1440,01-03-2018,24000,CE,1032018,01-03-2018

In [365]:
import pandas as pd
import numpy as np

data = sorted_data.copy()  # Made a copy to avoid modifying original data
data['time'] = pd.to_datetime(data['time'])

time_range = pd.date_range(start='09:15:00', end='15:30:00', freq='5T')
expanded_data = pd.DataFrame()

grouped_data = data.groupby(['Preprocessed_Date', 'instrument_type'])


for (Preprocessed_Date, instrument_type), subset in grouped_data:
    # Group the subset by strike and resample each group to 5-minute intervals
    resampled_subset = subset.set_index('time').groupby('strike').resample('5T').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
        'oi': 'last'
    }).reset_index(level='strike')

    # Forward filling
    resampled_subset[['high', 'low']] = resampled_subset[['high', 'low']].ffill()
    # Interpolating
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].replace(0, np.nan)
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].interpolate(method='linear')
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].fillna(0).round(2)
    resampled_subset[['open', 'close']] = resampled_subset[['open', 'close']].interpolate(method='linear').round(2)

    resampled_subset.reset_index(inplace=True)

    for col in ['symbol', 'expiry']:
        resampled_subset[col] = subset[col].iloc[0]

    resampled_subset['Preprocessed_Date'] = Preprocessed_Date
    resampled_subset['instrument_type'] = instrument_type
    expanded_data = pd.concat([expanded_data, resampled_subset], ignore_index=True)

expanded_data.sort_values(by=['Preprocessed_Date', 'instrument_type', 'strike', 'time'], inplace=True)
expanded_data.reset_index(drop=True, inplace=True)
expanded_data['time'] = pd.to_datetime(expanded_data['time']).dt.time

<ipython-input-365-54d6af9e359d>:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['time'] = pd.to_datetime(data['time'])

In [366]:
expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE
...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE

In [367]:
import pandas as pd
import os
from datetime import datetime

directory_path = '/content/gdrive/MyDrive/Fut_data'
data_list = []

for filename in os.listdir(directory_path):
    if filename.endswith('.csv'):
        try:
            date_str = filename.split('.')[0]  # Assuming the filename is like 'DDMMYYYY.csv'
            date_obj = datetime.strptime(date_str, '%d%m%Y')
            formatted_date = date_obj.strftime('%d-%m-%Y')
        except ValueError:
            print(f'{filename}: Filename does not match expected date format')
            continue
        if date_obj.year==2018:                                                                                   #change here!!!!!!!!!!!!!!!!!!!!!!!!
        #if date_obj.year==2018 and date_obj.month==12:
            file_path = os.path.join(directory_path, filename)
            df = pd.read_csv(file_path)

            # Considering ATM value from the first row
            if 'open' in df.columns:
                atm_value = df['open'].iloc[0]
                # Appending the formatted date and the ATM value to the data list
                data_list.append((formatted_date, atm_value))
            else:
                print(f'{formatted_date}: "open" column not found')

data_list.sort(key=lambda x: datetime.strptime(x[0], '%d-%m-%Y'))
for formatted_date, atm_value in data_list:
    print(f'{formatted_date}: ATM = {atm_value}')

01-01-2018: ATM = 25570.0
02-01-2018: ATM = 25490.0
03-01-2018: ATM = 25440.0
04-01-2018: ATM = 25394.75
05-01-2018: ATM = 25534.0
08-01-2018: ATM = 25699.85
09-01-2018: ATM = 25750.0
10-01-2018: ATM = 25696.2
11-01-2018: ATM = 25602.4
12-01-2018: ATM = 25710.0
15-01-2018: ATM = 25774.75
16-01-2018: ATM = 26121.0
17-01-2018: ATM = 25989.95
18-01-2018: ATM = 26610.25
19-01-2018: ATM = 26551.05
22-01-2018: ATM = 26889.9
23-01-2018: ATM = 27044.4
24-01-2018: ATM = 27310.05
25-01-2018: ATM = 27474.65
29-01-2018: ATM = 27382.0
30-01-2018: ATM = 27451.05
31-01-2018: ATM = 27222.0
01-02-2018: ATM = 27430.35
02-02-2018: ATM = 26994.95
05-02-2018: ATM = 26094.95
06-02-2018: ATM = 25201.1
07-02-2018: ATM = 26111.35
08-02-2018: ATM = 25741.0
09-02-2018: ATM = 25510.15
12-02-2018: ATM = 25602.5
14-02-2018: ATM = 25760.0
15-02-2018: ATM = 25325.0
16-02-2018: ATM = 25475.1
19-02-2018: ATM = 25300.05
20-02-2018: ATM = 25061.1
21-02-2018: ATM = 24980.0
22-02-2018: ATM = 24785.0
23-02-2018: ATM = 25002.0
26-02-2018: ATM = 25530.0
27-02-2018: ATM = 25700.0
28-02-2018: ATM = 24600.0
01-03-2018: ATM = 25069.4
05-03-2018: ATM = 24749.65
06-03-2018: ATM = 24990.0
07-03-2018: ATM = 24370.0
08-03-2018: ATM = 24364.0
09-03-2018: ATM = 24549.8
12-03-2018: ATM = 24505.65
13-03-2018: ATM = 24710.0
14-03-2018: ATM = 24690.0
15-03-2018: ATM = 24922.05
16-03-2018: ATM = 24750.85
19-03-2018: ATM = 24630.0
20-03-2018: ATM = 24210.0
21-03-2018: ATM = 24375.05
22-03-2018: ATM = 24352.35
23-03-2018: ATM = 23832.0
26-03-2018: ATM = 23670.0
27-03-2018: ATM = 24424.0
28-03-2018: ATM = 24300.0
02-04-2018: ATM = 24355.5
03-04-2018: ATM = 24380.0
04-04-2018: ATM = 24621.75
05-04-2018: ATM = 24422.0
06-04-2018: ATM = 24820.1
09-04-2018: ATM = 24860.0
10-04-2018: ATM = 25149.0
11-04-2018: ATM = 25201.2
12-04-2018: ATM = 25099.65
13-04-2018: ATM = 25249.65
16-04-2018: ATM = 25098.6
17-04-2018: ATM = 25385.05
18-04-2018: ATM = 25410.1
19-04-2018: ATM = 25199.9
20-04-2018: ATM = 25111.05
23-04-2018: ATM = 25135.0
24-04-2018: ATM = 24963.0
25-04-2018: ATM = 24949.8
26-04-2018: ATM = 24801.05
27-04-2018: ATM = 25040.65
30-04-2018: ATM = 25401.0
02-05-2018: ATM = 25675.0
03-05-2018: ATM = 25611.05
04-05-2018: ATM = 25679.25
07-05-2018: ATM = 25760.0
08-05-2018: ATM = 26035.0
09-05-2018: ATM = 25967.85
10-05-2018: ATM = 26133.05
11-05-2018: ATM = 26115.0
14-05-2018: ATM = 26411.95
15-05-2018: ATM = 26470.0
16-05-2018: ATM = 26319.4
17-05-2018: ATM = 26260.0
18-05-2018: ATM = 26033.35
21-05-2018: ATM = 25952.1
22-05-2018: ATM = 25775.9
23-05-2018: ATM = 25770.0
24-05-2018: ATM = 25640.0
25-05-2018: ATM = 25968.95
28-05-2018: ATM = 26240.0
29-05-2018: ATM = 26490.05
30-05-2018: ATM = 25981.55
31-05-2018: ATM = 26510.15
01-06-2018: ATM = 26726.0
04-06-2018: ATM = 26890.0
05-06-2018: ATM = 26140.0
06-06-2018: ATM = 26277.95
07-06-2018: ATM = 26563.0
08-06-2018: ATM = 26481.05
11-06-2018: ATM = 26449.95
12-06-2018: ATM = 26575.55
13-06-2018: ATM = 26700.05
14-06-2018: ATM = 26600.0
15-06-2018: ATM = 26545.0
18-06-2018: ATM = 26339.95
19-06-2018: ATM = 26349.95
20-06-2018: ATM = 26286.4
21-06-2018: ATM = 26677.9
22-06-2018: ATM = 26470.0
25-06-2018: ATM = 26110.8
26-06-2018: ATM = 26511.1
27-06-2018: ATM = 26593.35
28-06-2018: ATM = 26417.6
29-06-2018: ATM = 26255.6
02-07-2018: ATM = 26349.95
03-07-2018: ATM = 26181.0
04-07-2018: ATM = 26244.95
05-07-2018: ATM = 26436.55
06-07-2018: ATM = 26427.85
09-07-2018: ATM = 26620.0
10-07-2018: ATM = 26775.05
11-07-2018: ATM = 26870.0
12-07-2018: ATM = 26879.95
13-07-2018: ATM = 27039.95
16-07-2018: ATM = 26912.7
17-07-2018: ATM = 26689.95
18-07-2018: ATM = 27149.95
19-07-2018: ATM = 26967.95
20-07-2018: ATM = 26825.05
23-07-2018: ATM = 26805.15
24-07-2018: ATM = 27053.05
25-07-2018: ATM = 27077.7
26-07-2018: ATM = 27090.0
27-07-2018: ATM = 27503.3
30-07-2018: ATM = 27724.8
31-07-2018: ATM = 27814.85
01-08-2018: ATM = 27778.7
02-08-2018: ATM = 27510.15
03-08-2018: ATM = 27510.0
06-08-2018: ATM = 27825.6
07-08-2018: ATM = 27979.0
08-08-2018: ATM = 27975.0
09-08-2018: ATM = 28224.85
10-08-2018: ATM = 28342.95
13-08-2018: ATM = 27890.0
14-08-2018: ATM = 27905.0
16-08-2018: ATM = 27889.55
17-08-2018: ATM = 28011.35
20-08-2018: ATM = 28290.0
21-08-2018: ATM = 28340.2
23-08-2018: ATM = 28336.4
24-08-2018: ATM = 28010.4
27-08-2018: ATM = 28034.75
28-08-2018: ATM = 28360.55
29-08-2018: ATM = 28249.95
30-08-2018: ATM = 28233.3
31-08-2018: ATM = 28160.0
03-09-2018: ATM = 28285.15
04-09-2018: ATM = 27969.0
05-09-2018: ATM = 27594.95
06-09-2018: ATM = 27555.05
07-09-2018: ATM = 27560.05
10-09-2018: ATM = 27485.0
11-09-2018: ATM = 27365.55
12-09-2018: ATM = 26980.05
14-09-2018: ATM = 27202.0
17-09-2018: ATM = 27049.75
18-09-2018: ATM = 26819.9
19-09-2018: ATM = 26585.05
21-09-2018: ATM = 26442.95
24-09-2018: ATM = 25749.9
25-09-2018: ATM = 24952.4
26-09-2018: ATM = 25619.95
27-09-2018: ATM = 25155.55
28-09-2018: ATM = 25325.2
01-10-2018: ATM = 25085.0
03-10-2018: ATM = 25400.0
04-10-2018: ATM = 24780.0
05-10-2018: ATM = 24700.0
08-10-2018: ATM = 24444.7
09-10-2018: ATM = 24762.4
10-10-2018: ATM = 24609.95
11-10-2018: ATM = 24600.35
12-10-2018: ATM = 25037.0
15-10-2018: ATM = 25399.0
16-10-2018: ATM = 25356.25
17-10-2018: ATM = 25875.0
19-10-2018: ATM = 24960.25
22-10-2018: ATM = 25475.0
23-10-2018: ATM = 24799.8
24-10-2018: ATM = 25350.05
25-10-2018: ATM = 24860.0
26-10-2018: ATM = 24875.0
29-10-2018: ATM = 24683.65
30-10-2018: ATM = 25050.35
31-10-2018: ATM = 24874.95
01-11-2018: ATM = 25249.95
02-11-2018: ATM = 25548.0
05-11-2018: ATM = 25700.2
06-11-2018: ATM = 25824.7
07-11-2018: ATM = 25880.0
09-11-2018: ATM = 25730.0
12-11-2018: ATM = 25850.25
13-11-2018: ATM = 25479.95
14-11-2018: ATM = 25984.5
15-11-2018: ATM = 25960.0
16-11-2018: ATM = 26202.15
19-11-2018: ATM = 26355.1
20-11-2018: ATM = 26240.0
21-11-2018: ATM = 26050.0
22-11-2018: ATM = 26310.1
26-11-2018: ATM = 26075.0
27-11-2018: ATM = 26300.2
28-11-2018: ATM = 26467.8
29-11-2018: ATM = 26602.05
30-11-2018: ATM = 26957.45
03-12-2018: ATM = 27055.5
04-12-2018: ATM = 26903.0
05-12-2018: ATM = 26670.0
06-12-2018: ATM = 26485.5
07-12-2018: ATM = 26380.0
10-12-2018: ATM = 26251.25
11-12-2018: ATM = 25800.0
12-12-2018: ATM = 26349.85
13-12-2018: ATM = 26867.65
14-12-2018: ATM = 26853.0
17-12-2018: ATM = 26988.8
18-12-2018: ATM = 26950.0
19-12-2018: ATM = 27301.0
20-12-2018: ATM = 27189.4
21-12-2018: ATM = 27300.0
24-12-2018: ATM = 26925.0
26-12-2018: ATM = 26700.0
27-12-2018: ATM = 27198.0
28-12-2018: ATM = 27275.0
31-12-2018: ATM = 27400.0

In [368]:
data_list.sort(key=lambda x: datetime.strptime(x[0], '%d-%m-%Y'))
atm_dict = dict(data_list)
# Function to map preprocessed date to ATM value
def get_atm(date):
    return atm_dict.get(date, None)

# Adding a new column 'ATM' using the mapping function
expanded_data['atm'] = expanded_data['Preprocessed_Date'].apply(get_atm)
expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0

In [369]:
df_opt = pd.DataFrame(expanded_data)

df_opt['time'] = df_opt['time'].astype(str)
df_opt['datetime'] = pd.to_datetime(df_opt['Preprocessed_Date'] + ' ' + df_opt['time'], format='%d-%m-%Y %H:%M:%S')
cols = ['datetime'] + [col for col in df_opt if col != 'datetime']
df_opt = df_opt[cols]

In [370]:
df_opt.head(60)

,datetime,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
0,2018-03-01 11:05:00,11:05:00,23300,1909.25,1912.50,1884.90,1884.90,360.0,6720.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
1,2018-03-01 11:10:00,11:10:00,23300,1904.38,1912.50,1884.90,1874.92,296.0,6680.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
2,2018-03-01 11:15:00,11:15:00,23300,1899.51,1912.50,1884.90,1864.94,232.0,6640.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
3,2018-03-01 11:20:00,11:20:00,23300,1894.64,1912.50,1884.90,1854.96,168.0,6600.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
4,2018-03-01 11:25:00,11:25:00,23300,1889.77,1912.50,1884.90,1844.98,104.0,6560.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
5,2018-03-01 11:30:00,11:30:00,23300,1884.90,1884.90,1835.00,1835.00,40.0,6520.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
6,2018-03-01 11:35:00,11:35:00,23300,1872.43,1884.90,1835.00,1845.75,40.0,6510.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
7,2018-03-01 11:40:00,11:40:00,23300,1859.95,1884.90,1835.00,1856.50,40.0,6500.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
8,2018-03-01 11:45:00,11:45:00,23300,1847.48,1884.90,1835.00,1867.25,40.0,6490.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
9,2018-03-01 11:50:00,11:50:00,23300,1835.00,1878.00,1835.00,1878.00,40.0,6480.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
10,2018-03-01 11:55:00,11:55:00,23300,1839.78,1878.00,1835.00,1879.52,40.0,6475.56,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
11,2018-03-01 12:00:00,12:00:00,23300,1844.56,1878.00,1835.00,1881.03,40.0,6471.11,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
12,2018-03-01 12:05:00,12:05:00,23300,1849.33,1878.00,1835.00,1882.55,40.0,6466.67,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
13,2018-03-01 12:10:00,12:10:00,23300,1854.11,1878.00,1835.00,1884.07,40.0,6462.22,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
14,2018-03-01 12:15:00,12:15:00,23300,1858.89,1878.00,1835.00,1885.58,40.0,6457.78,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
15,2018-03-01 12:20:00,12:20:00,23300,1863.67,1878.00,1835.00,1887.10,40.0,6453.33,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
16,2018-03-01 12:25:00,12:25:00,23300,1868.44,1878.00,1835.00,1888.62,40.0,6448.89,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
17,2018-03-01 12:30:00,12:30:00,23300,1873.22,1878.00,1835.00,1890.13,40.0,6444.44,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
18,2018-03-01 12:35:00,12:35:00,23300,1878.00,1891.65,1878.00,1891.65,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
19,2018-03-01 12:40:00,12:40:00,23300,1878.80,1891.65,1878.00,1888.91,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
20,2018-03-01 12:45:00,12:45:00,23300,1879.61,1891.65,1878.00,1886.16,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
21,2018-03-01 12:50:00,12:50:00,23300,1880.41,1891.65,1878.00,1883.42,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
22,2018-03-01 12:55:00,12:55:00,23300,1881.21,1891.65,1878.00,1880.67,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
23,2018-03-01 13:00:00,13:00:00,23300,1882.01,1891.65,1878.00,1877.93,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
24,2018-03-01 13:05:00,13:05:00,23300,1882.82,1891.65,1878.00,1875.19,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
25,2018-03-01 13:10:00,13:10:00,23300,1883.62,1891.65,1878.00,1872.44,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
26,2018-03-01 13:15:00,13:15:00,23300,1884.42,1891.65,1878.00,1869.70,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
27,2018-03-01 13:20:00,13:20:00,23300,1885.23,1891.65,1878.00,1866.95,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
28,2018-03-01 13:25:00,13:25:00,23300,1886.03,1891.65,1878.00,1864.21,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
29,2018-03-01 13:30:00,13:30:00,23300,1886.83,1891.65,1878.00,1861.46,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
30,2018-03-01 13:35:00,13:35:00,23300,1887.64,1891.65,1878.00,1858.72,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
31,2018-03-01 13:40:00,13:40:00,23300,1888.44,1891.65,1878.00,1855.98,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
32,2018-03-01 13:45:00,13:45:00,23300,1889.24,1891.65,1878.00,1853.23,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
33,2018-03-01 13:50:00,13:50:00,23300,1890.04,1891.65,1878.00,1850.49,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
34,2018-03-01 13:55:00,13:55:00,23300,1890.85,1891.65,1878.00,1847.74,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
35,2018-03-01 14:00:00,14:00:00,23300,1891.65,1891.65,1845.00,1845.00,40.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
36,2018-03-01 14:05:00,14:05:00,23300,1885.82,1891.65,1845.00,1838.12,40.0,6445.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
37,2018-03-01 14:10:00,14:10:00,23300,1879.99,1891.65,1845.00,1831.25,40.0,6450.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
38,2018-03-01 14:15:00,14:15:00,23300,1874.16,1891.65,1845.00,1824.38,40.0,6455.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
39,2018-03-01 14:20:00,14:20:00,23300,1868.32,1891.65,1845.00,1817.50,40.0,6460.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
40,2018-03-01 14:25:00,14:25:00,23300,1862.49,1891.65,1845.00,1810.62,40.0,6465.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
41,2018-03-01 14:30:00,14:30:00,23300,1856.66,1891.65,1845.00,1803.75,40.0,6470.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
42,2018-03-01 14:35:00,14:35:00,23300,1850.83,1891.65,1845.00,1796.88,40.0,6475.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
43,2018-03-01 14:40:00,14:40:00,23300,1845.00,1845.00,1790.00,1790.00,40.0,6480.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
44,2018-03-01 14:45:00,14:45:00,23300,1834.00,1845.00,1790.00,1767.92,48.0,6472.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
45,2018-03-01 14:50:00,14:50:00,23300,1823.00,1845.00,1790.00,1745.84,56.0,6464.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
46,2018-03-01 14:55:00,14:55:00,23300,1812.00,1845.00,1790.00,1723.76,64.0,6456.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
47,2018-03-01 15:00:00,15:00:00,23300,1801.00,1845.00,1790.00,1701.68,72.0,6448.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
48,2018-03-01 15:05:00,15:05:00,23300,1790.00,1790.00,1679.60,1679.60,80.0,6440.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
49,2018-03-01 15:10:00,15:10:00,23300,1762.40,1790.00,1679.60,1672.20,120.0,6500.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
50,2018-03-01 15:15:00,15:15:00,23300,1734.80,1790.00,1679.60,1664.80,160.0,6560.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
51,2018-03-01 15:20:00,15:20:00,23300,1707.20,1790.00,1679.60,1657.40,200.0,6620.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
52,2018-03-01 15:25:00,15:25:00,23300,1679.60,1679.60,1650.00,1650.00,240.0,6680.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
53,2018-03-01 09:20:00,09:20:00,23500,1790.00,1790.00,1790.00,1790.00,40.0,149040.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
54,2018-03-01 09:25:00,09:25:00,23500,1790.00,1795.00,1785.00,1785.00,2880.0,149080.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
55,2018-03-01 09:30:00,09:30:00,23500,1789.00,1795.00,1785.00,1769.55,2320.0,148560.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
56,2018-03-01 09:35:00,09:35:00,23500,1788.00,1795.00,1785.00,1754.10,1760.0,148040.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
57,2018-03-01 09:40:00,09:40:00,23500,1787.00,1795.00,1785.00,1738.65,1200.0,147520.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
58,2018-03-01 09:45:00,09:45:00,23500,1786.00,1795.00,1785.00,1723.20,640.0,147000.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4
59,2018-03-01 09:50:00,09:50:00,23500,1785.00,1785.00,1707.75,1707.75,80.0,146480.00,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4

In [371]:
df_new = pd.DataFrame(df_opt)


df_new['datetime'] = pd.to_datetime(df_new['datetime'])
df_new['Preprocessed_Date'] = pd.to_datetime(df_new['Preprocessed_Date'], format='%d-%m-%Y')

# Function to find the nearest strike to ATM for each day
def nearest_strike(group):
    nearest_strike_row = group.loc[(group['strike'] - group['atm']).abs().idxmin()]
    return nearest_strike_row['strike']

# Get the nearest strike for each Preprocessed_Date
nearest_strikes = df_new.groupby('Preprocessed_Date').apply(nearest_strike).reset_index()
nearest_strikes.columns = ['Preprocessed_Date', 'nearest_strike']


merged_df = pd.merge(df_new, nearest_strikes, on='Preprocessed_Date')
filtered_data = merged_df[merged_df['strike'] == merged_df['nearest_strike']]

filtered_data = filtered_data[(filtered_data['datetime'].dt.time >= pd.to_datetime('09:15:00').time()) &
                          (filtered_data['datetime'].dt.time <= pd.to_datetime('15:30:00').time())]

filtered_data = filtered_data.drop(columns='nearest_strike')
filtered_data

,datetime,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
776,2018-03-01 09:15:00,09:15:00,25100,54.00,491.05,41.70,490.00,806080.0,10880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4
777,2018-03-01 09:20:00,09:20:00,25100,93.40,512.05,91.90,512.05,673960.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4
778,2018-03-01 09:25:00,09:25:00,25100,135.10,542.15,113.95,258.40,391960.0,13880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4
779,2018-03-01 09:30:00,09:30:00,25100,119.15,267.25,106.10,259.65,140840.0,13920.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4
780,2018-03-01 09:35:00,09:35:00,25100,125.90,518.50,114.55,510.00,144480.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107313,2018-03-28 15:05:00,15:05:00,24300,234.00,466.00,14.20,46.90,1651840.0,427760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0
107314,2018-03-28 15:10:00,15:10:00,24300,254.65,470.00,36.05,44.00,832120.0,351000.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0
107315,2018-03-28 15:15:00,15:15:00,24300,250.00,469.90,33.25,35.05,454640.0,287760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0
107316,2018-03-28 15:20:00,15:20:00,24300,236.95,452.55,24.65,27.95,429560.0,196240.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0
107317,2018-03-28 15:25:00,15:25:00,24300,230.65,456.00,28.00,30.05,320280.0,133760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0

In [372]:
expanded_data['time'] = expanded_data['time'].astype(str)
expanded_data['datetime'] = pd.to_datetime(expanded_data['Preprocessed_Date'] + ' ' + expanded_data['time'], format='%d-%m-%Y %H:%M:%S')

unique_combinations = expanded_data[['Preprocessed_Date', 'time']].drop_duplicates()

results = []

for _, row in unique_combinations.iterrows():
    target_date = row['Preprocessed_Date']
    target_time = row['time']

    # Filter the dataset for the current combination
    filtered_df = expanded_data[(expanded_data['Preprocessed_Date'] == target_date) & (expanded_data['time'] == target_time)]

    strikes = filtered_df['strike'].unique()

    min_total_loss = float('inf')
    max_pain_strike = None

    for strike in strikes:
        total_loss = 0

        for _, option in filtered_df.iterrows():
            if option['instrument_type'] == 'CE':
                if option['strike'] < strike:
                    loss = (strike - option['strike']) * option['oi']
                else:
                    loss = 0
            elif option['instrument_type'] == 'PE':
                if option['strike'] > strike:
                    loss = (option['strike'] - strike) * option['oi']
                else:
                    loss = 0

            total_loss += loss

        if total_loss < min_total_loss:
            min_total_loss = total_loss
            max_pain_strike = strike

    results.append({
        'Preprocessed_Date': target_date,
        'time': target_time,
        'Max_Pain_Strike': max_pain_strike
    })

results_df = pd.DataFrame(results)
expanded_data = pd.merge(expanded_data, results_df, on=['Preprocessed_Date', 'time'], how='left')
expanded_data.rename(columns={'Max_Pain_Strike': 'max_pain_strike'}, inplace=True)

expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:05:00,25100
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:10:00,25200
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:15:00,25100
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:20:00,25100
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:25:00,25000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:10:00,24300
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:15:00,24300
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:20:00,24300
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:25:00,24400
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 12:30:00,24300

In [373]:
import pandas as pd

expanded_df = pd.DataFrame(expanded_data)

# Ensure 'Preprocessed_Date' and 'time' are strings
expanded_df['Preprocessed_Date'] = expanded_df['Preprocessed_Date'].astype(str)
expanded_df['time'] = expanded_df['time'].astype(str)

# Combine 'Preprocessed_Date' and 'time' into a single 'datetime' column with explicit format
expanded_df['datetime'] = pd.to_datetime(expanded_df['Preprocessed_Date'] + ' ' + expanded_df['time'], format='%d-%m-%Y %H:%M:%S')

# Group by both 'datetime' and 'strike', then aggregate 'oi'
grouped_df = expanded_df.groupby(['datetime', 'strike']).agg({'oi': 'sum'}).reset_index()

# Get the top 6 most active strikes for each 5-minute interval
top_strikes = grouped_df.groupby('datetime').apply(lambda x: x.nlargest(6, 'oi')).reset_index(drop=True)

# Combine the top strikes into a single string for each datetime
result_df = top_strikes.groupby('datetime')['strike'].apply(lambda x: ', '.join(x.astype(str))).reset_index()
merged_df = pd.merge(expanded_df, result_df, on='datetime', how='left')

# Rename the column to 'most_active_strikes'
merged_df.rename(columns={'strike_y': 'most_active_strikes'}, inplace=True)
if 'strike_x' in merged_df.columns:
    merged_df.drop(columns=['strike_x'], inplace=True)

merged_df

,time,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,most_active_strikes
0,11:05:00,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:05:00,25100,"25000, 26000, 25500, 27000, 23500, 25200"
1,11:10:00,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:10:00,25200,"24000, 25500, 25000, 26000, 27000, 24500"
2,11:15:00,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:15:00,25100,"24000, 25500, 25000, 26000, 27000, 24500"
3,11:20:00,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:20:00,25100,"24000, 25000, 26000, 25500, 27000, 24500"
4,11:25:00,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:25:00,25000,"24000, 25000, 26000, 25500, 26500, 27000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:10:00,24300,"24500, 24000, 24200, 24300, 24400, 24100"
108922,15:15:00,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:15:00,24300,"24500, 24200, 24000, 24300, 24400, 24100"
108923,15:20:00,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:20:00,24300,"24500, 24000, 24200, 24300, 24400, 24600"
108924,15:25:00,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:25:00,24400,"24500, 24000, 24200, 24300, 24400, 24100"
108925,12:30:00,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 12:30:00,24300,"24500, 24000, 24300, 24200, 24600, 24400"

In [374]:
def calculate_intraday_pcr(df):
    # Ensure 'Preprocessed_Date' and 'time' are strings
    df['Preprocessed_Date'] = df['Preprocessed_Date'].astype(str)
    df['time'] = df['time'].astype(str)

    # Combine 'Preprocessed_Date' and 'time' to ensure 'datetime' is in datetime format
    df['datetime'] = pd.to_datetime(df['Preprocessed_Date'] + ' ' + df['time'], format='%d-%m-%Y %H:%M:%S')

    # Get the unique 5-minute intervals in the data
    time_intervals = df['datetime'].dt.floor('5T').unique()

    for time in time_intervals:
        # Filter data for the current 5-minute interval
        interval_df = df[df['datetime'].dt.floor('5T') == time]

        atm_strike = interval_df['atm'].iloc[0] if not interval_df['atm'].empty else None

        if atm_strike is not None:
            lower_bound = atm_strike - 1000
            upper_bound = atm_strike + 1000
            selected_strikes = interval_df[(interval_df['strike'] >= lower_bound) & (interval_df['strike'] <= upper_bound)]

            total_put_volume = selected_strikes[selected_strikes['instrument_type'] == 'PE']['volume'].sum()
            total_call_volume = selected_strikes[selected_strikes['instrument_type'] == 'CE']['volume'].sum()

            pcr = total_put_volume / total_call_volume if total_call_volume != 0 else None

            # Update the 'intraday_pcr' for the filtered interval data
            df.loc[df['datetime'].dt.floor('5T') == time, 'intraday_pcr'] = pcr

    return df

# Assuming expanded_data is your initial dataset
merged_df = pd.DataFrame(expanded_data)

# Calculate intraday PCR and update the DataFrame
merged_df = calculate_intraday_pcr(expanded_df)

merged_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:05:00,25100,0.627078
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:10:00,25200,0.518556
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:15:00,25100,0.906108
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:20:00,25100,0.728071
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:25:00,25000,0.897145
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:10:00,24300,1.271178
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:15:00,24300,1.259509
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:20:00,24300,1.125140
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:25:00,24400,0.947927
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 12:30:00,24300,0.862084

In [375]:
import pandas as pd

def calculate_cumulative_pcr(df):
    # Combine 'Preprocessed_Date' and 'time' to ensure 'time' is in datetime format
    df['datetime'] = pd.to_datetime(df['Preprocessed_Date'] + ' ' + df['time'], format='%d-%m-%Y %H:%M:%S')

    # Initialize cumulative put and call volumes
    cumulative_put_volume = 0
    cumulative_call_volume = 0

    # Get the unique 5-minute intervals in the data
    time_intervals = df['datetime'].dt.floor('5T').unique()

    for time in time_intervals:
        # Filter data for the current 5-minute interval
        interval_df = df[df['datetime'].dt.floor('5T') == time]

        atm_strike = interval_df['atm'].iloc[0] if not interval_df['atm'].empty else None

        if atm_strike is not None:
            lower_bound = atm_strike - 1000
            upper_bound = atm_strike + 1000
            selected_strikes = interval_df[(interval_df['strike'] >= lower_bound) & (interval_df['strike'] <= upper_bound)]

            interval_put_volume = selected_strikes[selected_strikes['instrument_type'] == 'PE']['volume'].sum()
            interval_call_volume = selected_strikes[selected_strikes['instrument_type'] == 'CE']['volume'].sum()

            # Update cumulative volumes
            cumulative_put_volume += interval_put_volume
            cumulative_call_volume += interval_call_volume

            # Calculate cumulative PCR
            cumulative_pcr = cumulative_put_volume / cumulative_call_volume if cumulative_call_volume != 0 else None

            # Update the 'Cumulative_pcr' for the filtered interval data
            df.loc[df['datetime'].dt.floor('5T') == time, 'cumulative_pcr'] = cumulative_pcr

    return df

# Assuming merged_df is your DataFrame after merging the most active strikes
final_merged_df = pd.DataFrame(merged_df)

# Calculate cumulative PCR and update the DataFrame
final_merged_df = calculate_cumulative_pcr(final_merged_df)
final_merged_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:05:00,25100,0.627078,0.627078
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:10:00,25200,0.518556,0.556810
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:15:00,25100,0.906108,0.664468
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:20:00,25100,0.728071,0.681755
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:25:00,25000,0.897145,0.713335
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:10:00,24300,1.271178,0.807965
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:15:00,24300,1.259509,0.808480
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:20:00,24300,1.125140,0.808742
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:25:00,24400,0.947927,0.808835
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 12:30:00,24300,0.862084,0.806223

In [376]:
import pandas as pd

# Assuming expanded_data is your initial dataset
last_final_merged_df = pd.DataFrame(final_merged_df)

# Group by both 'datetime' and 'strike', then aggregate 'oi'
grouped_df = last_final_merged_df.groupby(['datetime', 'strike']).agg({'oi': 'sum'}).reset_index()

# Get the top 6 most active strikes for each 5-minute interval
top_strikes = last_final_merged_df.groupby('datetime').apply(lambda x: x.nlargest(6, 'oi')).reset_index(drop=True)

# Concatenate 'strike' with 'instrument_type'
top_strikes['strike_with_type'] = top_strikes['strike'].astype(str) + top_strikes['instrument_type']

# Combine the top strikes into a single string for each datetime
result_df = top_strikes.groupby('datetime')['strike_with_type'].apply(lambda x: ', '.join(x)).reset_index()

# Merge the result back into the last_final_merged_df
end_df = pd.merge(last_final_merged_df, result_df, on='datetime', how='left')

# Rename the column to 'most_active_strikes'
end_df.rename(columns={'strike_with_type': 'most_active_strikes'}, inplace=True)

# Optionally, drop the redundant columns if they exist
if 'strike_x' in end_df.columns:
    end_df.drop(columns=['strike_x'], inplace=True)

end_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
0,11:05:00,23300,1909.25,1912.5,1884.9,1884.90,360.0,6720.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:05:00,25100,0.627078,0.627078,"26000CE, 25000PE, 25500CE, 26500CE, 25200PE, 2..."
1,11:10:00,23300,1904.38,1912.5,1884.9,1874.92,296.0,6680.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:10:00,25200,0.518556,0.556810,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
2,11:15:00,23300,1899.51,1912.5,1884.9,1864.94,232.0,6640.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:15:00,25100,0.906108,0.664468,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
3,11:20:00,23300,1894.64,1912.5,1884.9,1854.96,168.0,6600.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:20:00,25100,0.728071,0.681755,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
4,11:25:00,23300,1889.77,1912.5,1884.9,1844.98,104.0,6560.0,BANKNIFTY28MAR1823300CE,28-03-2018,01-03-2018,CE,25069.4,2018-03-01 11:25:00,25000,0.897145,0.713335,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
108921,15:10:00,29000,4595.45,4650.0,4650.0,4620.00,280.0,2560.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:10:00,24300,1.271178,0.807965,"24500CE, 24000PE, 24200PE, 24400CE, 24100PE, 2..."
108922,15:15:00,29000,4568.17,4650.0,4650.0,4605.00,400.0,3620.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:15:00,24300,1.259509,0.808480,"24500CE, 24200PE, 24000PE, 24400CE, 24300CE, 2..."
108923,15:20:00,29000,4540.90,4590.0,4540.9,4590.00,520.0,4680.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:20:00,24300,1.125140,0.808742,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."
108924,15:25:00,29000,4725.00,4725.0,4725.0,4725.00,320.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 15:25:00,24400,0.947927,0.808835,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."
108925,12:30:00,29100,3500.00,3500.0,3500.0,3500.00,2480.0,320.0,BANKNIFTY05APR1822100PE,05-04-2018,28-03-2018,PE,24300.0,2018-03-28 12:30:00,24300,0.862084,0.806223,"24500CE, 24000PE, 24600CE, 24200PE, 24400CE, 2..."

In [377]:
df1 = pd.DataFrame(end_df)


df1['datetime'] = pd.to_datetime(df1['datetime'])
df1['Preprocessed_Date'] = pd.to_datetime(df1['Preprocessed_Date'], format='%d-%m-%Y')

# Function to find the nearest strike to ATM for each day
def nearest_strike(group):
    nearest_strike_row = group.loc[(group['strike'] - group['atm']).abs().idxmin()]
    return nearest_strike_row['strike']

# Get the nearest strike for each Preprocessed_Date
nearest_strikes = df1.groupby('Preprocessed_Date').apply(nearest_strike).reset_index()
nearest_strikes.columns = ['Preprocessed_Date', 'nearest_strike']


merged_df = pd.merge(df1, nearest_strikes, on='Preprocessed_Date')
filtered_df = merged_df[merged_df['strike'] == merged_df['nearest_strike']]

filtered_df = filtered_df[(filtered_df['datetime'].dt.time >= pd.to_datetime('09:15:00').time()) &
                          (filtered_df['datetime'].dt.time <= pd.to_datetime('15:30:00').time())]
filtered_df = filtered_df.drop(columns='nearest_strike')
filtered_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
776,09:15:00,25100,54.00,491.05,41.70,490.00,806080.0,10880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:15:00,25500,0.592719,0.804578,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
777,09:20:00,25100,93.40,512.05,91.90,512.05,673960.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:20:00,25300,0.636941,0.844229,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
778,09:25:00,25100,135.10,542.15,113.95,258.40,391960.0,13880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:25:00,25400,0.651194,0.837541,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
779,09:30:00,25100,119.15,267.25,106.10,259.65,140840.0,13920.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:30:00,25200,0.724292,0.835560,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
780,09:35:00,25100,125.90,518.50,114.55,510.00,144480.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:35:00,25500,0.912277,0.836814,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107313,15:05:00,24300,234.00,466.00,14.20,46.90,1651840.0,427760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0,2018-03-28 15:05:00,24400,0.868174,0.807301,"24500CE, 24000PE, 24200PE, 24400CE, 24600CE, 2..."
107314,15:10:00,24300,254.65,470.00,36.05,44.00,832120.0,351000.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0,2018-03-28 15:10:00,24300,1.271178,0.807965,"24500CE, 24000PE, 24200PE, 24400CE, 24100PE, 2..."
107315,15:15:00,24300,250.00,469.90,33.25,35.05,454640.0,287760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0,2018-03-28 15:15:00,24300,1.259509,0.808480,"24500CE, 24200PE, 24000PE, 24400CE, 24300CE, 2..."
107316,15:20:00,24300,236.95,452.55,24.65,27.95,429560.0,196240.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0,2018-03-28 15:20:00,24300,1.125140,0.808742,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."
107317,15:25:00,24300,230.65,456.00,28.00,30.05,320280.0,133760.0,BANKNIFTY05APR1822100PE,05-04-2018,2018-03-28,PE,24300.0,2018-03-28 15:25:00,24400,0.947927,0.808835,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."

In [378]:
options_df = filtered_df[filtered_df['instrument_type'].str.contains('ce', case=False, na=False)]
#options_df.drop(columns=['symbol',	'time','open','	high'	,'low',	'close','volume',	'oi'	], inplace=True)
options_df.head()

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
776,09:15:00,25100,54.00,491.05,41.70,490.00,806080.0,10880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:15:00,25500,0.592719,0.804578,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
777,09:20:00,25100,93.40,512.05,91.90,512.05,673960.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:20:00,25300,0.636941,0.844229,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
778,09:25:00,25100,135.10,542.15,113.95,258.40,391960.0,13880.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:25:00,25400,0.651194,0.837541,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
779,09:30:00,25100,119.15,267.25,106.10,259.65,140840.0,13920.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:30:00,25200,0.724292,0.835560,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
780,09:35:00,25100,125.90,518.50,114.55,510.00,144480.0,10760.0,BANKNIFTY28MAR1823300CE,28-03-2018,2018-03-01,CE,25069.4,2018-03-01 09:35:00,25500,0.912277,0.836814,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."

In [379]:
#final_opt_df=options_df['datetime','instrument_type','atm','max_pain_strike','intraday_pcr'	,'cumulative_pcr','most_active_strikes']
options_df.columns = options_df.columns.str.strip()

# Select the columns to create final_opt_df
columns_to_select = ['datetime', 'atm', 'max_pain_strike', 'intraday_pcr', 'cumulative_pcr', 'most_active_strikes']
final_opt_df = options_df[columns_to_select]
final_opt_df

,datetime,atm,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
776,2018-03-01 09:15:00,25069.4,25500,0.592719,0.804578,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
777,2018-03-01 09:20:00,25069.4,25300,0.636941,0.844229,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
778,2018-03-01 09:25:00,25069.4,25400,0.651194,0.837541,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
779,2018-03-01 09:30:00,25069.4,25200,0.724292,0.835560,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
780,2018-03-01 09:35:00,25069.4,25500,0.912277,0.836814,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2..."
...,...,...,...,...,...,...
103971,2018-03-28 15:05:00,24300.0,24400,0.868174,0.807301,"24500CE, 24000PE, 24200PE, 24400CE, 24600CE, 2..."
103972,2018-03-28 15:10:00,24300.0,24300,1.271178,0.807965,"24500CE, 24000PE, 24200PE, 24400CE, 24100PE, 2..."
103973,2018-03-28 15:15:00,24300.0,24300,1.259509,0.808480,"24500CE, 24200PE, 24000PE, 24400CE, 24300CE, 2..."
103974,2018-03-28 15:20:00,24300.0,24300,1.125140,0.808742,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."
103975,2018-03-28 15:25:00,24300.0,24400,0.947927,0.808835,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2..."

# Futures

In [380]:
import pandas as pd

# Read the data from the CSV file
fut_data = pd.read_csv("/content/gdrive/MyDrive/final_BANKNIFTY_F2.csv")

# Convert 'Date' column to datetime with the format '%Y%m%d'
fut_data['Date'] = pd.to_datetime(fut_data['Date'], format='%Y%m%d')

# Filter out only the data for the year 2018
fut_data_2018 = fut_data[fut_data['Date'].dt.year == 2018]

# Sort the data by 'Date'
fut_data_2018.sort_values(by='Date', inplace=True)

# Convert 'Time' column to datetime time format (assuming time is in HH:MM:SS format)
fut_data_2018['Time'] = pd.to_datetime(fut_data_2018['Time'], format='%H:%M').dt.time

# Define the start and end time for filtering
start_time = pd.to_datetime('09:15:00', format='%H:%M:%S').time()
end_time = pd.to_datetime('15:30:00', format='%H:%M:%S').time()

# Filter the data that occurs within the specified time range
filtered_fut = fut_data_2018[(fut_data_2018['Time'] >= start_time) & (fut_data_2018['Time'] <= end_time)]

# Display the filtered data
filtered_fut

<ipython-input-380-d4d3bbc9de8f>:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fut_data_2018.sort_values(by='Date', inplace=True)
<ipython-input-380-d4d3bbc9de8f>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  fut_data_2018['Time'] = pd.to_datetime(fut_data_2018['Time'], format='%H:%M').dt.time

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest
813079,BANKNIFTY_F2,2018-01-01,09:16:00,25634.00,25634.00,25608.00,25608.00,80.0,NaN
813105,BANKNIFTY_F2,2018-01-01,11:23:00,25652.10,25652.10,25652.10,25652.10,40.0,NaN
813106,BANKNIFTY_F2,2018-01-01,11:24:00,25658.00,25658.00,25653.10,25653.10,120.0,NaN
813107,BANKNIFTY_F2,2018-01-01,11:26:00,25656.00,25656.00,25650.30,25650.30,80.0,NaN
813108,BANKNIFTY_F2,2018-01-01,11:47:00,25650.00,25650.00,25650.00,25650.00,80.0,NaN
...,...,...,...,...,...,...,...,...,...
886586,BANKNIFTY_F2,2018-12-31,15:16:00,27405.70,27409.35,27405.70,27409.35,80.0,40600.0
886585,BANKNIFTY_F2,2018-12-31,15:11:00,27405.70,27405.70,27405.70,27405.70,20.0,40520.0
886584,BANKNIFTY_F2,2018-12-31,15:10:00,27400.00,27400.00,27400.00,27400.00,80.0,40520.0
886593,BANKNIFTY_F2,2018-12-31,15:28:00,27410.00,27412.25,27405.45,27412.25,80.0,40540.0
886561,BANKNIFTY_F2,2018-12-31,14:16:00,27402.05,27402.05,27402.00,27402.00,40.0,40060.0

In [381]:
# Assuming 'filtered_fut' has 'Date' and 'Time' columns
filtered_fut['Time'] = filtered_fut['Time'].astype(str)  # Ensure 'Time' is string type
filtered_fut['Date'] = filtered_fut['Date'].astype(str)
# Create a new string column 'DateTime_str' by combining 'Date' and 'Time'
filtered_fut['DateTime_str'] = filtered_fut['Date'] + ' ' + filtered_fut['Time']

# Convert 'DateTime_str' to datetime using pd.to_datetime with correct format
filtered_fut['datetime'] = pd.to_datetime(filtered_fut['DateTime_str'], format='%Y-%m-%d %H:%M:%S')

# Reorder columns (optional)
cols = ['datetime'] + [col for col in filtered_fut if col != 'datetime']
filtered_fut = filtered_fut[cols]
filtered_fut

<ipython-input-381-54a01791e810>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_fut['Time'] = filtered_fut['Time'].astype(str)  # Ensure 'Time' is string type
<ipython-input-381-54a01791e810>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_fut['Date'] = filtered_fut['Date'].astype(str)
<ipython-input-381-54a01791e810>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_fut['DateTime_str'] = filtered_fut['Date'] + ' ' + filtered_fut['Time']
<ipython-input-381-54a01791e810>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_fut['datetime'] = pd.to_datetime(filtered_fut['DateTime_str'], format='%Y-%m-%d %H:%M:%S')

,datetime,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,DateTime_str
813079,2018-01-01 09:16:00,BANKNIFTY_F2,2018-01-01,09:16:00,25634.00,25634.00,25608.00,25608.00,80.0,NaN,2018-01-01 09:16:00
813105,2018-01-01 11:23:00,BANKNIFTY_F2,2018-01-01,11:23:00,25652.10,25652.10,25652.10,25652.10,40.0,NaN,2018-01-01 11:23:00
813106,2018-01-01 11:24:00,BANKNIFTY_F2,2018-01-01,11:24:00,25658.00,25658.00,25653.10,25653.10,120.0,NaN,2018-01-01 11:24:00
813107,2018-01-01 11:26:00,BANKNIFTY_F2,2018-01-01,11:26:00,25656.00,25656.00,25650.30,25650.30,80.0,NaN,2018-01-01 11:26:00
813108,2018-01-01 11:47:00,BANKNIFTY_F2,2018-01-01,11:47:00,25650.00,25650.00,25650.00,25650.00,80.0,NaN,2018-01-01 11:47:00
...,...,...,...,...,...,...,...,...,...,...,...
886586,2018-12-31 15:16:00,BANKNIFTY_F2,2018-12-31,15:16:00,27405.70,27409.35,27405.70,27409.35,80.0,40600.0,2018-12-31 15:16:00
886585,2018-12-31 15:11:00,BANKNIFTY_F2,2018-12-31,15:11:00,27405.70,27405.70,27405.70,27405.70,20.0,40520.0,2018-12-31 15:11:00
886584,2018-12-31 15:10:00,BANKNIFTY_F2,2018-12-31,15:10:00,27400.00,27400.00,27400.00,27400.00,80.0,40520.0,2018-12-31 15:10:00
886593,2018-12-31 15:28:00,BANKNIFTY_F2,2018-12-31,15:28:00,27410.00,27412.25,27405.45,27412.25,80.0,40540.0,2018-12-31 15:28:00
886561,2018-12-31 14:16:00,BANKNIFTY_F2,2018-12-31,14:16:00,27402.05,27402.05,27402.00,27402.00,40.0,40060.0,2018-12-31 14:16:00

In [382]:
import pandas as pd
df = pd.DataFrame(filtered_fut)
df['Open Interest'] = df['Open Interest'].fillna(0) #Replaced Nan by 0
'''df['Date'] = df['Date'].astype(str)
df['Time'] = df['Time'].astype(str)'''
#df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'].astype(str), format='%d-%m-%Y %H:%M:%S', errors='coerce') #Concatenated Date and Time to set a unique index
df = df.set_index('datetime')
df = df.dropna(subset=['Date', 'Time'])
'''all_days = df.index.normalize().unique()
full_range = pd.concat([pd.DataFrame(index=pd.date_range(start=f"{day} 09:16:00", end=f"{day} 15:30:00", freq='1T')) for day in all_days])'''
all_days = df.index.normalize().unique()
full_range = pd.concat([pd.DataFrame(index=pd.date_range(start=f"{day} 09:15:00", end=f"{day} 15:30:00", freq='1T')) for day in all_days])
full_range = full_range.merge(df, how='left', left_index=True, right_index=True)
full_range.fillna(method='ffill', inplace=True)
full_range.reset_index(inplace=True)
full_range.rename(columns={'index': 'DateTime'}, inplace=True)
full_range['Date'] = full_range['DateTime'].dt.strftime('%d-%m-%Y')
full_range['Time'] = full_range['DateTime'].dt.strftime('%H:%M:%S')
full_range = full_range[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest']]
full_range['DateTime'] = pd.to_datetime(full_range['Date'] + ' ' + full_range['Time'], format='%d-%m-%Y %H:%M:%S')
full_range.set_index('DateTime', inplace=True)

aggregation = {
    'Symbol': 'first',
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum',
    'Open Interest': 'last'
}

resampled_df = full_range.resample('5T').apply(aggregation)

# Reset index to split DateTime into Date and Time
resampled_df.reset_index(inplace=True)
resampled_df['Date'] = resampled_df['DateTime'].dt.strftime('%d-%m-%Y')
resampled_df['Time'] = resampled_df['DateTime'].dt.strftime('%H:%M:%S')

resampled_df.drop(columns=['DateTime'], inplace=True)
resampled_df = resampled_df[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest']]

resampled_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest
0,BANKNIFTY_F2,01-01-2018,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0
1,BANKNIFTY_F2,01-01-2018,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0
2,BANKNIFTY_F2,01-01-2018,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0
3,BANKNIFTY_F2,01-01-2018,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0
4,BANKNIFTY_F2,01-01-2018,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0
...,...,...,...,...,...,...,...,...,...
104903,BANKNIFTY_F2,31-12-2018,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0
104904,BANKNIFTY_F2,31-12-2018,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0
104905,BANKNIFTY_F2,31-12-2018,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0
104906,BANKNIFTY_F2,31-12-2018,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0
104907,BANKNIFTY_F2,31-12-2018,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0

In [383]:
 df = pd.DataFrame(resampled_df)

df['DateTime'] = pd.to_datetime(df['Date'].str.strip() + ' ' + df['Time'].str.strip(), format='%d-%m-%Y %H:%M:%S', errors='coerce')
df = df.dropna(subset=['DateTime'])  # Remove rows where DateTime could not be parsed
df.set_index('DateTime', inplace=True)
# Calculate typical price for VWAP
df.loc[:, 'Price'] = (df['High'] + df['Low'] + df['Close']) / 3

# Calculate cumulative values for VWAP
cumulative_price_volume = (df['Price'] * df['Volume']).cumsum()
cumulative_volume = df['Volume'].cumsum()

df.loc[:, 'VWAP'] = cumulative_price_volume / cumulative_volume #Calculating for 1 min

# Aggregate the data into 5-minute intervals
resampled = df.resample('5T').agg({
    'Symbol': 'first',
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum',
    'Open Interest': 'last',
    'Price': 'last'
})
# Calculate cumulative values for the resampled data
resampled['Price'] = (resampled['High'] + resampled['Low'] + resampled['Close']) / 3
resampled_cumulative_price_volume = (resampled['Price'] * resampled['Volume']).cumsum()
resampled_cumulative_volume = resampled['Volume'].cumsum()

# Calculating VWAP for the 5-minute intervals
resampled['VWAP'] = resampled_cumulative_price_volume / resampled_cumulative_volume

resampled.reset_index(inplace=True)
resampled['Date'] = resampled['DateTime'].dt.strftime('%d-%m-%Y')
resampled['Time'] = resampled['DateTime'].dt.strftime('%H:%M:%S')

resampled.drop(columns=['DateTime', 'Price'], inplace=True) # Dropped DateTime column and unnecessary columns
resampled = resampled[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest', 'VWAP']]

resampled.dropna(inplace=True)
resampled.head(60)

<ipython-input-383-4d2011d4afd1>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resampled.dropna(inplace=True)

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP
0,BANKNIFTY_F2,01-01-2018,09:15:00,25634.0,25643.1,25608.0,25643.1,480.0,0.0,25631.400000
1,BANKNIFTY_F2,01-01-2018,09:20:00,25631.5,25675.7,25631.5,25665.3,600.0,0.0,25645.900000
2,BANKNIFTY_F2,01-01-2018,09:25:00,25665.3,25665.3,25655.1,25655.1,240.0,0.0,25648.190909
3,BANKNIFTY_F2,01-01-2018,09:30:00,25647.7,25647.7,25647.7,25647.7,240.0,0.0,25648.115385
4,BANKNIFTY_F2,01-01-2018,09:35:00,25647.7,25647.7,25647.0,25647.0,440.0,0.0,25647.921333
5,BANKNIFTY_F2,01-01-2018,09:40:00,25655.1,25661.9,25655.0,25655.0,320.0,0.0,25649.214943
6,BANKNIFTY_F2,01-01-2018,09:45:00,25653.0,25653.0,25645.0,25650.0,440.0,0.0,25649.233816
7,BANKNIFTY_F2,01-01-2018,09:50:00,25645.0,25650.0,25645.0,25650.0,400.0,0.0,25649.119831
8,BANKNIFTY_F2,01-01-2018,09:55:00,25645.0,25650.0,25645.0,25650.0,400.0,0.0,25649.031461
9,BANKNIFTY_F2,01-01-2018,10:00:00,25642.0,25642.0,25642.0,25642.0,1680.0,0.0,25646.777099
10,BANKNIFTY_F2,01-01-2018,10:05:00,25642.0,25655.0,25642.0,25653.7,1200.0,0.0,25647.421118
11,BANKNIFTY_F2,01-01-2018,10:10:00,25660.0,25660.0,25660.0,25660.0,280.0,0.0,25647.945238
12,BANKNIFTY_F2,01-01-2018,10:15:00,25660.0,25660.0,25660.0,25660.0,200.0,0.0,25648.293642
13,BANKNIFTY_F2,01-01-2018,10:20:00,25660.0,25660.0,25659.9,25659.9,640.0,0.0,25649.279012
14,BANKNIFTY_F2,01-01-2018,10:25:00,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25650.733942
15,BANKNIFTY_F2,01-01-2018,10:30:00,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25651.838286
16,BANKNIFTY_F2,01-01-2018,10:35:00,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25652.705137
17,BANKNIFTY_F2,01-01-2018,10:40:00,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25653.403668
18,BANKNIFTY_F2,01-01-2018,10:45:00,25659.9,25659.9,25648.9,25649.0,680.0,0.0,25653.361759
19,BANKNIFTY_F2,01-01-2018,10:50:00,25649.0,25649.0,25649.0,25649.0,200.0,0.0,25653.295871
20,BANKNIFTY_F2,01-01-2018,10:55:00,25649.0,25649.0,25649.0,25649.0,200.0,0.0,25653.231944
21,BANKNIFTY_F2,01-01-2018,11:00:00,25649.0,25655.0,25649.0,25655.0,240.0,0.0,25653.227875
22,BANKNIFTY_F2,01-01-2018,11:05:00,25655.0,25655.0,25655.0,25655.0,200.0,0.0,25653.253410
23,BANKNIFTY_F2,01-01-2018,11:10:00,25655.0,25655.0,25655.0,25655.0,200.0,0.0,25653.278220
24,BANKNIFTY_F2,01-01-2018,11:15:00,25655.0,25655.0,25647.1,25655.0,520.0,0.0,25653.245753
25,BANKNIFTY_F2,01-01-2018,11:20:00,25655.0,25658.0,25652.1,25653.1,680.0,0.0,25653.297120
26,BANKNIFTY_F2,01-01-2018,11:25:00,25658.0,25658.0,25650.3,25650.3,520.0,0.0,25653.282954
27,BANKNIFTY_F2,01-01-2018,11:30:00,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.256214
28,BANKNIFTY_F2,01-01-2018,11:35:00,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.230763
29,BANKNIFTY_F2,01-01-2018,11:40:00,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.206510
30,BANKNIFTY_F2,01-01-2018,11:45:00,25656.0,25656.0,25650.0,25650.0,480.0,0.0,25653.173379
31,BANKNIFTY_F2,01-01-2018,11:50:00,25650.0,25650.0,25650.0,25650.0,240.0,0.0,25653.130399
32,BANKNIFTY_F2,01-01-2018,11:55:00,25650.0,25650.0,25650.0,25650.0,200.0,0.0,25653.095461
33,BANKNIFTY_F2,01-01-2018,12:00:00,25650.0,25650.0,25645.0,25645.0,240.0,0.0,25653.010499
34,BANKNIFTY_F2,01-01-2018,12:05:00,25645.0,25645.0,25645.0,25645.0,200.0,0.0,25652.923239
35,BANKNIFTY_F2,01-01-2018,12:10:00,25645.0,25645.0,25637.9,25642.0,600.0,0.0,25652.565963
36,BANKNIFTY_F2,01-01-2018,12:15:00,25642.0,25642.0,25639.3,25639.3,320.0,0.0,25652.360719
37,BANKNIFTY_F2,01-01-2018,12:20:00,25639.3,25639.3,25635.1,25635.1,480.0,0.0,25651.975439
38,BANKNIFTY_F2,01-01-2018,12:25:00,25635.1,25635.2,25635.1,25635.2,560.0,0.0,25651.512205
39,BANKNIFTY_F2,01-01-2018,12:30:00,25635.2,25635.2,25635.2,25635.2,600.0,0.0,25651.044359
40,BANKNIFTY_F2,01-01-2018,12:35:00,25638.0,25640.0,25637.5,25640.0,320.0,0.0,25650.865411
41,BANKNIFTY_F2,01-01-2018,12:40:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.764055
42,BANKNIFTY_F2,01-01-2018,12:45:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.664572
43,BANKNIFTY_F2,01-01-2018,12:50:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.566911
44,BANKNIFTY_F2,01-01-2018,12:55:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.471022
45,BANKNIFTY_F2,01-01-2018,13:00:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.376859
46,BANKNIFTY_F2,01-01-2018,13:05:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.284373
47,BANKNIFTY_F2,01-01-2018,13:10:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.193522
48,BANKNIFTY_F2,01-01-2018,13:15:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.104262
49,BANKNIFTY_F2,01-01-2018,13:20:00,25635.8,25635.8,25625.1,25625.1,840.0,0.0,25649.343806
50,BANKNIFTY_F2,01-01-2018,13:25:00,25616.0,25630.0,25616.0,25630.0,320.0,0.0,25649.023667
51,BANKNIFTY_F2,01-01-2018,13:30:00,25637.3,25637.3,25637.3,25637.3,240.0,0.0,25648.907591
52,BANKNIFTY_F2,01-01-2018,13:35:00,25637.3,25637.3,25637.3,25637.3,200.0,0.0,25648.812602
53,BANKNIFTY_F2,01-01-2018,13:40:00,25637.3,25637.3,25625.0,25625.0,240.0,0.0,25648.620908
54,BANKNIFTY_F2,01-01-2018,13:45:00,25625.0,25625.0,25625.0,25625.0,200.0,0.0,25648.431029
55,BANKNIFTY_F2,01-01-2018,13:50:00,25625.0,25634.1,25625.0,25634.1,400.0,0.0,25648.156276
56,BANKNIFTY_F2,01-01-2018,13:55:00,25634.1,25634.1,25634.1,25634.1,400.0,0.0,25647.937331
57,BANKNIFTY_F2,01-01-2018,14:00:00,25634.1,25634.1,25634.1,25634.1,400.0,0.0,25647.725102
58,BANKNIFTY_F2,01-01-2018,14:05:00,25637.1,25637.1,25635.0,25635.0,280.0,0.0,25647.597370
59,BANKNIFTY_F2,01-01-2018,14:10:00,25635.0,25637.3,25635.0,25636.3,600.0,0.0,25647.343719

In [384]:
resampled_df_copy = resampled

# Converted 'Date' and 'Time' columns to strings so that we can concatenate
resampled_df_copy['Date'] = resampled_df_copy['Date'].astype(str)
resampled_df_copy['Time'] = resampled_df_copy['Time'].astype(str)
resampled_df_copy['DateTime'] = pd.to_datetime(resampled_df_copy['Date'] + ' ' + resampled_df_copy['Time'], format='%d-%m-%Y %H:%M:%S')

resampled_df_copy = resampled_df_copy.dropna(subset=['DateTime'])
resampled_df_copy.set_index('DateTime', inplace=True) #Setting DateTime column as index

resampled_df_copy['EMA_12'] = resampled_df_copy['Close'].ewm(span=12, adjust=False).mean() #12-period EMA
resampled_df_copy['EMA_26'] = resampled_df_copy['Close'].ewm(span=26, adjust=False).mean() #26-period EMA

resampled_df_copy['MACD'] = resampled_df_copy['EMA_12'] - resampled_df_copy['EMA_26'] # MACD= 12_EMA - 26_EMA

resampled_df_copy.drop(['Date'	,'Time','EMA_12', 'EMA_26'], axis=1, inplace=True)

resampled_df_copy['Date'] = resampled_df_copy.index.strftime('%d-%m-%Y')
resampled_df_copy['Time'] = resampled_df_copy.index.strftime('%H:%M:%S')
resampled_df_copy = resampled_df_copy[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest','VWAP' ,'MACD']]
resampled_df_copy

<ipython-input-384-5cc5a4e45041>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resampled_df_copy['Date'] = resampled_df_copy['Date'].astype(str)

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD
DateTime,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,01-01-2018,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,0.000000
2018-01-01 09:20:00,BANKNIFTY_F2,01-01-2018,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,1.770940
2018-01-01 09:25:00,BANKNIFTY_F2,01-01-2018,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,2.324572
2018-01-01 09:30:00,BANKNIFTY_F2,01-01-2018,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,2.141525
2018-01-01 09:35:00,BANKNIFTY_F2,01-01-2018,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,1.917867
...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 15:10:00,BANKNIFTY_F2,31-12-2018,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,2.657355
2018-12-31 15:15:00,BANKNIFTY_F2,31-12-2018,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,3.337394
2018-12-31 15:20:00,BANKNIFTY_F2,31-12-2018,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,3.122185
2018-12-31 15:25:00,BANKNIFTY_F2,31-12-2018,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,2.654744
2018-12-31 15:30:00,BANKNIFTY_F2,31-12-2018,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,2.038890

In [385]:
data = resampled_df_copy.copy()
data['DateTime'] = pd.to_datetime(data['Date'] + ' ' + data['Time'], format='%d-%m-%Y %H:%M:%S')
data.reset_index(drop=True, inplace=True)
df = pd.DataFrame(data)

# Convert DateTime to datetime object
df['DateTime'] = pd.to_datetime(df['DateTime'])

# Extracting the Date Part from 'DateTime'
df['Date'] = df['DateTime'].dt.date

# Calculate POC
aggregated = df.groupby(['Date', 'Close']).agg({'Volume': 'sum'}).reset_index()
poc = aggregated.loc[aggregated.groupby('Date')['Volume'].idxmax()]
poc.rename(columns={'Close': 'Point of Control'}, inplace=True)

# Calculate Local Maximum and Minimum
daily_high_low = df.groupby('Date').agg({'High': 'max', 'Low': 'min'}).reset_index()
daily_high_low.rename(columns={'High': 'Local Maximum', 'Low': 'Local Minimum'}, inplace=True)

# Merge POC and daily high/low back into the original dataframe
df = df.merge(poc[['Date', 'Point of Control']], on='Date', how='left')
df = df.merge(daily_high_low, on='Date', how='left')
df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,DateTime,Point of Control,Local Maximum,Local Minimum
0,BANKNIFTY_F2,2018-01-01,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,0.000000,2018-01-01 09:15:00,25659.9,25675.70,25481.3
1,BANKNIFTY_F2,2018-01-01,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,1.770940,2018-01-01 09:20:00,25659.9,25675.70,25481.3
2,BANKNIFTY_F2,2018-01-01,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,2.324572,2018-01-01 09:25:00,25659.9,25675.70,25481.3
3,BANKNIFTY_F2,2018-01-01,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,2.141525,2018-01-01 09:30:00,25659.9,25675.70,25481.3
4,BANKNIFTY_F2,2018-01-01,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,1.917867,2018-01-01 09:35:00,25659.9,25675.70,25481.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18615,BANKNIFTY_F2,2018-12-31,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,2.657355,2018-12-31 15:10:00,27393.6,27511.15,27319.2
18616,BANKNIFTY_F2,2018-12-31,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,3.337394,2018-12-31 15:15:00,27393.6,27511.15,27319.2
18617,BANKNIFTY_F2,2018-12-31,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,3.122185,2018-12-31 15:20:00,27393.6,27511.15,27319.2
18618,BANKNIFTY_F2,2018-12-31,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,2.654744,2018-12-31 15:25:00,27393.6,27511.15,27319.2
18619,BANKNIFTY_F2,2018-12-31,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,2.038890,2018-12-31 15:30:00,27393.6,27511.15,27319.2

In [386]:
df.set_index('DateTime', inplace=True)

def calculate_vah_val_poc(df_day):
    total_volume = df_day['Volume'].sum()
    volume_threshold = 0.7 * total_volume  # 70% volume threshold

    df_day['midpoint'] = (df_day['High'] + df_day['Low']) / 2  # Calculate the midpoint for each row
    df_sorted = df_day.sort_values(by='midpoint', ascending=False)

    cumulative_volume = 0
    VAH = None
    VAL = None
    POC = df_sorted.iloc[0]['midpoint']  # Initialize POC as the highest midpoint

    # Accumulate volume to find VAL and POC
    for index, row in df_sorted.iterrows():
        cumulative_volume += row['Volume']
        if cumulative_volume >= volume_threshold:
            VAL = row['midpoint']
            break

    # The highest price in the sorted DataFrame is VAH
    VAH = df_sorted.iloc[0]['midpoint']

    # Calculate Value Area Width in percentage terms
    value_area_width = ((VAH - VAL) / VAH) * 100

    return pd.Series({'VAH': VAH, 'VAL': VAL, 'POC': POC, 'Value Area Width (%)': value_area_width})

# Group by each day and apply the calculate_vah_val_poc function
df_daily = df.groupby(df.index.date).apply(calculate_vah_val_poc)

# Merge the daily results back into the original DataFrame
df = df.join(df_daily, on=df.index.date)
df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%)
DateTime,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,0.000000,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,1.770940,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,2.324572,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,2.141525,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,1.917867,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 15:10:00,BANKNIFTY_F2,2018-12-31,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,2.657355,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241
2018-12-31 15:15:00,BANKNIFTY_F2,2018-12-31,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,3.337394,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241
2018-12-31 15:20:00,BANKNIFTY_F2,2018-12-31,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,3.122185,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241
2018-12-31 15:25:00,BANKNIFTY_F2,2018-12-31,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,2.654744,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241
2018-12-31 15:30:00,BANKNIFTY_F2,2018-12-31,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,2.038890,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241

In [387]:
q = pd.DataFrame(resampled)

q['DateTime'] = pd.to_datetime(q['Date'] + ' ' + q['Time'], format='%d-%m-%Y %H:%M:%S')
q.set_index('DateTime', inplace=True)

def calculate_vah_val(df_day):
    total_volume = df_day['Volume'].sum()
    volume_threshold = 0.7 * total_volume #Here i have considered 70%

    df_day['midpoint'] = (df_day['High'] + df_day['Low']) / 2   # Calculating the midpoint for each row
    df_sorted = df_day.sort_values(by='midpoint', ascending=False)

    cumulative_volume = 0
    VAH = None
    VAL = None

    # Accumulate volume and find VAH and VAL
    for index, row in df_sorted.iterrows():
        cumulative_volume += row['Volume']
        if cumulative_volume >= volume_threshold:
            VAL = row['midpoint']
            break

    # The highest price in the sorted DataFrame is VAH
    VAH = df_sorted.iloc[0]['midpoint']
    return pd.Series({'VAH': VAH, 'VAL': VAL})

result = q.groupby(df.index.date).apply(calculate_vah_val)
result

                  VAH        VAL
2018-01-01  25660.200  25545.300
2018-01-02  25518.600  25422.450
2018-01-03  25544.500  25488.250
2018-01-04  25565.700  25510.000
2018-01-05  25711.500  25624.950
...               ...        ...
2018-12-24  27053.125  26915.450
2018-12-26  27179.100  26676.375
2018-12-27  27302.500  27097.375
2018-12-28  27396.600  27317.525
2018-12-31  27480.675  27386.625

[245 rows x 2 columns]

In [388]:
result = result.rename_axis('Date').rename(columns={'Date': 'Date'})
result

                  VAH        VAL
Date
2018-01-01  25660.200  25545.300
2018-01-02  25518.600  25422.450
2018-01-03  25544.500  25488.250
2018-01-04  25565.700  25510.000
2018-01-05  25711.500  25624.950
...               ...        ...
2018-12-24  27053.125  26915.450
2018-12-26  27179.100  26676.375
2018-12-27  27302.500  27097.375
2018-12-28  27396.600  27317.525
2018-12-31  27480.675  27386.625

[245 rows x 2 columns]

In [389]:
poc_last = df.groupby('Date')['Point of Control'].last().reset_index()
result_df = pd.DataFrame(result)

# Merge the result DataFrame with the last POC for each date
final_result = result_df.merge(poc_last, on='Date', how='left')

# Rename columns for clarity
final_result.rename(columns={'Point of Control': 'poc'}, inplace=True)
final_result

           Date        VAH        VAL       poc
0    2018-01-01  25660.200  25545.300  25659.90
1    2018-01-02  25518.600  25422.450  25417.90
2    2018-01-03  25544.500  25488.250  25511.00
3    2018-01-04  25565.700  25510.000  25500.00
4    2018-01-05  25711.500  25624.950  25685.20
..          ...        ...        ...       ...
240  2018-12-24  27053.125  26915.450  26945.20
241  2018-12-26  27179.100  26676.375  26621.85
242  2018-12-27  27302.500  27097.375  27205.00
243  2018-12-28  27396.600  27317.525  27254.85
244  2018-12-31  27480.675  27386.625  27393.60

[245 rows x 4 columns]

In [390]:
dff=final_result
dff['VAH_3day'] = dff['VAH'].rolling(window=3).mean()
dff['VAL_3day'] = dff['VAL'].rolling(window=3).mean()
dff['VAH_5day'] = dff['VAH'].rolling(window=5).mean()
dff['VAL_5day'] = dff['VAL'].rolling(window=5).mean()

# Calculate rolling POC
dff['POC_3day'] = dff['poc'].rolling(window=3).mean()
dff['POC_5day'] = dff['poc'].rolling(window=5).mean()
dff

,Date,VAH,VAL,poc,VAH_3day,VAL_3day,VAH_5day,VAL_5day,POC_3day,POC_5day
0,2018-01-01,25660.200,25545.300,25659.90,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-02,25518.600,25422.450,25417.90,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-03,25544.500,25488.250,25511.00,25574.433333,25485.333333,NaN,NaN,25529.600000,NaN
3,2018-01-04,25565.700,25510.000,25500.00,25542.933333,25473.566667,NaN,NaN,25476.300000,NaN
4,2018-01-05,25711.500,25624.950,25685.20,25607.233333,25541.066667,25600.100,25518.190,25565.400000,25554.80
...,...,...,...,...,...,...,...,...,...,...
240,2018-12-24,27053.125,26915.450,26945.20,27342.166667,27117.741667,27381.730,27183.655,27118.850000,27216.57
241,2018-12-26,27179.100,26676.375,26621.85,27241.458333,26892.941667,27344.150,27098.840,26876.133333,27089.68
242,2018-12-27,27302.500,27097.375,27205.00,27178.241667,26896.400000,27301.620,27025.395,26924.016667,27036.68
243,2018-12-28,27396.600,27317.525,27254.85,27292.733333,27030.425000,27284.695,27018.745,27027.233333,27017.65
244,2018-12-31,27480.675,27386.625,27393.60,27393.258333,27267.175000,27282.400,27078.670,27284.483333,27084.10

In [391]:
def calculate_ghost_zone(df_day, vah, val):
    # Filter prices above VAH and below VAL
    above_vah = df_day[df_day['High'] > vah]
    below_val = df_day[df_day['Low'] < val]

    highest_above_vah = above_vah['High'].max() if not above_vah.empty else None
    lowest_below_val = below_val['Low'].min() if not below_val.empty else None

    return pd.Series({'Highest Above VAH': highest_above_vah, 'Lowest Below VAL': lowest_below_val})

# Join the original df with the calculated daily VAH and VAL
daily_vah_val = result[['VAH', 'VAL']]

# Iterate over each day to calculate the ghost zone
ghost_zones = []
for date, vah_val in daily_vah_val.iterrows():
    vah = vah_val['VAH']
    val = vah_val['VAL']
    df_day = df[df.index.date == pd.Timestamp(date).date()]

    ghost_zone = calculate_ghost_zone(df_day, vah, val)
    ghost_zones.append(ghost_zone)

# Convert list of series to DataFrame
ghost_zones_df = pd.DataFrame(ghost_zones, index=daily_vah_val.index)

# Combine with the existing result DataFrame
result_with_ghost_zones = result.join(ghost_zones_df)
result_with_ghost_zones

                  VAH        VAL  Highest Above VAH  Lowest Below VAL
Date
2018-01-01  25660.200  25545.300           25675.70           25481.3
2018-01-02  25518.600  25422.450           25554.60           25360.0
2018-01-03  25544.500  25488.250           25550.00           25432.8
2018-01-04  25565.700  25510.000           25573.30           25436.3
2018-01-05  25711.500  25624.950           25720.00           25565.0
...               ...        ...                ...               ...
2018-12-24  27053.125  26915.450           27085.00           26854.6
2018-12-26  27179.100  26676.375           27190.00           26577.5
2018-12-27  27302.500  27097.375           27368.65           27001.0
2018-12-28  27396.600  27317.525           27417.25           27033.8
2018-12-31  27480.675  27386.625           27511.15           27319.2

[245 rows x 4 columns]

In [392]:
merged_df = df.merge(result_with_ghost_zones[['Highest Above VAH', 'Lowest Below VAL']], left_on=df.index.date, right_index=True, how='left')
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL
DateTime,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,0.000000,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,1.770940,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,2.324572,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,2.141525,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,1.917867,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 15:10:00,BANKNIFTY_F2,2018-12-31,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,2.657355,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2
2018-12-31 15:15:00,BANKNIFTY_F2,2018-12-31,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,3.337394,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2
2018-12-31 15:20:00,BANKNIFTY_F2,2018-12-31,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,3.122185,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2
2018-12-31 15:25:00,BANKNIFTY_F2,2018-12-31,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,2.654744,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2
2018-12-31 15:30:00,BANKNIFTY_F2,2018-12-31,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,2.038890,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2

In [393]:
merged_df['Previous Day VAH'] = merged_df['VAH'].shift(1)
merged_df['Previous Day VAL'] = merged_df['VAL'].shift(1)

# Function to determine gap up or gap down
def gap_type(row):
    if row['Open'] >= row['Previous Day VAH']:
        return 'Gap Up'
    elif row['Close'] <= row['Previous Day VAL']:
        return 'Gap Down'
    else:
        return ''

# Apply the function to each row
merged_df['Gap Type'] = merged_df.apply(gap_type, axis=1)

# Handle consecutive missing days
merged_df['Date'] = pd.to_datetime(merged_df['Date'])
merged_df['Date_diff'] = merged_df['Date'].diff().dt.days
merged_df.loc[merged_df['Date_diff'] > 1, 'Gap Type'] = ''

merged_df['Gap Type'] = merged_df.groupby('Date')['Gap Type'].transform(lambda x: x.iloc[0]).fillna('')

# Drop the auxiliary columns if needed
merged_df.drop(['Previous Day VAH', 'Previous Day VAL', 'Date_diff'], axis=1, inplace=True)
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL,Gap Type
DateTime,,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,...,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,...,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,...,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,...,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,...,25659.9,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 15:10:00,BANKNIFTY_F2,2018-12-31,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,...,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,
2018-12-31 15:15:00,BANKNIFTY_F2,2018-12-31,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,...,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,
2018-12-31 15:20:00,BANKNIFTY_F2,2018-12-31,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,...,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,
2018-12-31 15:25:00,BANKNIFTY_F2,2018-12-31,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,...,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,
2018-12-31 15:30:00,BANKNIFTY_F2,2018-12-31,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,...,27393.6,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,

In [394]:
def is_gap_filled(row):
    if row['Open'] >= row['Previous Day Low'] and row['Open'] <= row['High']:
        return 'Yes'
    else:
        return 'No'

merged_df['Previous Day Low'] = merged_df['Low'].shift(1)
merged_df['Gap Filled'] = merged_df.apply(is_gap_filled, axis=1)
merged_df.drop('Previous Day Low', axis=1, inplace=True)
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL,Gap Type,Gap Filled
DateTime,,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,...,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,,No
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,...,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,,Yes
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,...,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,,Yes
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,...,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,,No
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,...,25675.70,25481.3,25660.200,25545.300,25660.200,0.447775,25675.70,25481.3,,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2018-12-31 15:10:00,BANKNIFTY_F2,2018-12-31,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,...,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,,Yes
2018-12-31 15:15:00,BANKNIFTY_F2,2018-12-31,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,...,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,,Yes
2018-12-31 15:20:00,BANKNIFTY_F2,2018-12-31,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,...,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,,Yes
2018-12-31 15:25:00,BANKNIFTY_F2,2018-12-31,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,...,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,,Yes
2018-12-31 15:30:00,BANKNIFTY_F2,2018-12-31,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,...,27511.15,27319.2,27480.675,27386.625,27480.675,0.342241,27511.15,27319.2,,Yes

In [395]:
merged_df.reset_index(inplace=True)
merged_df['Date'] = merged_df['DateTime'].dt.date
merged_df = pd.merge(merged_df, dff, on='Date', how='left')
merged_df.drop('Date', axis=1, inplace=True)
merged_df.head()

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Gap Filled,VAH_y,VAL_y,poc,VAH_3day,VAL_3day,VAH_5day,VAL_5day,POC_3day,POC_5day
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.0,25643.1,25608.0,25643.1,480.0,0.0,25631.400000,...,No,25660.2,25545.3,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.5,25675.7,25631.5,25665.3,600.0,0.0,25645.900000,...,Yes,25660.2,25545.3,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.3,25665.3,25655.1,25655.1,240.0,0.0,25648.190909,...,Yes,25660.2,25545.3,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.7,25647.7,25647.7,25647.7,240.0,0.0,25648.115385,...,No,25660.2,25545.3,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.7,25647.7,25647.0,25647.0,440.0,0.0,25647.921333,...,Yes,25660.2,25545.3,25659.9,NaN,NaN,NaN,NaN,NaN,NaN

In [396]:
merged_df

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Gap Filled,VAH_y,VAL_y,poc,VAH_3day,VAL_3day,VAH_5day,VAL_5day,POC_3day,POC_5day
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,...,No,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,...,Yes,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,...,Yes,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,...,No,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,...,Yes,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18615,2018-12-31 15:10:00,BANKNIFTY_F2,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,...,Yes,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1
18616,2018-12-31 15:15:00,BANKNIFTY_F2,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,...,Yes,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1
18617,2018-12-31 15:20:00,BANKNIFTY_F2,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,...,Yes,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1
18618,2018-12-31 15:25:00,BANKNIFTY_F2,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,...,Yes,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1
18619,2018-12-31 15:30:00,BANKNIFTY_F2,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,...,Yes,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1

In [397]:
import pandas as pd
fut_df1 = pd.DataFrame(merged_df)

fut_df1.reset_index(drop=True, inplace=True)
fut_df1['DateTime'] = pd.to_datetime(fut_df1['DateTime'])

# Identify the first day of each weekly expiry (assuming weekly expiry is every Thursday)
fut_df1['Week_Start'] = fut_df1['DateTime'].dt.to_period('W').apply(lambda r: r.start_time)
week_starts = fut_df1['Week_Start'].unique()

fut_df1['AWAP'] = pd.Series(dtype='float64')
for week_start in week_starts:
    mask = fut_df1['Week_Start'] == week_start
    weekly_data = fut_df1[mask]
    fut_df1.loc[mask, 'AWAP'] = (weekly_data['Close'] * weekly_data['Volume']).cumsum() / weekly_data['Volume'].cumsum()

fut_df1['AWAP'] = fut_df1.groupby('Week_Start')['AWAP'].ffill()
fut_df1.drop(columns=['Week_Start'], inplace=True)

In [398]:
fut_df1

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,VAH_y,VAL_y,poc,VAH_3day,VAL_3day,VAH_5day,VAL_5day,POC_3day,POC_5day,AWAP
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,...,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN,25643.100000
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,...,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN,25655.433333
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,...,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN,25655.372727
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,...,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN,25654.192308
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,...,25660.200,25545.300,25659.9,NaN,NaN,NaN,NaN,NaN,NaN,25652.610000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18615,2018-12-31 15:10:00,BANKNIFTY_F2,15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,...,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1,27397.739299
18616,2018-12-31 15:15:00,BANKNIFTY_F2,15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,...,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1,27397.854316
18617,2018-12-31 15:20:00,BANKNIFTY_F2,15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,...,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1,27397.922324
18618,2018-12-31 15:25:00,BANKNIFTY_F2,15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,...,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1,27397.958845
18619,2018-12-31 15:30:00,BANKNIFTY_F2,15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,...,27480.675,27386.625,27393.6,27393.258333,27267.175,27282.4,27078.67,27284.483333,27084.1,27397.972344

In [399]:
fut_df1.columns

Index(['DateTime', 'Symbol', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume',
       'Open Interest', 'VWAP', 'MACD', 'Point of Control', 'Local Maximum',
       'Local Minimum', 'VAH_x', 'VAL_x', 'POC', 'Value Area Width (%)',
       'Highest Above VAH', 'Lowest Below VAL', 'Gap Type', 'Gap Filled',
       'VAH_y', 'VAL_y', 'poc', 'VAH_3day', 'VAL_3day', 'VAH_5day', 'VAL_5day',
       'POC_3day', 'POC_5day', 'AWAP'],
      dtype='object')

In [400]:
testing=fut_df1.copy()
testing.drop(columns=['Symbol',	'Time'], inplace=True)
testing.rename(columns={'DateTime':'datetime','Open': 'open', 'Close': 'close','High':'high',	'Low':'low',	'Close':'close',	'Volume':'volume',	'Open Interest':'oi',	'VWAP':'vwap',
                   'MACD':'macd',
 'Point of Control':'poc',
 'Local Maximum':'local_max',
 'Local Minimum':'local_min',
 'VAH_x':'vah',
 'VAL_x':'val',
 'POC':'poc',
 'Value Area Width (%)':'value_area_width(%)',
 'Highest Above VAH':'highest_above_vah',
 'Lowest Below VAL':'lowest_below_val',
 'Gap Type':'gap_type',
 'Gap Filled':'gap_filled',
 'VAH_3day':'3_day_vah',
 'VAH_5day':'5_day_vah',
 'VAL_3day':'3_day_val',
 'VAL_5day':'5_day_val',
 'POC_3day':'3_day_poc',
 'POC_5day':'5_day_poc',
 'AWAP':'awap'}, inplace=True)
new_column_order = ['datetime','open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

# Reorder the DataFrame columns
fut_reordered = testing[new_column_order]
fut_reordered

,datetime,open,high,low,close,volume,oi,vwap,awap,macd,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-01-01 09:15:00,25634.0,25643.10,25608.00,25643.10,480.0,0.0,25631.400000,25643.100000,0.000000,...,25675.70,25481.3,,No,NaN,NaN,NaN,NaN,NaN,NaN
1,2018-01-01 09:20:00,25631.5,25675.70,25631.50,25665.30,600.0,0.0,25645.900000,25655.433333,1.770940,...,25675.70,25481.3,,Yes,NaN,NaN,NaN,NaN,NaN,NaN
2,2018-01-01 09:25:00,25665.3,25665.30,25655.10,25655.10,240.0,0.0,25648.190909,25655.372727,2.324572,...,25675.70,25481.3,,Yes,NaN,NaN,NaN,NaN,NaN,NaN
3,2018-01-01 09:30:00,25647.7,25647.70,25647.70,25647.70,240.0,0.0,25648.115385,25654.192308,2.141525,...,25675.70,25481.3,,No,NaN,NaN,NaN,NaN,NaN,NaN
4,2018-01-01 09:35:00,25647.7,25647.70,25647.00,25647.00,440.0,0.0,25647.921333,25652.610000,1.917867,...,25675.70,25481.3,,Yes,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18615,2018-12-31 15:10:00,27400.0,27405.70,27400.00,27405.70,260.0,40520.0,26123.450778,27397.739299,2.657355,...,27511.15,27319.2,,Yes,27393.258333,27282.4,27267.175,27078.67,27284.483333,27084.1
18616,2018-12-31 15:15:00,27405.7,27416.00,27405.70,27416.00,340.0,40600.0,26123.453659,27397.854316,3.337394,...,27511.15,27319.2,,Yes,27393.258333,27282.4,27267.175,27078.67,27284.483333,27084.1
18617,2018-12-31 15:20:00,27416.0,27416.50,27405.00,27407.10,400.0,40580.0,26123.457041,27397.922324,3.122185,...,27511.15,27319.2,,Yes,27393.258333,27282.4,27267.175,27078.67,27284.483333,27084.1
18618,2018-12-31 15:25:00,27405.6,27412.25,27403.80,27403.80,340.0,40540.0,26123.459909,27397.958845,2.654744,...,27511.15,27319.2,,Yes,27393.258333,27282.4,27267.175,27078.67,27284.483333,27084.1
18619,2018-12-31 15:30:00,27405.1,27405.10,27401.05,27401.05,240.0,40540.0,26123.461926,27397.972344,2.038890,...,27511.15,27319.2,,Yes,27393.258333,27282.4,27267.175,27078.67,27284.483333,27084.1

In [401]:
#df_reordered.to_csv('fut_testing.csv', index=True)

In [402]:
import pandas as pd
final_opt_df['datetime'] = pd.to_datetime(final_opt_df['datetime'])

fut_reordered = fut_reordered.reset_index()
fut_reordered['datetime'] = pd.to_datetime(fut_reordered['datetime'])
finals = pd.merge(final_opt_df, fut_reordered, left_on='datetime', right_on='datetime', how='inner')
finals

<ipython-input-402-76025f618160>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_opt_df['datetime'] = pd.to_datetime(final_opt_df['datetime'])

,datetime,atm,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes,index,open,high,low,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-03-01 09:15:00,25069.4,25500,0.592719,0.804578,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2...",3116,25242.9,25262.1,25127.6,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
1,2018-03-01 09:20:00,25069.4,25300,0.636941,0.844229,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2...",3117,25262.0,25314.9,25257.2,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
2,2018-03-01 09:25:00,25069.4,25400,0.651194,0.837541,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2...",3118,25310.0,25339.9,25310.0,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
3,2018-03-01 09:30:00,25069.4,25200,0.724292,0.835560,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2...",3119,25300.0,25302.6,25292.0,...,25339.9,24950.0,,No,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
4,2018-03-01 09:35:00,25069.4,25500,0.912277,0.836814,"24000PE, 26000CE, 25000PE, 25500CE, 24500PE, 2...",3120,25300.0,25330.0,25300.0,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2018-03-28 15:05:00,24300.0,24400,0.868174,0.807301,"24500CE, 24000PE, 24200PE, 24400CE, 24600CE, 2...",4554,24360.0,24367.4,24319.0,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1430,2018-03-28 15:10:00,24300.0,24300,1.271178,0.807965,"24500CE, 24000PE, 24200PE, 24400CE, 24100PE, 2...",4555,24319.9,24328.6,24300.0,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1431,2018-03-28 15:15:00,24300.0,24300,1.259509,0.808480,"24500CE, 24200PE, 24000PE, 24400CE, 24300CE, 2...",4556,24320.3,24332.2,24315.1,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1432,2018-03-28 15:20:00,24300.0,24300,1.125140,0.808742,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2...",4557,24331.8,24355.8,24330.2,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1433,2018-03-28 15:25:00,24300.0,24400,0.947927,0.808835,"24500CE, 24000PE, 24200PE, 24400CE, 24300CE, 2...",4558,24352.0,24367.0,24346.4,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08

In [403]:
finals.columns.tolist()

['datetime',
 'atm',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'index',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'poc',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [404]:
column_order = [
    'datetime', 'atm', 'open', 'high', 'low', 'close', 'volume', 'oi',
    'max_pain_strike', 'intraday_pcr', 'cumulative_pcr', 'most_active_strikes',
    'vwap', 'awap', 'macd', 'local_max', 'local_min', 'vah', 'val', 'poc',
    'value_area_width(%)', 'highest_above_vah', 'lowest_below_val', 'gap_type',
    'gap_filled', '3_day_vah', '5_day_vah', '3_day_val', '5_day_val', '3_day_poc',
    '5_day_poc'
]

final_columns = [col for col in column_order if col in finals.columns]
final_s = finals[final_columns]
final_s

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-03-01 09:15:00,25069.4,25242.9,25262.1,25127.6,25262.1,4240.0,0.0,25500,0.592719,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
1,2018-03-01 09:20:00,25069.4,25262.0,25314.9,25257.2,25305.6,2720.0,0.0,25300,0.636941,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
2,2018-03-01 09:25:00,25069.4,25310.0,25339.9,25310.0,25310.0,2240.0,0.0,25400,0.651194,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
3,2018-03-01 09:30:00,25069.4,25300.0,25302.6,25292.0,25298.0,1040.0,0.0,25200,0.724292,...,25339.9,24950.0,,No,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
4,2018-03-01 09:35:00,25069.4,25300.0,25330.0,25300.0,25320.0,1040.0,0.0,25500,0.912277,...,25339.9,24950.0,,Yes,25483.383333,25549.33,25212.033333,25311.83,25244.300000,25345.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2018-03-28 15:05:00,24300.0,24360.0,24367.4,24319.0,24319.0,104720.0,0.0,24400,0.868174,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1430,2018-03-28 15:10:00,24300.0,24319.9,24328.6,24300.0,24323.8,169040.0,0.0,24300,1.271178,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1431,2018-03-28 15:15:00,24300.0,24320.3,24332.2,24315.1,24331.7,144480.0,0.0,24300,1.259509,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1432,2018-03-28 15:20:00,24300.0,24331.8,24355.8,24330.2,24350.0,135840.0,0.0,24300,1.125140,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08
1433,2018-03-28 15:25:00,24300.0,24352.0,24367.0,24346.4,24362.0,164560.0,0.0,24400,0.947927,...,24518.6,24300.0,Gap Down,Yes,24501.033333,24393.98,24265.083333,24173.16,24424.833333,24279.08

In [405]:
final_s.columns.tolist()

['datetime',
 'atm',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'poc',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [406]:
columns_to_round2 = ['vwap', 'awap', 'macd', 'val','3_day_vah' , '3_day_val', '5_day_vah','5_day_val','3_day_poc',	'5_day_poc'
]
columns_to_round4 = [
    'intraday_pcr', 'cumulative_pcr',
    'value_area_width(%)'
]
final_s[columns_to_round2] = final_s[columns_to_round2].round(2)
final_s[columns_to_round4] = final_s[columns_to_round4].round(4)
final_s

<ipython-input-406-dbbf3e14529a>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_s[columns_to_round2] = final_s[columns_to_round2].round(2)
<ipython-input-406-dbbf3e14529a>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_s[columns_to_round4] = final_s[columns_to_round4].round(4)

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-03-01 09:15:00,25069.4,25242.9,25262.1,25127.6,25262.1,4240.0,0.0,25500,0.5927,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
1,2018-03-01 09:20:00,25069.4,25262.0,25314.9,25257.2,25305.6,2720.0,0.0,25300,0.6369,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
2,2018-03-01 09:25:00,25069.4,25310.0,25339.9,25310.0,25310.0,2240.0,0.0,25400,0.6512,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
3,2018-03-01 09:30:00,25069.4,25300.0,25302.6,25292.0,25298.0,1040.0,0.0,25200,0.7243,...,25339.9,24950.0,,No,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
4,2018-03-01 09:35:00,25069.4,25300.0,25330.0,25300.0,25320.0,1040.0,0.0,25500,0.9123,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2018-03-28 15:05:00,24300.0,24360.0,24367.4,24319.0,24319.0,104720.0,0.0,24400,0.8682,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1430,2018-03-28 15:10:00,24300.0,24319.9,24328.6,24300.0,24323.8,169040.0,0.0,24300,1.2712,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1431,2018-03-28 15:15:00,24300.0,24320.3,24332.2,24315.1,24331.7,144480.0,0.0,24300,1.2595,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1432,2018-03-28 15:20:00,24300.0,24331.8,24355.8,24330.2,24350.0,135840.0,0.0,24300,1.1251,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1433,2018-03-28 15:25:00,24300.0,24352.0,24367.0,24346.4,24362.0,164560.0,0.0,24400,0.9479,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08

In [407]:
f=final_s
filled_dates = f.groupby(f['datetime'].dt.date)['gap_filled'].transform(lambda x: 'Yes' if 'Yes' in x.values else 'No')
f['gap_filled'] = filled_dates
f

<ipython-input-407-e55bbcfd0724>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f['gap_filled'] = filled_dates

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-03-01 09:15:00,25069.4,25242.9,25262.1,25127.6,25262.1,4240.0,0.0,25500,0.5927,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
1,2018-03-01 09:20:00,25069.4,25262.0,25314.9,25257.2,25305.6,2720.0,0.0,25300,0.6369,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
2,2018-03-01 09:25:00,25069.4,25310.0,25339.9,25310.0,25310.0,2240.0,0.0,25400,0.6512,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
3,2018-03-01 09:30:00,25069.4,25300.0,25302.6,25292.0,25298.0,1040.0,0.0,25200,0.7243,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
4,2018-03-01 09:35:00,25069.4,25300.0,25330.0,25300.0,25320.0,1040.0,0.0,25500,0.9123,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2018-03-28 15:05:00,24300.0,24360.0,24367.4,24319.0,24319.0,104720.0,0.0,24400,0.8682,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1430,2018-03-28 15:10:00,24300.0,24319.9,24328.6,24300.0,24323.8,169040.0,0.0,24300,1.2712,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1431,2018-03-28 15:15:00,24300.0,24320.3,24332.2,24315.1,24331.7,144480.0,0.0,24300,1.2595,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1432,2018-03-28 15:20:00,24300.0,24331.8,24355.8,24330.2,24350.0,135840.0,0.0,24300,1.1251,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1433,2018-03-28 15:25:00,24300.0,24352.0,24367.0,24346.4,24362.0,164560.0,0.0,24400,0.9479,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08

In [408]:
f.columns.tolist()

['datetime',
 'atm',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'poc',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [409]:
f = f.loc[:, ~f.columns.duplicated()]

# Print new columns
print("\nColumns after removing duplicates:")
print(f.columns.tolist())

Columns after removing duplicates:
['datetime', 'atm', 'open', 'high', 'low', 'close', 'volume', 'oi', 'max_pain_strike', 'intraday_pcr', 'cumulative_pcr', 'most_active_strikes', 'vwap', 'awap', 'macd', 'local_max', 'local_min', 'vah', 'val', 'poc', 'value_area_width(%)', 'highest_above_vah', 'lowest_below_val', 'gap_type', 'gap_filled', '3_day_vah', '5_day_vah', '3_day_val', '5_day_val', '3_day_poc', '5_day_poc']

In [410]:
f.columns.tolist()

['datetime',
 'atm',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [411]:
f

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-03-01 09:15:00,25069.4,25242.9,25262.1,25127.6,25262.1,4240.0,0.0,25500,0.5927,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
1,2018-03-01 09:20:00,25069.4,25262.0,25314.9,25257.2,25305.6,2720.0,0.0,25300,0.6369,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
2,2018-03-01 09:25:00,25069.4,25310.0,25339.9,25310.0,25310.0,2240.0,0.0,25400,0.6512,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
3,2018-03-01 09:30:00,25069.4,25300.0,25302.6,25292.0,25298.0,1040.0,0.0,25200,0.7243,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
4,2018-03-01 09:35:00,25069.4,25300.0,25330.0,25300.0,25320.0,1040.0,0.0,25500,0.9123,...,25339.9,24950.0,,Yes,25483.38,25549.33,25212.03,25311.83,25244.30,25345.14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1429,2018-03-28 15:05:00,24300.0,24360.0,24367.4,24319.0,24319.0,104720.0,0.0,24400,0.8682,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1430,2018-03-28 15:10:00,24300.0,24319.9,24328.6,24300.0,24323.8,169040.0,0.0,24300,1.2712,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1431,2018-03-28 15:15:00,24300.0,24320.3,24332.2,24315.1,24331.7,144480.0,0.0,24300,1.2595,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1432,2018-03-28 15:20:00,24300.0,24331.8,24355.8,24330.2,24350.0,135840.0,0.0,24300,1.1251,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08
1433,2018-03-28 15:25:00,24300.0,24352.0,24367.0,24346.4,24362.0,164560.0,0.0,24400,0.9479,...,24518.6,24300.0,Gap Down,Yes,24501.03,24393.98,24265.08,24173.16,24424.83,24279.08

In [412]:
file_path = '/content/gdrive/MyDrive/Solutions/April2018.csv'

# Save the DataFrame to CSV
f.to_csv(file_path, index=True)

In [413]:
#final_s.to_csv('opt_fut_combined.csv', index=True)

In [414]:
#final_s.to_csv('1.csv', index=True)

In [415]:
#f.to_csv('2.csv', index=True)