<a href="https://colab.research.google.com/github/naga-dheeraj-p/Assignments/blob/main/Quant_Final_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Options

In [2]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [3]:
import glob
import csv
import os
import time

start = time.time()

path = "/content/gdrive/MyDrive/bank_nifty data/csv"
all_files = glob.glob(os.path.join(path, "*.csv"))
cols = ['time', 'symbol', 'open', 'high', 'low', 'close', 'volume', 'oi', 'expiry', 'strike', 'instrument_type', 'Date']

output_file = 'dataset.csv'
with open(output_file, 'w', newline='') as out:
    writer = csv.writer(out)
    writer.writerow(cols)

for file in all_files:
    date = os.path.basename(file).split('.')[0]
    year = int(date[-6:])
    if year == 122018:
        with open(file, 'r') as f, open(output_file, 'a', newline='') as out:
            reader = csv.reader(f)
            writer = csv.writer(out)
            next(reader)  # Skip the header row
            for row in reader:
                row.append(date)
                writer.writerow(row)

end = time.time()
print("Execution time:", end - start)

Execution time: 28.534664630889893

In [4]:
import pandas as pd
data1=pd.read_csv("/content/dataset.csv")
print(data1.shape)
data1.tail()

(668835, 12)

,time,symbol,open,high,low,close,volume,oi,expiry,strike,instrument_type,Date
668830,14:55:00,BANKNIFTY31JAN1928900PE,1620.00,1620.00,1620.00,1620.00,20,1280,31-01-2019,28900,PE,28122018
668831,15:11:00,BANKNIFTY31JAN1928900PE,1620.00,1621.00,1620.00,1621.00,20,1280,31-01-2019,28900,PE,28122018
668832,10:07:00,BANKNIFTY31JAN1928900PE,1610.00,1610.00,1600.00,1600.00,240,1160,31-01-2019,28900,PE,28122018
668833,09:35:00,BANKNIFTY31JAN1928900PE,1592.15,1592.15,1592.15,1592.15,20,1140,31-01-2019,28900,PE,28122018
668834,10:06:00,BANKNIFTY31JAN1928900PE,1592.15,1610.00,1592.15,1610.00,20,1160,31-01-2019,28900,PE,28122018

In [5]:
import pandas as pd
def preprocess_date(date_string):
    date_str = str(date_string)
    if len(date_str) == 8:
        # If the date string is in the format 'DDMMYYYY', convert it to 'DD-MM-YYYY'
        return date_str[:2] + '-' + date_str[2:4] + '-' + date_str[4:]
    else:
        date_str = '0' + date_str
        return date_str[:2] + '-' + date_str[2:4] + '-' + date_str[4:]
data1['Preprocessed_Date'] = data1['Date'].apply(preprocess_date)

In [6]:
sorted_data = data1.sort_values(by=['Preprocessed_Date', 'instrument_type', 'strike', 'time']).reset_index(drop=True)
sorted_data.head(60)

,time,symbol,open,high,low,close,volume,oi,expiry,strike,instrument_type,Date,Preprocessed_Date
0,09:17:00,BANKNIFTY27DEC1823000CE,3950.00,3950.00,3950.00,3950.00,40,15460,27-12-2018,23000,CE,3122018,03-12-2018
1,09:22:00,BANKNIFTY27DEC1823000CE,3950.00,3950.00,3940.00,3940.00,40,15420,27-12-2018,23000,CE,3122018,03-12-2018
2,09:25:00,BANKNIFTY27DEC1823000CE,3940.00,3940.00,3930.00,3930.00,40,15380,27-12-2018,23000,CE,3122018,03-12-2018
3,09:30:00,BANKNIFTY27DEC1823000CE,3930.00,3930.00,3905.00,3905.00,40,15340,27-12-2018,23000,CE,3122018,03-12-2018
4,09:33:00,BANKNIFTY27DEC1823000CE,3900.00,3905.00,3900.00,3900.00,40,15300,27-12-2018,23000,CE,3122018,03-12-2018
5,11:29:00,BANKNIFTY27DEC1823000CE,3900.00,3931.40,3900.00,3931.40,40,15260,27-12-2018,23000,CE,3122018,03-12-2018
6,11:34:00,BANKNIFTY27DEC1823000CE,3931.40,3931.40,3902.80,3902.80,40,15260,27-12-2018,23000,CE,3122018,03-12-2018
7,11:53:00,BANKNIFTY06DEC1823000CE,3850.00,3850.00,3850.00,3850.00,20,240,06-12-2018,23000,CE,3122018,03-12-2018
8,11:54:00,BANKNIFTY27DEC1823000CE,3902.80,3902.80,3850.00,3850.00,20,15260,27-12-2018,23000,CE,3122018,03-12-2018
9,11:56:00,BANKNIFTY06DEC1823000CE,3850.00,3850.00,3850.00,3850.00,20,220,06-12-2018,23000,CE,3122018,03-12-2018
10,11:57:00,BANKNIFTY27DEC1823000CE,3870.00,3870.00,3870.00,3870.00,20,15280,27-12-2018,23000,CE,3122018,03-12-2018
11,12:17:00,BANKNIFTY27DEC1823000CE,3870.00,3870.00,3844.75,3844.75,20,15300,27-12-2018,23000,CE,3122018,03-12-2018
12,12:45:00,BANKNIFTY06DEC1823000CE,3850.00,3870.00,3850.00,3870.00,20,200,06-12-2018,23000,CE,3122018,03-12-2018
13,12:50:00,BANKNIFTY27DEC1823000CE,3844.75,3880.00,3844.75,3880.00,20,15300,27-12-2018,23000,CE,3122018,03-12-2018
14,12:56:00,BANKNIFTY27DEC1823000CE,3880.00,3880.00,3880.00,3880.00,20,15320,27-12-2018,23000,CE,3122018,03-12-2018
15,13:13:00,BANKNIFTY27DEC1823000CE,3880.00,3895.00,3880.00,3895.00,20,15340,27-12-2018,23000,CE,3122018,03-12-2018
16,14:31:00,BANKNIFTY27DEC1823000CE,3895.00,3900.00,3895.00,3900.00,20,15360,27-12-2018,23000,CE,3122018,03-12-2018
17,14:44:00,BANKNIFTY27DEC1823000CE,3900.00,3900.00,3895.00,3895.00,20,15380,27-12-2018,23000,CE,3122018,03-12-2018
18,14:45:00,BANKNIFTY06DEC1823000CE,3870.00,3875.00,3870.00,3875.00,20,180,06-12-2018,23000,CE,3122018,03-12-2018
19,15:26:00,BANKNIFTY27DEC1823000CE,3895.00,3925.00,3895.00,3925.00,40,15400,27-12-2018,23000,CE,3122018,03-12-2018
20,15:27:00,BANKNIFTY27DEC1823000CE,3925.00,3925.00,3925.00,3925.00,20,15400,27-12-2018,23000,CE,3122018,03-12-2018
21,09:27:00,BANKNIFTY27DEC1823500CE,3450.55,3533.60,3450.55,3533.60,100,13580,27-12-2018,23500,CE,3122018,03-12-2018
22,09:28:00,BANKNIFTY27DEC1823500CE,3456.45,3456.45,3456.45,3456.45,20,13480,27-12-2018,23500,CE,3122018,03-12-2018
23,10:21:00,BANKNIFTY27DEC1823500CE,3456.45,3456.45,3429.65,3429.65,20,13460,27-12-2018,23500,CE,3122018,03-12-2018
24,15:17:00,BANKNIFTY27DEC1823500CE,3429.65,3429.65,3414.90,3414.90,20,13460,27-12-2018,23500,CE,3122018,03-12-2018
25,15:20:00,BANKNIFTY27DEC1823500CE,3414.90,3417.65,3414.90,3417.65,40,13480,27-12-2018,23500,CE,3122018,03-12-2018
26,15:21:00,BANKNIFTY27DEC1823500CE,3417.65,3417.65,3409.70,3409.70,20,13480,27-12-2018,23500,CE,3122018,03-12-2018
27,09:19:00,BANKNIFTY27DEC1824000CE,2980.00,2980.00,2980.00,2980.00,140,19140,27-12-2018,24000,CE,3122018,03-12-2018
28,09:26:00,BANKNIFTY27DEC1824000CE,2980.00,2980.00,2920.25,2920.25,40,19140,27-12-2018,24000,CE,3122018,03-12-2018
29,09:30:00,BANKNIFTY27DEC1824000CE,2920.25,2925.00,2920.25,2925.00,140,19180,27-12-2018,24000,CE,3122018,03-12-2018
30,10:07:00,BANKNIFTY27DEC1824000CE,2925.00,2944.10,2925.00,2944.10,20,19180,27-12-2018,24000,CE,3122018,03-12-2018
31,10:30:00,BANKNIFTY27DEC1824000CE,2944.10,2970.00,2944.10,2970.00,20,19180,27-12-2018,24000,CE,3122018,03-12-2018
32,11:32:00,BANKNIFTY06DEC1824000CE,2862.20,2862.20,2862.20,2862.20,20,1020,06-12-2018,24000,CE,3122018,03-12-2018
33,11:53:00,BANKNIFTY27DEC1824000CE,2970.00,2970.00,2880.00,2880.00,20,19180,27-12-2018,24000,CE,3122018,03-12-2018
34,11:54:00,BANKNIFTY27DEC1824000CE,2880.00,2890.00,2880.00,2890.00,140,19180,27-12-2018,24000,CE,3122018,03-12-2018
35,12:41:00,BANKNIFTY27DEC1824000CE,2890.00,2933.00,2890.00,2933.00,20,19160,27-12-2018,24000,CE,3122018,03-12-2018
36,13:07:00,BANKNIFTY27DEC1824000CE,2933.00,2933.00,2900.00,2900.00,20,19160,27-12-2018,24000,CE,3122018,03-12-2018
37,14:59:00,BANKNIFTY27DEC1824000CE,2900.00,2940.00,2900.00,2940.00,140,19160,27-12-2018,24000,CE,3122018,03-12-2018
38,15:01:00,BANKNIFTY27DEC1824000CE,2940.00,2940.00,2924.15,2924.15,20,19160,27-12-2018,24000,CE,3122018,03-12-2018
39,15:06:00,BANKNIFTY27DEC1824000CE,2924.15,2924.15,2918.70,2918.70,20,19180,27-12-2018,24000,CE,3122018,03-12-2018
40,15:07:00,BANKNIFTY27DEC1824000CE,2918.70,2922.20,2918.70,2922.20,20,19200,27-12-2018,24000,CE,3122018,03-12-2018
41,15:14:00,BANKNIFTY06DEC1824000CE,2862.20,2862.30,2862.20,2862.30,20,1020,06-12-2018,24000,CE,3122018,03-12-2018
42,15:14:00,BANKNIFTY27DEC1824000CE,2922.20,2950.00,2922.20,2950.00,40,19220,27-12-2018,24000,CE,3122018,03-12-2018
43,15:15:00,BANKNIFTY06DEC1824000CE,2862.30,2867.65,2862.30,2867.65,20,1020,06-12-2018,24000,CE,3122018,03-12-2018
44,15:20:00,BANKNIFTY27DEC1824000CE,2950.00,2950.00,2925.00,2925.00,20,19220,27-12-2018,24000,CE,3122018,03-12-2018
45,15:21:00,BANKNIFTY27DEC1824000CE,2925.00,2925.30,2925.00,2925.30,20,19220,27-12-2018,24000,CE,3122018,03-12-2018
46,09:19:00,BANKNIFTY27DEC1824500CE,2500.00,2500.00,2500.00,2500.00,20,31260,27-12-2018,24500,CE,3122018,03-12-2018
47,09:22:00,BANKNIFTY06DEC1824500CE,2400.00,2400.00,2400.00,2400.00,20,420,06-12-2018,24500,CE,3122018,03-12-2018
48,09:24:00,BANKNIFTY06DEC1824500CE,2400.00,2400.00,2400.00,2400.00,20,420,06-12-2018,24500,CE,3122018,03-12-2018
49,11:31:00,BANKNIFTY27DEC1824500CE,2475.00,2480.00,2475.00,2475.00,240,31280,27-12-2018,24500,CE,3122018,03-12-2018
50,11:33:00,BANKNIFTY27DEC1824500CE,2460.00,2460.00,2460.00,2460.00,80,31280,27-12-2018,24500,CE,3122018,03-12-2018
51,11:34:00,BANKNIFTY27DEC1824500CE,2460.00,2460.00,2450.00,2450.00,80,30960,27-12-2018,24500,CE,3122018,03-12-2018
52,13:06:00,BANKNIFTY27DEC1824500CE,2450.00,2450.00,2421.00,2421.00,20,30880,27-12-2018,24500,CE,3122018,03-12-2018
53,14:59:00,BANKNIFTY27DEC1824500CE,2421.00,2483.60,2421.00,2483.60,40,30880,27-12-2018,24500,CE,3122018,03-12-2018
54,15:00:00,BANKNIFTY27DEC1824500CE,2483.60,2483.60,2482.95,2482.95,60,30880,27-12-2018,24500,CE,3122018,03-12-2018
55,12:08:00,BANKNIFTY06DEC1824900CE,1930.00,1930.00,1930.00,1930.00,20,0,06-12-2018,24900,CE,3122018,03-12-2018
56,09:16:00,BANKNIFTY27DEC1825000CE,2050.00,2050.00,2050.00,2050.00,100,31540,27-12-2018,25000,CE,3122018,03-12-2018
57,09:18:00,BANKNIFTY27DEC1825000CE,2050.00,2050.00,2020.35,2020.35,20,31540,27-12-2018,25000,CE,3122018,03-12-2018
58,09:20:00,BANKNIFTY06DEC1825000CE,1930.00,1930.00,1930.00,1930.00,20,10680,06-12-2018,25000,CE,3122018,03-12-2018
59,09:25:00,BANKNIFTY27DEC1825000CE,2020.35,2020.35,1991.35,1991.60,80,31500,27-12-2018,25000,CE,3122018,03-12-2018

In [7]:
import pandas as pd
import numpy as np

data = sorted_data.copy()  # Made a copy to avoid modifying original data
data['time'] = pd.to_datetime(data['time'])

time_range = pd.date_range(start='09:15:00', end='15:30:00', freq='5T')
expanded_data = pd.DataFrame()

grouped_data = data.groupby(['Preprocessed_Date', 'instrument_type'])


for (Preprocessed_Date, instrument_type), subset in grouped_data:
    # Group the subset by strike and resample each group to 5-minute intervals
    resampled_subset = subset.set_index('time').groupby('strike').resample('5T').agg({
        'open': 'first',
        'high': 'max',
        'low': 'min',
        'close': 'last',
        'volume': 'sum',
        'oi': 'last'
    }).reset_index(level='strike')

    # Forward filling
    resampled_subset[['high', 'low']] = resampled_subset[['high', 'low']].ffill()
    # Interpolating
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].replace(0, np.nan)
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].interpolate(method='linear')
    resampled_subset[['volume', 'oi']] = resampled_subset[['volume', 'oi']].fillna(0).round(2)
    resampled_subset[['open', 'close']] = resampled_subset[['open', 'close']].interpolate(method='linear').round(2)

    resampled_subset.reset_index(inplace=True)

    for col in ['symbol', 'expiry']:
        resampled_subset[col] = subset[col].iloc[0]

    resampled_subset['Preprocessed_Date'] = Preprocessed_Date
    resampled_subset['instrument_type'] = instrument_type
    expanded_data = pd.concat([expanded_data, resampled_subset], ignore_index=True)

expanded_data.sort_values(by=['Preprocessed_Date', 'instrument_type', 'strike', 'time'], inplace=True)
expanded_data.reset_index(drop=True, inplace=True)
expanded_data['time'] = pd.to_datetime(expanded_data['time']).dt.time

<ipython-input-7-54d6af9e359d>:5: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data['time'] = pd.to_datetime(data['time'])

In [8]:
expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE
...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE

In [9]:
import pandas as pd
import os
from datetime import datetime

directory_path = '/content/gdrive/MyDrive/Fut_data'
data_list = []

for filename in os.listdir(directory_path):
    if filename.endswith('.csv'):
        try:
            date_str = filename.split('.')[0]  # Assuming the filename is like 'DDMMYYYY.csv'
            date_obj = datetime.strptime(date_str, '%d%m%Y')
            formatted_date = date_obj.strftime('%d-%m-%Y')
        except ValueError:
            print(f'{filename}: Filename does not match expected date format')
            continue
        #if date_obj.year==2018:                                                                                   #change here!!!!!!!!!!!!!!!!!!!!!!!!
        if date_obj.year==2018 and date_obj.month==12:
            file_path = os.path.join(directory_path, filename)
            df = pd.read_csv(file_path)

            # Considering ATM value from the first row
            if 'open' in df.columns:
                atm_value = df['open'].iloc[0]
                # Appending the formatted date and the ATM value to the data list
                data_list.append((formatted_date, atm_value))
            else:
                print(f'{formatted_date}: "open" column not found')

data_list.sort(key=lambda x: datetime.strptime(x[0], '%d-%m-%Y'))
for formatted_date, atm_value in data_list:
    print(f'{formatted_date}: ATM = {atm_value}')

03-12-2018: ATM = 27055.5
04-12-2018: ATM = 26903.0
05-12-2018: ATM = 26670.0
06-12-2018: ATM = 26485.5
07-12-2018: ATM = 26380.0
10-12-2018: ATM = 26251.25
11-12-2018: ATM = 25800.0
12-12-2018: ATM = 26349.85
13-12-2018: ATM = 26867.65
14-12-2018: ATM = 26853.0
17-12-2018: ATM = 26988.8
18-12-2018: ATM = 26950.0
19-12-2018: ATM = 27301.0
20-12-2018: ATM = 27189.4
21-12-2018: ATM = 27300.0
24-12-2018: ATM = 26925.0
26-12-2018: ATM = 26700.0
27-12-2018: ATM = 27198.0
28-12-2018: ATM = 27275.0
31-12-2018: ATM = 27400.0

In [10]:
data_list.sort(key=lambda x: datetime.strptime(x[0], '%d-%m-%Y'))
atm_dict = dict(data_list)
# Function to map preprocessed date to ATM value
def get_atm(date):
    return atm_dict.get(date, None)

# Adding a new column 'ATM' using the mapping function
expanded_data['atm'] = expanded_data['Preprocessed_Date'].apply(get_atm)
expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0

In [11]:
df_opt = pd.DataFrame(expanded_data)

df_opt['time'] = df_opt['time'].astype(str)
df_opt['datetime'] = pd.to_datetime(df_opt['Preprocessed_Date'] + ' ' + df_opt['time'], format='%d-%m-%Y %H:%M:%S')
cols = ['datetime'] + [col for col in df_opt if col != 'datetime']
df_opt = df_opt[cols]

In [12]:
df_opt.head(60)

,datetime,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
0,2018-12-03 09:15:00,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
1,2018-12-03 09:20:00,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
2,2018-12-03 09:25:00,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
3,2018-12-03 09:30:00,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
4,2018-12-03 09:35:00,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
5,2018-12-03 09:40:00,09:40:00,23000,3927.39,3930.0,3900.00,3902.73,76.52,15296.52,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
6,2018-12-03 09:45:00,09:45:00,23000,3926.09,3930.0,3900.00,3904.10,74.78,15294.78,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
7,2018-12-03 09:50:00,09:50:00,23000,3924.78,3930.0,3900.00,3905.46,73.04,15293.04,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
8,2018-12-03 09:55:00,09:55:00,23000,3923.48,3930.0,3900.00,3906.83,71.30,15291.30,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
9,2018-12-03 10:00:00,10:00:00,23000,3922.17,3930.0,3900.00,3908.19,69.57,15289.57,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
10,2018-12-03 10:05:00,10:05:00,23000,3920.87,3930.0,3900.00,3909.56,67.83,15287.83,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
11,2018-12-03 10:10:00,10:10:00,23000,3919.57,3930.0,3900.00,3910.92,66.09,15286.09,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
12,2018-12-03 10:15:00,10:15:00,23000,3918.26,3930.0,3900.00,3912.29,64.35,15284.35,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
13,2018-12-03 10:20:00,10:20:00,23000,3916.96,3930.0,3900.00,3913.65,62.61,15282.61,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
14,2018-12-03 10:25:00,10:25:00,23000,3915.65,3930.0,3900.00,3915.02,60.87,15280.87,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
15,2018-12-03 10:30:00,10:30:00,23000,3914.35,3930.0,3900.00,3916.38,59.13,15279.13,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
16,2018-12-03 10:35:00,10:35:00,23000,3913.04,3930.0,3900.00,3917.75,57.39,15277.39,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
17,2018-12-03 10:40:00,10:40:00,23000,3911.74,3930.0,3900.00,3919.11,55.65,15275.65,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
18,2018-12-03 10:45:00,10:45:00,23000,3910.43,3930.0,3900.00,3920.48,53.91,15273.91,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
19,2018-12-03 10:50:00,10:50:00,23000,3909.13,3930.0,3900.00,3921.84,52.17,15272.17,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
20,2018-12-03 10:55:00,10:55:00,23000,3907.83,3930.0,3900.00,3923.21,50.43,15270.43,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
21,2018-12-03 11:00:00,11:00:00,23000,3906.52,3930.0,3900.00,3924.57,48.70,15268.70,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
22,2018-12-03 11:05:00,11:05:00,23000,3905.22,3930.0,3900.00,3925.94,46.96,15266.96,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
23,2018-12-03 11:10:00,11:10:00,23000,3903.91,3930.0,3900.00,3927.30,45.22,15265.22,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
24,2018-12-03 11:15:00,11:15:00,23000,3902.61,3930.0,3900.00,3928.67,43.48,15263.48,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
25,2018-12-03 11:20:00,11:20:00,23000,3901.30,3930.0,3900.00,3930.03,41.74,15261.74,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
26,2018-12-03 11:25:00,11:25:00,23000,3900.00,3931.4,3900.00,3931.40,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
27,2018-12-03 11:30:00,11:30:00,23000,3931.40,3931.4,3902.80,3902.80,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
28,2018-12-03 11:35:00,11:35:00,23000,3911.05,3931.4,3902.80,3889.60,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
29,2018-12-03 11:40:00,11:40:00,23000,3890.70,3931.4,3902.80,3876.40,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
30,2018-12-03 11:45:00,11:45:00,23000,3870.35,3931.4,3902.80,3863.20,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
31,2018-12-03 11:50:00,11:50:00,23000,3850.00,3902.8,3850.00,3850.00,40.00,15260.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
32,2018-12-03 11:55:00,11:55:00,23000,3850.00,3870.0,3850.00,3870.00,40.00,15280.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
33,2018-12-03 12:00:00,12:00:00,23000,3855.00,3870.0,3850.00,3863.69,35.00,15285.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
34,2018-12-03 12:05:00,12:05:00,23000,3860.00,3870.0,3850.00,3857.38,30.00,15290.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
35,2018-12-03 12:10:00,12:10:00,23000,3865.00,3870.0,3850.00,3851.06,25.00,15295.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
36,2018-12-03 12:15:00,12:15:00,23000,3870.00,3870.0,3844.75,3844.75,20.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
37,2018-12-03 12:20:00,12:20:00,23000,3866.67,3870.0,3844.75,3848.96,20.00,12783.33,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
38,2018-12-03 12:25:00,12:25:00,23000,3863.33,3870.0,3844.75,3853.17,20.00,10266.67,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
39,2018-12-03 12:30:00,12:30:00,23000,3860.00,3870.0,3844.75,3857.38,20.00,7750.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
40,2018-12-03 12:35:00,12:35:00,23000,3856.67,3870.0,3844.75,3861.58,20.00,5233.33,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
41,2018-12-03 12:40:00,12:40:00,23000,3853.33,3870.0,3844.75,3865.79,20.00,2716.67,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
42,2018-12-03 12:45:00,12:45:00,23000,3850.00,3870.0,3850.00,3870.00,20.00,200.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
43,2018-12-03 12:50:00,12:50:00,23000,3844.75,3880.0,3844.75,3880.00,20.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
44,2018-12-03 12:55:00,12:55:00,23000,3880.00,3880.0,3880.00,3880.00,20.00,15320.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
45,2018-12-03 13:00:00,13:00:00,23000,3880.00,3880.0,3880.00,3885.00,20.00,15326.67,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
46,2018-12-03 13:05:00,13:05:00,23000,3880.00,3880.0,3880.00,3890.00,20.00,15333.33,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
47,2018-12-03 13:10:00,13:10:00,23000,3880.00,3895.0,3880.00,3895.00,20.00,15340.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
48,2018-12-03 13:15:00,13:15:00,23000,3880.94,3895.0,3880.00,3895.31,20.00,15341.25,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
49,2018-12-03 13:20:00,13:20:00,23000,3881.88,3895.0,3880.00,3895.62,20.00,15342.50,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
50,2018-12-03 13:25:00,13:25:00,23000,3882.81,3895.0,3880.00,3895.94,20.00,15343.75,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
51,2018-12-03 13:30:00,13:30:00,23000,3883.75,3895.0,3880.00,3896.25,20.00,15345.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
52,2018-12-03 13:35:00,13:35:00,23000,3884.69,3895.0,3880.00,3896.56,20.00,15346.25,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
53,2018-12-03 13:40:00,13:40:00,23000,3885.62,3895.0,3880.00,3896.88,20.00,15347.50,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
54,2018-12-03 13:45:00,13:45:00,23000,3886.56,3895.0,3880.00,3897.19,20.00,15348.75,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
55,2018-12-03 13:50:00,13:50:00,23000,3887.50,3895.0,3880.00,3897.50,20.00,15350.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
56,2018-12-03 13:55:00,13:55:00,23000,3888.44,3895.0,3880.00,3897.81,20.00,15351.25,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
57,2018-12-03 14:00:00,14:00:00,23000,3889.38,3895.0,3880.00,3898.12,20.00,15352.50,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
58,2018-12-03 14:05:00,14:05:00,23000,3890.31,3895.0,3880.00,3898.44,20.00,15353.75,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5
59,2018-12-03 14:10:00,14:10:00,23000,3891.25,3895.0,3880.00,3898.75,20.00,15355.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5

In [13]:
df_new = pd.DataFrame(df_opt)


df_new['datetime'] = pd.to_datetime(df_new['datetime'])
df_new['Preprocessed_Date'] = pd.to_datetime(df_new['Preprocessed_Date'], format='%d-%m-%Y')

# Function to find the nearest strike to ATM for each day
def nearest_strike(group):
    nearest_strike_row = group.loc[(group['strike'] - group['atm']).abs().idxmin()]
    return nearest_strike_row['strike']

# Get the nearest strike for each Preprocessed_Date
nearest_strikes = df_new.groupby('Preprocessed_Date').apply(nearest_strike).reset_index()
nearest_strikes.columns = ['Preprocessed_Date', 'nearest_strike']


merged_df = pd.merge(df_new, nearest_strikes, on='Preprocessed_Date')
filtered_data = merged_df[merged_df['strike'] == merged_df['nearest_strike']]

filtered_data = filtered_data[(filtered_data['datetime'].dt.time >= pd.to_datetime('09:15:00').time()) &
                          (filtered_data['datetime'].dt.time <= pd.to_datetime('15:30:00').time())]

filtered_data = filtered_data.drop(columns='nearest_strike')
filtered_data

,datetime,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm
1483,2018-12-03 09:15:00,09:15:00,27100,150.00,445.15,130.00,307.15,209240.0,1220.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5
1484,2018-12-03 09:20:00,09:20:00,27100,135.60,446.85,127.15,128.65,124700.0,296760.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5
1485,2018-12-03 09:25:00,09:25:00,27100,128.80,442.00,119.75,438.90,127560.0,2840.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5
1486,2018-12-03 09:30:00,09:30:00,27100,125.85,438.90,117.40,127.00,113400.0,344740.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5
1487,2018-12-03 09:35:00,09:35:00,27100,127.05,452.60,120.00,435.00,101140.0,3080.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119499,2018-12-31 15:10:00,15:10:00,27400,267.25,482.05,262.00,262.00,12840.0,51540.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0
119500,2018-12-31 15:15:00,15:15:00,27400,262.10,482.05,255.95,259.25,10380.0,45800.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0
119501,2018-12-31 15:20:00,15:20:00,27400,259.85,480.70,258.80,261.90,18500.0,42820.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0
119502,2018-12-31 15:25:00,15:25:00,27400,261.90,484.05,257.90,260.60,15600.0,39020.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0
119503,2018-12-31 15:30:00,15:30:00,27400,260.05,260.05,260.05,260.05,20.0,39020.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0

In [14]:
expanded_data['time'] = expanded_data['time'].astype(str)
expanded_data['datetime'] = pd.to_datetime(expanded_data['Preprocessed_Date'] + ' ' + expanded_data['time'], format='%d-%m-%Y %H:%M:%S')

unique_combinations = expanded_data[['Preprocessed_Date', 'time']].drop_duplicates()

results = []

for _, row in unique_combinations.iterrows():
    target_date = row['Preprocessed_Date']
    target_time = row['time']

    # Filter the dataset for the current combination
    filtered_df = expanded_data[(expanded_data['Preprocessed_Date'] == target_date) & (expanded_data['time'] == target_time)]

    strikes = filtered_df['strike'].unique()

    min_total_loss = float('inf')
    max_pain_strike = None

    for strike in strikes:
        total_loss = 0

        for _, option in filtered_df.iterrows():
            if option['instrument_type'] == 'CE':
                if option['strike'] < strike:
                    loss = (strike - option['strike']) * option['oi']
                else:
                    loss = 0
            elif option['instrument_type'] == 'PE':
                if option['strike'] > strike:
                    loss = (option['strike'] - strike) * option['oi']
                else:
                    loss = 0

            total_loss += loss

        if total_loss < min_total_loss:
            min_total_loss = total_loss
            max_pain_strike = strike

    results.append({
        'Preprocessed_Date': target_date,
        'time': target_time,
        'Max_Pain_Strike': max_pain_strike
    })

results_df = pd.DataFrame(results)
expanded_data = pd.merge(expanded_data, results_df, on=['Preprocessed_Date', 'time'], how='left')
expanded_data.rename(columns={'Max_Pain_Strike': 'max_pain_strike'}, inplace=True)

expanded_data

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:15:00,26500
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:20:00,26500
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:25:00,26600
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:30:00,26800
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:35:00,26800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:25:00,27000
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:30:00,27000
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:35:00,27100
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:40:00,27000
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:45:00,27000

In [15]:
import pandas as pd

expanded_df = pd.DataFrame(expanded_data)

# Ensure 'Preprocessed_Date' and 'time' are strings
expanded_df['Preprocessed_Date'] = expanded_df['Preprocessed_Date'].astype(str)
expanded_df['time'] = expanded_df['time'].astype(str)

# Combine 'Preprocessed_Date' and 'time' into a single 'datetime' column with explicit format
expanded_df['datetime'] = pd.to_datetime(expanded_df['Preprocessed_Date'] + ' ' + expanded_df['time'], format='%d-%m-%Y %H:%M:%S')

# Group by both 'datetime' and 'strike', then aggregate 'oi'
grouped_df = expanded_df.groupby(['datetime', 'strike']).agg({'oi': 'sum'}).reset_index()

# Get the top 6 most active strikes for each 5-minute interval
top_strikes = grouped_df.groupby('datetime').apply(lambda x: x.nlargest(6, 'oi')).reset_index(drop=True)

# Combine the top strikes into a single string for each datetime
result_df = top_strikes.groupby('datetime')['strike'].apply(lambda x: ', '.join(x.astype(str))).reset_index()
merged_df = pd.merge(expanded_df, result_df, on='datetime', how='left')

# Rename the column to 'most_active_strikes'
merged_df.rename(columns={'strike_y': 'most_active_strikes'}, inplace=True)
if 'strike_x' in merged_df.columns:
    merged_df.drop(columns=['strike_x'], inplace=True)

merged_df

,time,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,most_active_strikes
0,09:15:00,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:15:00,26500,"26000, 25000, 26500, 25500, 26600, 27000"
1,09:20:00,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:20:00,26500,"26000, 25000, 26500, 25500, 27200, 26600"
2,09:25:00,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:25:00,26600,"25000, 26000, 26500, 25500, 26600, 26400"
3,09:30:00,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:30:00,26800,"26500, 26000, 25500, 26600, 26800, 26900"
4,09:35:00,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:35:00,26800,"25000, 26500, 26000, 27200, 25500, 26600"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:25:00,27000,"27500, 27000, 26500, 26000, 28000, 26400"
120053,12:30:00,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:30:00,27000,"27500, 27000, 26500, 26700, 27700, 26000"
120054,12:35:00,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:35:00,27100,"27500, 27000, 26500, 26800, 27200, 27700"
120055,12:40:00,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:40:00,27000,"27500, 27000, 26500, 26800, 28000, 26400"
120056,12:45:00,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:45:00,27000,"27200, 27000, 27300, 27400, 26500, 27500"

In [16]:
def calculate_intraday_pcr(df):
    # Ensure 'Preprocessed_Date' and 'time' are strings
    df['Preprocessed_Date'] = df['Preprocessed_Date'].astype(str)
    df['time'] = df['time'].astype(str)

    # Combine 'Preprocessed_Date' and 'time' to ensure 'datetime' is in datetime format
    df['datetime'] = pd.to_datetime(df['Preprocessed_Date'] + ' ' + df['time'], format='%d-%m-%Y %H:%M:%S')

    # Get the unique 5-minute intervals in the data
    time_intervals = df['datetime'].dt.floor('5T').unique()

    for time in time_intervals:
        # Filter data for the current 5-minute interval
        interval_df = df[df['datetime'].dt.floor('5T') == time]

        atm_strike = interval_df['atm'].iloc[0] if not interval_df['atm'].empty else None

        if atm_strike is not None:
            lower_bound = atm_strike - 1000
            upper_bound = atm_strike + 1000
            selected_strikes = interval_df[(interval_df['strike'] >= lower_bound) & (interval_df['strike'] <= upper_bound)]

            total_put_volume = selected_strikes[selected_strikes['instrument_type'] == 'PE']['volume'].sum()
            total_call_volume = selected_strikes[selected_strikes['instrument_type'] == 'CE']['volume'].sum()

            pcr = total_put_volume / total_call_volume if total_call_volume != 0 else None

            # Update the 'intraday_pcr' for the filtered interval data
            df.loc[df['datetime'].dt.floor('5T') == time, 'intraday_pcr'] = pcr

    return df

# Assuming expanded_data is your initial dataset
merged_df = pd.DataFrame(expanded_data)

# Calculate intraday PCR and update the DataFrame
merged_df = calculate_intraday_pcr(expanded_df)

merged_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:15:00,26500,0.683871
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:20:00,26500,0.849990
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:25:00,26600,0.962676
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:30:00,26800,0.811316
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:35:00,26800,0.693757
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:25:00,27000,1.338217
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:30:00,27000,1.173345
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:35:00,27100,1.125640
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:40:00,27000,1.364296
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:45:00,27000,1.028942

In [17]:
import pandas as pd

def calculate_cumulative_pcr(df):
    # Combine 'Preprocessed_Date' and 'time' to ensure 'time' is in datetime format
    df['datetime'] = pd.to_datetime(df['Preprocessed_Date'] + ' ' + df['time'], format='%d-%m-%Y %H:%M:%S')

    # Initialize cumulative put and call volumes
    cumulative_put_volume = 0
    cumulative_call_volume = 0

    # Get the unique 5-minute intervals in the data
    time_intervals = df['datetime'].dt.floor('5T').unique()

    for time in time_intervals:
        # Filter data for the current 5-minute interval
        interval_df = df[df['datetime'].dt.floor('5T') == time]

        atm_strike = interval_df['atm'].iloc[0] if not interval_df['atm'].empty else None

        if atm_strike is not None:
            lower_bound = atm_strike - 1000
            upper_bound = atm_strike + 1000
            selected_strikes = interval_df[(interval_df['strike'] >= lower_bound) & (interval_df['strike'] <= upper_bound)]

            interval_put_volume = selected_strikes[selected_strikes['instrument_type'] == 'PE']['volume'].sum()
            interval_call_volume = selected_strikes[selected_strikes['instrument_type'] == 'CE']['volume'].sum()

            # Update cumulative volumes
            cumulative_put_volume += interval_put_volume
            cumulative_call_volume += interval_call_volume

            # Calculate cumulative PCR
            cumulative_pcr = cumulative_put_volume / cumulative_call_volume if cumulative_call_volume != 0 else None

            # Update the 'Cumulative_pcr' for the filtered interval data
            df.loc[df['datetime'].dt.floor('5T') == time, 'cumulative_pcr'] = cumulative_pcr

    return df

# Assuming merged_df is your DataFrame after merging the most active strikes
final_merged_df = pd.DataFrame(merged_df)

# Calculate cumulative PCR and update the DataFrame
final_merged_df = calculate_cumulative_pcr(final_merged_df)
final_merged_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:15:00,26500,0.683871,0.683871
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:20:00,26500,0.849990,0.746159
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:25:00,26600,0.962676,0.802238
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:30:00,26800,0.811316,0.804080
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:35:00,26800,0.693757,0.788170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:25:00,27000,1.338217,0.861097
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:30:00,27000,1.173345,0.861155
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:35:00,27100,1.125640,0.861219
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:40:00,27000,1.364296,0.861328
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:45:00,27000,1.028942,0.861380

In [18]:
import pandas as pd

# Assuming expanded_data is your initial dataset
last_final_merged_df = pd.DataFrame(final_merged_df)

# Group by both 'datetime' and 'strike', then aggregate 'oi'
grouped_df = last_final_merged_df.groupby(['datetime', 'strike']).agg({'oi': 'sum'}).reset_index()

# Get the top 6 most active strikes for each 5-minute interval
top_strikes = last_final_merged_df.groupby('datetime').apply(lambda x: x.nlargest(6, 'oi')).reset_index(drop=True)

# Concatenate 'strike' with 'instrument_type'
top_strikes['strike_with_type'] = top_strikes['strike'].astype(str) + top_strikes['instrument_type']

# Combine the top strikes into a single string for each datetime
result_df = top_strikes.groupby('datetime')['strike_with_type'].apply(lambda x: ', '.join(x)).reset_index()

# Merge the result back into the last_final_merged_df
end_df = pd.merge(last_final_merged_df, result_df, on='datetime', how='left')

# Rename the column to 'most_active_strikes'
end_df.rename(columns={'strike_with_type': 'most_active_strikes'}, inplace=True)

# Optionally, drop the redundant columns if they exist
if 'strike_x' in end_df.columns:
    end_df.drop(columns=['strike_x'], inplace=True)

end_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
0,09:15:00,23000,3950.00,3950.0,3950.00,3950.00,40.00,15460.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:15:00,26500,0.683871,0.683871,"25000PE, 26000PE, 26000CE, 25500PE, 26600PE, 2..."
1,09:20:00,23000,3950.00,3950.0,3940.00,3940.00,40.00,15420.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:20:00,26500,0.849990,0.746159,"25000PE, 26000PE, 26000CE, 25500PE, 27200CE, 2..."
2,09:25:00,23000,3940.00,3940.0,3930.00,3930.00,40.00,15380.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:25:00,26600,0.962676,0.802238,"25000PE, 26000PE, 25500PE, 26600PE, 26400PE, 2..."
3,09:30:00,23000,3930.00,3930.0,3900.00,3900.00,80.00,15300.00,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:30:00,26800,0.811316,0.804080,"26000PE, 25500PE, 26600PE, 26400PE, 26500PE, 2..."
4,09:35:00,23000,3928.70,3930.0,3900.00,3901.37,78.26,15298.26,BANKNIFTY27DEC1823000CE,27-12-2018,03-12-2018,CE,27055.5,2018-12-03 09:35:00,26800,0.693757,0.788170,"25000PE, 26000PE, 27200CE, 25500PE, 26600PE, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120052,12:25:00,28900,1652.35,1700.2,1652.35,1700.20,20.00,400.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:25:00,27000,1.338217,0.861097,"27500PE, 27500CE, 27000PE, 27000CE, 26500PE, 2..."
120053,12:30:00,28900,1636.76,1700.2,1652.35,1672.65,25.00,620.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:30:00,27000,1.173345,0.861155,"27500PE, 27500CE, 27000PE, 27000CE, 26700PE, 2..."
120054,12:35:00,28900,1621.18,1700.2,1652.35,1645.10,30.00,840.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:35:00,27100,1.125640,0.861219,"27500PE, 27500CE, 27200PE, 26800PE, 27000PE, 2..."
120055,12:40:00,28900,1605.59,1700.2,1652.35,1617.55,35.00,1060.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:40:00,27000,1.364296,0.861328,"27500PE, 27500CE, 26800PE, 27000PE, 27000CE, 2..."
120056,12:45:00,28900,1590.00,1590.0,1590.00,1590.00,40.00,1280.00,BANKNIFTY31JAN1922800PE,31-01-2019,31-12-2018,PE,27400.0,2018-12-31 12:45:00,27000,1.028942,0.861380,"27300CE, 27400CE, 27500CE, 27200PE, 26900PE, 2..."

In [19]:
df1 = pd.DataFrame(end_df)


df1['datetime'] = pd.to_datetime(df1['datetime'])
df1['Preprocessed_Date'] = pd.to_datetime(df1['Preprocessed_Date'], format='%d-%m-%Y')

# Function to find the nearest strike to ATM for each day
def nearest_strike(group):
    nearest_strike_row = group.loc[(group['strike'] - group['atm']).abs().idxmin()]
    return nearest_strike_row['strike']

# Get the nearest strike for each Preprocessed_Date
nearest_strikes = df1.groupby('Preprocessed_Date').apply(nearest_strike).reset_index()
nearest_strikes.columns = ['Preprocessed_Date', 'nearest_strike']


merged_df = pd.merge(df1, nearest_strikes, on='Preprocessed_Date')
filtered_df = merged_df[merged_df['strike'] == merged_df['nearest_strike']]

filtered_df = filtered_df[(filtered_df['datetime'].dt.time >= pd.to_datetime('09:15:00').time()) &
                          (filtered_df['datetime'].dt.time <= pd.to_datetime('15:30:00').time())]
filtered_df = filtered_df.drop(columns='nearest_strike')
filtered_df

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
1483,09:15:00,27100,150.00,445.15,130.00,307.15,209240.0,1220.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:15:00,26500,0.683871,0.683871,"25000PE, 26000PE, 26000CE, 25500PE, 26600PE, 2..."
1484,09:20:00,27100,135.60,446.85,127.15,128.65,124700.0,296760.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:20:00,26500,0.849990,0.746159,"25000PE, 26000PE, 26000CE, 25500PE, 27200CE, 2..."
1485,09:25:00,27100,128.80,442.00,119.75,438.90,127560.0,2840.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:25:00,26600,0.962676,0.802238,"25000PE, 26000PE, 25500PE, 26600PE, 26400PE, 2..."
1486,09:30:00,27100,125.85,438.90,117.40,127.00,113400.0,344740.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:30:00,26800,0.811316,0.804080,"26000PE, 25500PE, 26600PE, 26400PE, 26500PE, 2..."
1487,09:35:00,27100,127.05,452.60,120.00,435.00,101140.0,3080.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:35:00,26800,0.693757,0.788170,"25000PE, 26000PE, 27200CE, 25500PE, 26600PE, 2..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119499,15:10:00,27400,267.25,482.05,262.00,262.00,12840.0,51540.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0,2018-12-31 15:10:00,27000,0.956274,0.859714,"27500PE, 26900PE, 27000CE, 27000PE, 26800PE, 2..."
119500,15:15:00,27400,262.10,482.05,255.95,259.25,10380.0,45800.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0,2018-12-31 15:15:00,27000,0.858456,0.859713,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
119501,15:20:00,27400,259.85,480.70,258.80,261.90,18500.0,42820.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0,2018-12-31 15:20:00,27000,0.711615,0.859632,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
119502,15:25:00,27400,261.90,484.05,257.90,260.60,15600.0,39020.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0,2018-12-31 15:25:00,27000,0.658744,0.861610,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
119503,15:30:00,27400,260.05,260.05,260.05,260.05,20.0,39020.0,BANKNIFTY31JAN1922800PE,31-01-2019,2018-12-31,PE,27400.0,2018-12-31 15:30:00,27200,0.720339,0.861610,"27500CE, 27400CE, 27300CE, 27000PE, 26900PE, 2..."

In [20]:
options_df = filtered_df[filtered_df['instrument_type'].str.contains('ce', case=False, na=False)]
#options_df.drop(columns=['symbol',	'time','open','	high'	,'low',	'close','volume',	'oi'	], inplace=True)
options_df.head()

,time,strike,open,high,low,close,volume,oi,symbol,expiry,Preprocessed_Date,instrument_type,atm,datetime,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
1483,09:15:00,27100,150.00,445.15,130.00,307.15,209240.0,1220.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:15:00,26500,0.683871,0.683871,"25000PE, 26000PE, 26000CE, 25500PE, 26600PE, 2..."
1484,09:20:00,27100,135.60,446.85,127.15,128.65,124700.0,296760.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:20:00,26500,0.849990,0.746159,"25000PE, 26000PE, 26000CE, 25500PE, 27200CE, 2..."
1485,09:25:00,27100,128.80,442.00,119.75,438.90,127560.0,2840.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:25:00,26600,0.962676,0.802238,"25000PE, 26000PE, 25500PE, 26600PE, 26400PE, 2..."
1486,09:30:00,27100,125.85,438.90,117.40,127.00,113400.0,344740.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:30:00,26800,0.811316,0.804080,"26000PE, 25500PE, 26600PE, 26400PE, 26500PE, 2..."
1487,09:35:00,27100,127.05,452.60,120.00,435.00,101140.0,3080.0,BANKNIFTY27DEC1823000CE,27-12-2018,2018-12-03,CE,27055.5,2018-12-03 09:35:00,26800,0.693757,0.788170,"25000PE, 26000PE, 27200CE, 25500PE, 26600PE, 2..."

In [21]:
#final_opt_df=options_df['datetime','instrument_type','atm','max_pain_strike','intraday_pcr'	,'cumulative_pcr','most_active_strikes']
options_df.columns = options_df.columns.str.strip()

# Select the columns to create final_opt_df
columns_to_select = ['datetime', 'atm', 'max_pain_strike', 'intraday_pcr', 'cumulative_pcr', 'most_active_strikes']
final_opt_df = options_df[columns_to_select]
final_opt_df

,datetime,atm,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes
1483,2018-12-03 09:15:00,27055.5,26500,0.683871,0.683871,"25000PE, 26000PE, 26000CE, 25500PE, 26600PE, 2..."
1484,2018-12-03 09:20:00,27055.5,26500,0.849990,0.746159,"25000PE, 26000PE, 26000CE, 25500PE, 27200CE, 2..."
1485,2018-12-03 09:25:00,27055.5,26600,0.962676,0.802238,"25000PE, 26000PE, 25500PE, 26600PE, 26400PE, 2..."
1486,2018-12-03 09:30:00,27055.5,26800,0.811316,0.804080,"26000PE, 25500PE, 26600PE, 26400PE, 26500PE, 2..."
1487,2018-12-03 09:35:00,27055.5,26800,0.693757,0.788170,"25000PE, 26000PE, 27200CE, 25500PE, 26600PE, 2..."
...,...,...,...,...,...,...
115628,2018-12-31 15:10:00,27400.0,27000,0.956274,0.859714,"27500PE, 26900PE, 27000CE, 27000PE, 26800PE, 2..."
115629,2018-12-31 15:15:00,27400.0,27000,0.858456,0.859713,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
115630,2018-12-31 15:20:00,27400.0,27000,0.711615,0.859632,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
115631,2018-12-31 15:25:00,27400.0,27000,0.658744,0.861610,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2..."
115632,2018-12-31 15:30:00,27400.0,27200,0.720339,0.861610,"27500CE, 27400CE, 27300CE, 27000PE, 26900PE, 2..."

# Futures

In [22]:
import pandas as pd
fut_data = pd.read_csv("/content/gdrive/MyDrive/final_BANKNIFTY_F2.csv")
fut_data['Date'] = pd.to_datetime(fut_data['Date'], format='%Y%m%d').dt.strftime('%d-%m-%Y') # Converted to reqd format
fut_data.sort_values(by='Date', inplace=True)
fut_data['Time'] = pd.to_datetime(fut_data['Time'], format='%H:%M').dt.time
start_time = pd.to_datetime('09:15:00', format='%H:%M:%S').time()
end_time = pd.to_datetime('15:30:00', format='%H:%M:%S').time()
filtered_fut = fut_data[(fut_data['Time'] >= start_time) & (fut_data['Time'] <= end_time)] #Filtered out the data that doesnt occur in the time range
filtered_fut

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest
813167,BANKNIFTY_F2,01-01-2018,15:20:00,25515.20,25515.20,25515.20,25515.20,80.0,NaN
809216,BANKNIFTY_F2,01-01-2018,12:38:00,25637.50,25637.50,25637.50,25637.50,40.0,NaN
809217,BANKNIFTY_F2,01-01-2018,12:39:00,25640.00,25640.00,25640.00,25640.00,40.0,NaN
809218,BANKNIFTY_F2,01-01-2018,13:20:00,25635.80,25635.80,25625.10,25625.10,120.0,NaN
809219,BANKNIFTY_F2,01-01-2018,13:24:00,25626.10,25626.10,25625.10,25625.10,120.0,NaN
...,...,...,...,...,...,...,...,...,...
562680,BANKNIFTY_F2,31-12-2021,10:42:00,35766.75,35769.00,35766.75,35769.00,325.0,109775.0
562681,BANKNIFTY_F2,31-12-2021,10:44:00,35775.00,35775.00,35765.00,35765.00,75.0,109775.0
562682,BANKNIFTY_F2,31-12-2021,10:45:00,35760.00,35772.55,35760.00,35772.55,75.0,109775.0
562683,BANKNIFTY_F2,31-12-2021,10:48:00,35766.80,35766.80,35766.80,35766.80,100.0,109750.0
562685,BANKNIFTY_F2,31-12-2021,10:50:00,35792.75,35795.00,35792.75,35795.00,75.0,109750.0

In [23]:
import pandas as pd
df = pd.DataFrame(filtered_fut)
df['Open Interest'] = df['Open Interest'].fillna(0) #Replaced Nan by 0
df['DateTime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'].astype(str), format='%d-%m-%Y %H:%M:%S', errors='coerce') #Concatenated Date and Time to set a unique index
df = df.set_index('DateTime')
df = df.dropna(subset=['Date', 'Time'])
all_days = df.index.normalize().unique()
full_range = pd.concat([pd.DataFrame(index=pd.date_range(start=f"{day} 09:16", end=f"{day} 15:30", freq='1T')) for day in all_days])
full_range = full_range.merge(df, how='left', left_index=True, right_index=True)
full_range.fillna(method='ffill', inplace=True)
full_range.reset_index(inplace=True)
full_range.rename(columns={'index': 'DateTime'}, inplace=True)
full_range['Date'] = full_range['DateTime'].dt.strftime('%d-%m-%Y')
full_range['Time'] = full_range['DateTime'].dt.strftime('%H:%M:%S')
full_range = full_range[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest']]
full_range['DateTime'] = pd.to_datetime(full_range['Date'] + ' ' + full_range['Time'], format='%d-%m-%Y %H:%M:%S')
full_range.set_index('DateTime', inplace=True)

aggregation = {
    'Symbol': 'first',
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum',
    'Open Interest': 'last'
}

resampled_df = full_range.resample('5T').apply(aggregation)

# Reset index to split DateTime into Date and Time
resampled_df.reset_index(inplace=True)
resampled_df['Date'] = resampled_df['DateTime'].dt.strftime('%d-%m-%Y')
resampled_df['Time'] = resampled_df['DateTime'].dt.strftime('%H:%M:%S')

resampled_df.drop(columns=['DateTime'], inplace=True)
resampled_df = resampled_df[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest']]

resampled_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest
0,BANKNIFTY_F2,01-01-2018,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0
1,BANKNIFTY_F2,01-01-2018,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0
2,BANKNIFTY_F2,01-01-2018,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0
3,BANKNIFTY_F2,01-01-2018,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0
4,BANKNIFTY_F2,01-01-2018,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0
...,...,...,...,...,...,...,...,...,...
542663,BANKNIFTY_F2,28-02-2023,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0
542664,BANKNIFTY_F2,28-02-2023,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0
542665,BANKNIFTY_F2,28-02-2023,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0
542666,BANKNIFTY_F2,28-02-2023,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0
542667,BANKNIFTY_F2,28-02-2023,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0

In [24]:
df = pd.DataFrame(resampled_df)

df['DateTime'] = pd.to_datetime(df['Date'].str.strip() + ' ' + df['Time'].str.strip(), format='%d-%m-%Y %H:%M:%S', errors='coerce')
df = df.dropna(subset=['DateTime'])  # Remove rows where DateTime could not be parsed
df.set_index('DateTime', inplace=True)
# Calculate typical price for VWAP
df.loc[:, 'Price'] = (df['High'] + df['Low'] + df['Close']) / 3

# Calculate cumulative values for VWAP
cumulative_price_volume = (df['Price'] * df['Volume']).cumsum()
cumulative_volume = df['Volume'].cumsum()

df.loc[:, 'VWAP'] = cumulative_price_volume / cumulative_volume #Calculating for 1 min

# Aggregate the data into 5-minute intervals
resampled = df.resample('5T').agg({
    'Symbol': 'first',
    'Open': 'first',
    'High': 'max',
    'Low': 'min',
    'Close': 'last',
    'Volume': 'sum',
    'Open Interest': 'last',
    'Price': 'last'
})
# Calculate cumulative values for the resampled data
resampled['Price'] = (resampled['High'] + resampled['Low'] + resampled['Close']) / 3
resampled_cumulative_price_volume = (resampled['Price'] * resampled['Volume']).cumsum()
resampled_cumulative_volume = resampled['Volume'].cumsum()

# Calculating VWAP for the 5-minute intervals
resampled['VWAP'] = resampled_cumulative_price_volume / resampled_cumulative_volume

resampled.reset_index(inplace=True)
resampled['Date'] = resampled['DateTime'].dt.strftime('%d-%m-%Y')
resampled['Time'] = resampled['DateTime'].dt.strftime('%H:%M')

resampled.drop(columns=['DateTime', 'Price'], inplace=True) # Dropped DateTime column and unnecessary columns
resampled = resampled[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest', 'VWAP']]

resampled.dropna(inplace=True)
resampled.head(60)

<ipython-input-24-188d1babc51c>:41: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  resampled.dropna(inplace=True)

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP
0,BANKNIFTY_F2,01-01-2018,09:15,25634.0,25643.1,25608.0,25643.1,480.0,0.0,25631.400000
1,BANKNIFTY_F2,01-01-2018,09:20,25631.5,25675.7,25631.5,25665.3,600.0,0.0,25645.900000
2,BANKNIFTY_F2,01-01-2018,09:25,25665.3,25665.3,25655.1,25655.1,240.0,0.0,25648.190909
3,BANKNIFTY_F2,01-01-2018,09:30,25647.7,25647.7,25647.7,25647.7,240.0,0.0,25648.115385
4,BANKNIFTY_F2,01-01-2018,09:35,25647.7,25647.7,25647.0,25647.0,440.0,0.0,25647.921333
5,BANKNIFTY_F2,01-01-2018,09:40,25655.1,25661.9,25655.0,25655.0,320.0,0.0,25649.214943
6,BANKNIFTY_F2,01-01-2018,09:45,25653.0,25653.0,25645.0,25650.0,440.0,0.0,25649.233816
7,BANKNIFTY_F2,01-01-2018,09:50,25645.0,25650.0,25645.0,25650.0,400.0,0.0,25649.119831
8,BANKNIFTY_F2,01-01-2018,09:55,25645.0,25650.0,25645.0,25650.0,400.0,0.0,25649.031461
9,BANKNIFTY_F2,01-01-2018,10:00,25642.0,25642.0,25642.0,25642.0,1680.0,0.0,25646.777099
10,BANKNIFTY_F2,01-01-2018,10:05,25642.0,25655.0,25642.0,25653.7,1200.0,0.0,25647.421118
11,BANKNIFTY_F2,01-01-2018,10:10,25660.0,25660.0,25660.0,25660.0,280.0,0.0,25647.945238
12,BANKNIFTY_F2,01-01-2018,10:15,25660.0,25660.0,25660.0,25660.0,200.0,0.0,25648.293642
13,BANKNIFTY_F2,01-01-2018,10:20,25660.0,25660.0,25659.9,25659.9,640.0,0.0,25649.279012
14,BANKNIFTY_F2,01-01-2018,10:25,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25650.733942
15,BANKNIFTY_F2,01-01-2018,10:30,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25651.838286
16,BANKNIFTY_F2,01-01-2018,10:35,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25652.705137
17,BANKNIFTY_F2,01-01-2018,10:40,25659.9,25659.9,25659.9,25659.9,1200.0,0.0,25653.403668
18,BANKNIFTY_F2,01-01-2018,10:45,25659.9,25659.9,25648.9,25649.0,680.0,0.0,25653.361759
19,BANKNIFTY_F2,01-01-2018,10:50,25649.0,25649.0,25649.0,25649.0,200.0,0.0,25653.295871
20,BANKNIFTY_F2,01-01-2018,10:55,25649.0,25649.0,25649.0,25649.0,200.0,0.0,25653.231944
21,BANKNIFTY_F2,01-01-2018,11:00,25649.0,25655.0,25649.0,25655.0,240.0,0.0,25653.227875
22,BANKNIFTY_F2,01-01-2018,11:05,25655.0,25655.0,25655.0,25655.0,200.0,0.0,25653.253410
23,BANKNIFTY_F2,01-01-2018,11:10,25655.0,25655.0,25655.0,25655.0,200.0,0.0,25653.278220
24,BANKNIFTY_F2,01-01-2018,11:15,25655.0,25655.0,25647.1,25655.0,520.0,0.0,25653.245753
25,BANKNIFTY_F2,01-01-2018,11:20,25655.0,25658.0,25652.1,25653.1,680.0,0.0,25653.297120
26,BANKNIFTY_F2,01-01-2018,11:25,25658.0,25658.0,25650.3,25650.3,520.0,0.0,25653.282954
27,BANKNIFTY_F2,01-01-2018,11:30,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.256214
28,BANKNIFTY_F2,01-01-2018,11:35,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.230763
29,BANKNIFTY_F2,01-01-2018,11:40,25656.0,25656.0,25650.3,25650.3,400.0,0.0,25653.206510
30,BANKNIFTY_F2,01-01-2018,11:45,25656.0,25656.0,25650.0,25650.0,480.0,0.0,25653.173379
31,BANKNIFTY_F2,01-01-2018,11:50,25650.0,25650.0,25650.0,25650.0,240.0,0.0,25653.130399
32,BANKNIFTY_F2,01-01-2018,11:55,25650.0,25650.0,25650.0,25650.0,200.0,0.0,25653.095461
33,BANKNIFTY_F2,01-01-2018,12:00,25650.0,25650.0,25645.0,25645.0,240.0,0.0,25653.010499
34,BANKNIFTY_F2,01-01-2018,12:05,25645.0,25645.0,25645.0,25645.0,200.0,0.0,25652.923239
35,BANKNIFTY_F2,01-01-2018,12:10,25645.0,25645.0,25637.9,25642.0,600.0,0.0,25652.565963
36,BANKNIFTY_F2,01-01-2018,12:15,25642.0,25642.0,25639.3,25639.3,320.0,0.0,25652.360719
37,BANKNIFTY_F2,01-01-2018,12:20,25639.3,25639.3,25635.1,25635.1,480.0,0.0,25651.975439
38,BANKNIFTY_F2,01-01-2018,12:25,25635.1,25635.2,25635.1,25635.2,560.0,0.0,25651.512205
39,BANKNIFTY_F2,01-01-2018,12:30,25635.2,25635.2,25635.2,25635.2,600.0,0.0,25651.044359
40,BANKNIFTY_F2,01-01-2018,12:35,25638.0,25640.0,25637.5,25640.0,320.0,0.0,25650.865411
41,BANKNIFTY_F2,01-01-2018,12:40,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.764055
42,BANKNIFTY_F2,01-01-2018,12:45,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.664572
43,BANKNIFTY_F2,01-01-2018,12:50,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.566911
44,BANKNIFTY_F2,01-01-2018,12:55,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.471022
45,BANKNIFTY_F2,01-01-2018,13:00,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.376859
46,BANKNIFTY_F2,01-01-2018,13:05,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.284373
47,BANKNIFTY_F2,01-01-2018,13:10,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.193522
48,BANKNIFTY_F2,01-01-2018,13:15,25640.0,25640.0,25640.0,25640.0,200.0,0.0,25650.104262
49,BANKNIFTY_F2,01-01-2018,13:20,25635.8,25635.8,25625.1,25625.1,840.0,0.0,25649.343806
50,BANKNIFTY_F2,01-01-2018,13:25,25616.0,25630.0,25616.0,25630.0,320.0,0.0,25649.023667
51,BANKNIFTY_F2,01-01-2018,13:30,25637.3,25637.3,25637.3,25637.3,240.0,0.0,25648.907591
52,BANKNIFTY_F2,01-01-2018,13:35,25637.3,25637.3,25637.3,25637.3,200.0,0.0,25648.812602
53,BANKNIFTY_F2,01-01-2018,13:40,25637.3,25637.3,25625.0,25625.0,240.0,0.0,25648.620908
54,BANKNIFTY_F2,01-01-2018,13:45,25625.0,25625.0,25625.0,25625.0,200.0,0.0,25648.431029
55,BANKNIFTY_F2,01-01-2018,13:50,25625.0,25634.1,25625.0,25634.1,400.0,0.0,25648.156276
56,BANKNIFTY_F2,01-01-2018,13:55,25634.1,25634.1,25634.1,25634.1,400.0,0.0,25647.937331
57,BANKNIFTY_F2,01-01-2018,14:00,25634.1,25634.1,25634.1,25634.1,400.0,0.0,25647.725102
58,BANKNIFTY_F2,01-01-2018,14:05,25637.1,25637.1,25635.0,25635.0,280.0,0.0,25647.597370
59,BANKNIFTY_F2,01-01-2018,14:10,25635.0,25637.3,25635.0,25636.3,600.0,0.0,25647.343719

In [25]:
resampled_df_copy = resampled

# Converted 'Date' and 'Time' columns to strings so that we can concatenate
resampled_df_copy['Date'] = resampled_df_copy['Date'].astype(str)
resampled_df_copy['Time'] = resampled_df_copy['Time'].astype(str)
resampled_df_copy['DateTime'] = pd.to_datetime(resampled_df_copy['Date'] + ' ' + resampled_df_copy['Time'], format='%d-%m-%Y %H:%M')

resampled_df_copy = resampled_df_copy.dropna(subset=['DateTime'])
resampled_df_copy.set_index('DateTime', inplace=True) #Setting DateTime column as index

resampled_df_copy['EMA_12'] = resampled_df_copy['Close'].ewm(span=12, adjust=False).mean() #12-period EMA
resampled_df_copy['EMA_26'] = resampled_df_copy['Close'].ewm(span=26, adjust=False).mean() #26-period EMA

resampled_df_copy['MACD'] = resampled_df_copy['EMA_12'] - resampled_df_copy['EMA_26'] # MACD= 12_EMA - 26_EMA

resampled_df_copy.drop(['Date'	,'Time','EMA_12', 'EMA_26'], axis=1, inplace=True)

resampled_df_copy['Date'] = resampled_df_copy.index.strftime('%d-%m-%Y')
resampled_df_copy['Time'] = resampled_df_copy.index.strftime('%H:%M:%S')
resampled_df_copy = resampled_df_copy[['Symbol', 'Date', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume', 'Open Interest','VWAP' ,'MACD']]
resampled_df_copy

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD
DateTime,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,01-01-2018,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,0.000000
2018-01-01 09:20:00,BANKNIFTY_F2,01-01-2018,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,1.770940
2018-01-01 09:25:00,BANKNIFTY_F2,01-01-2018,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,2.324572
2018-01-01 09:30:00,BANKNIFTY_F2,01-01-2018,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,2.141525
2018-01-01 09:35:00,BANKNIFTY_F2,01-01-2018,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,1.917867
...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 15:10:00,BANKNIFTY_F2,28-02-2023,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,-3.280036
2023-02-28 15:15:00,BANKNIFTY_F2,28-02-2023,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,-1.197626
2023-02-28 15:20:00,BANKNIFTY_F2,28-02-2023,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,1.723892
2023-02-28 15:25:00,BANKNIFTY_F2,28-02-2023,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,4.228513
2023-02-28 15:30:00,BANKNIFTY_F2,28-02-2023,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,6.461724

In [26]:
data = resampled_df_copy.copy()
data['DateTime'] = pd.to_datetime(data['Date'] + ' ' + data['Time'], format='%d-%m-%Y %H:%M:%S')
data.reset_index(drop=True, inplace=True)
df = pd.DataFrame(data)

# Convert DateTime to datetime object
df['DateTime'] = pd.to_datetime(df['DateTime'])

# Extracting the Date Part from 'DateTime'
df['Date'] = df['DateTime'].dt.date

# Calculate POC
aggregated = df.groupby(['Date', 'Close']).agg({'Volume': 'sum'}).reset_index()
poc = aggregated.loc[aggregated.groupby('Date')['Volume'].idxmax()]
poc.rename(columns={'Close': 'Point of Control'}, inplace=True)

# Calculate Local Maximum and Minimum
daily_high_low = df.groupby('Date').agg({'High': 'max', 'Low': 'min'}).reset_index()
daily_high_low.rename(columns={'High': 'Local Maximum', 'Low': 'Local Minimum'}, inplace=True)

# Merge POC and daily high/low back into the original dataframe
df = df.merge(poc[['Date', 'Point of Control']], on='Date', how='left')
df = df.merge(daily_high_low, on='Date', how='left')
df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,DateTime,Point of Control,Local Maximum,Local Minimum
0,BANKNIFTY_F2,2018-01-01,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,0.000000,2018-01-01 09:15:00,25659.9,25675.7,25481.3
1,BANKNIFTY_F2,2018-01-01,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,1.770940,2018-01-01 09:20:00,25659.9,25675.7,25481.3
2,BANKNIFTY_F2,2018-01-01,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,2.324572,2018-01-01 09:25:00,25659.9,25675.7,25481.3
3,BANKNIFTY_F2,2018-01-01,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,2.141525,2018-01-01 09:30:00,25659.9,25675.7,25481.3
4,BANKNIFTY_F2,2018-01-01,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,1.917867,2018-01-01 09:35:00,25659.9,25675.7,25481.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96895,BANKNIFTY_F2,2023-02-28,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,-3.280036,2023-02-28 15:10:00,40600.0,40900.0,40513.0
96896,BANKNIFTY_F2,2023-02-28,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,-1.197626,2023-02-28 15:15:00,40600.0,40900.0,40513.0
96897,BANKNIFTY_F2,2023-02-28,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,1.723892,2023-02-28 15:20:00,40600.0,40900.0,40513.0
96898,BANKNIFTY_F2,2023-02-28,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,4.228513,2023-02-28 15:25:00,40600.0,40900.0,40513.0
96899,BANKNIFTY_F2,2023-02-28,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,6.461724,2023-02-28 15:30:00,40600.0,40900.0,40513.0

In [27]:
df.set_index('DateTime', inplace=True)

def calculate_vah_val_poc(df_day):
    total_volume = df_day['Volume'].sum()
    volume_threshold = 0.7 * total_volume  # 70% volume threshold

    df_day['midpoint'] = (df_day['High'] + df_day['Low']) / 2  # Calculate the midpoint for each row
    df_sorted = df_day.sort_values(by='midpoint', ascending=False)

    cumulative_volume = 0
    VAH = None
    VAL = None
    POC = df_sorted.iloc[0]['midpoint']  # Initialize POC as the highest midpoint

    # Accumulate volume to find VAL and POC
    for index, row in df_sorted.iterrows():
        cumulative_volume += row['Volume']
        if cumulative_volume >= volume_threshold:
            VAL = row['midpoint']
            break

    # The highest price in the sorted DataFrame is VAH
    VAH = df_sorted.iloc[0]['midpoint']

    # Calculate Value Area Width in percentage terms
    value_area_width = ((VAH - VAL) / VAH) * 100

    return pd.Series({'VAH': VAH, 'VAL': VAL, 'POC': POC, 'Value Area Width (%)': value_area_width})

# Group by each day and apply the calculate_vah_val_poc function
df_daily = df.groupby(df.index.date).apply(calculate_vah_val_poc)

# Merge the daily results back into the original DataFrame
df = df.join(df_daily, on=df.index.date)
df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%)
DateTime,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,0.000000,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,1.770940,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,2.324572,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,2.141525,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,1.917867,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 15:10:00,BANKNIFTY_F2,2023-02-28,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,-3.280036,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406
2023-02-28 15:15:00,BANKNIFTY_F2,2023-02-28,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,-1.197626,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406
2023-02-28 15:20:00,BANKNIFTY_F2,2023-02-28,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,1.723892,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406
2023-02-28 15:25:00,BANKNIFTY_F2,2023-02-28,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,4.228513,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406
2023-02-28 15:30:00,BANKNIFTY_F2,2023-02-28,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,6.461724,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406

In [28]:
q = pd.DataFrame(resampled)

q['DateTime'] = pd.to_datetime(q['Date'] + ' ' + q['Time'], format='%d-%m-%Y %H:%M')
q.set_index('DateTime', inplace=True)

def calculate_vah_val(df_day):
    total_volume = df_day['Volume'].sum()
    volume_threshold = 0.7 * total_volume #Here i have considered 70%

    df_day['midpoint'] = (df_day['High'] + df_day['Low']) / 2   # Calculating the midpoint for each row
    df_sorted = df_day.sort_values(by='midpoint', ascending=False)

    cumulative_volume = 0
    VAH = None
    VAL = None

    # Accumulate volume and find VAH and VAL
    for index, row in df_sorted.iterrows():
        cumulative_volume += row['Volume']
        if cumulative_volume >= volume_threshold:
            VAL = row['midpoint']
            break

    # The highest price in the sorted DataFrame is VAH
    VAH = df_sorted.iloc[0]['midpoint']
    return pd.Series({'VAH': VAH, 'VAL': VAL})

result = q.groupby(df.index.date).apply(calculate_vah_val)
result

                  VAH        VAL
2018-01-01  25660.200  25545.300
2018-01-02  25529.000  25422.450
2018-01-03  25544.500  25488.900
2018-01-04  25565.700  25510.000
2018-01-05  25711.500  25624.950
...               ...        ...
2023-02-22  40788.050  40354.125
2023-02-23  40392.800  40189.025
2023-02-24  40783.300  40425.000
2023-02-27  40805.650  40558.500
2023-02-28  40813.525  40695.000

[1275 rows x 2 columns]

In [45]:
result = result.rename_axis('Date').rename(columns={'Date': 'Date'})
result

,VAH,VAL,VAH_3day,VAL_3day,VAH_5day,VAL_5day
Date,,,,,,
2018-01-01,25660.200,25545.300,NaN,NaN,NaN,NaN
2018-01-02,25529.000,25422.450,NaN,NaN,NaN,NaN
2018-01-03,25544.500,25488.900,25577.900000,25485.550000,NaN,NaN
2018-01-04,25565.700,25510.000,25546.400000,25473.783333,NaN,NaN
2018-01-05,25711.500,25624.950,25607.233333,25541.283333,25602.180,25518.320
...,...,...,...,...,...,...
2023-02-22,40788.050,40354.125,41166.158333,40791.016667,41498.090,41154.700
2023-02-23,40392.800,40189.025,40791.583333,40497.716667,41131.375,40782.920
2023-02-24,40783.300,40425.000,40654.716667,40322.716667,40934.915,40597.415
2023-02-27,40805.650,40558.500,40660.583333,40390.841667,40792.740,40495.330
2023-02-28,40813.525,40695.000,40800.825000,40559.500000,40716.665,40444.330

In [46]:
poc_last = df.groupby('Date')['Point of Control'].last().reset_index()
result_df = pd.DataFrame(result)

# Merge the result DataFrame with the last POC for each date
final_result = result_df.merge(poc_last, on='Date', how='left')

# Rename columns for clarity
final_result.rename(columns={'Point of Control': 'poc'}, inplace=True)
final_result

,Date,VAH,VAL,VAH_3day,VAL_3day,VAH_5day,VAL_5day,poc
0,2018-01-01,25660.200,25545.300,NaN,NaN,NaN,NaN,25659.90
1,2018-01-02,25529.000,25422.450,NaN,NaN,NaN,NaN,25417.90
2,2018-01-03,25544.500,25488.900,25577.900000,25485.550000,NaN,NaN,25511.00
3,2018-01-04,25565.700,25510.000,25546.400000,25473.783333,NaN,NaN,25500.00
4,2018-01-05,25711.500,25624.950,25607.233333,25541.283333,25602.180,25518.320,25685.20
...,...,...,...,...,...,...,...,...
1270,2023-02-22,40788.050,40354.125,41166.158333,40791.016667,41498.090,41154.700,40708.10
1271,2023-02-23,40392.800,40189.025,40791.583333,40497.716667,41131.375,40782.920,40232.20
1272,2023-02-24,40783.300,40425.000,40654.716667,40322.716667,40934.915,40597.415,40435.25
1273,2023-02-27,40805.650,40558.500,40660.583333,40390.841667,40792.740,40495.330,40583.65
1274,2023-02-28,40813.525,40695.000,40800.825000,40559.500000,40716.665,40444.330,40600.00

In [48]:
dff=final_result
dff['VAH_3day'] = dff['VAH'].rolling(window=3).mean()
dff['VAL_3day'] = dff['VAL'].rolling(window=3).mean()
dff['VAH_5day'] = dff['VAH'].rolling(window=5).mean()
dff['VAL_5day'] = dff['VAL'].rolling(window=5).mean()

# Calculate rolling POC
dff['POC_3day'] = dff['poc'].rolling(window=3).mean()
dff['POC_5day'] = dff['poc'].rolling(window=5).mean()
dff

,Date,VAH,VAL,VAH_3day,VAL_3day,VAH_5day,VAL_5day,poc,POC_3day,POC_5day
0,2018-01-01,25660.200,25545.300,NaN,NaN,NaN,NaN,25659.90,NaN,NaN
1,2018-01-02,25529.000,25422.450,NaN,NaN,NaN,NaN,25417.90,NaN,NaN
2,2018-01-03,25544.500,25488.900,25577.900000,25485.550000,NaN,NaN,25511.00,25529.600000,NaN
3,2018-01-04,25565.700,25510.000,25546.400000,25473.783333,NaN,NaN,25500.00,25476.300000,NaN
4,2018-01-05,25711.500,25624.950,25607.233333,25541.283333,25602.180,25518.320,25685.20,25565.400000,25554.80
...,...,...,...,...,...,...,...,...,...,...
1270,2023-02-22,40788.050,40354.125,41166.158333,40791.016667,41498.090,41154.700,40708.10,40891.283333,41261.28
1271,2023-02-23,40392.800,40189.025,40791.583333,40497.716667,41131.375,40782.920,40232.20,40647.866667,40872.77
1272,2023-02-24,40783.300,40425.000,40654.716667,40322.716667,40934.915,40597.415,40435.25,40458.516667,40668.26
1273,2023-02-27,40805.650,40558.500,40660.583333,40390.841667,40792.740,40495.330,40583.65,40417.033333,40592.50
1274,2023-02-28,40813.525,40695.000,40800.825000,40559.500000,40716.665,40444.330,40600.00,40539.633333,40511.84

In [29]:
def calculate_ghost_zone(df_day, vah, val):
    # Filter prices above VAH and below VAL
    above_vah = df_day[df_day['High'] > vah]
    below_val = df_day[df_day['Low'] < val]

    highest_above_vah = above_vah['High'].max() if not above_vah.empty else None
    lowest_below_val = below_val['Low'].min() if not below_val.empty else None

    return pd.Series({'Highest Above VAH': highest_above_vah, 'Lowest Below VAL': lowest_below_val})

# Join the original df with the calculated daily VAH and VAL
daily_vah_val = result[['VAH', 'VAL']]

# Iterate over each day to calculate the ghost zone
ghost_zones = []
for date, vah_val in daily_vah_val.iterrows():
    vah = vah_val['VAH']
    val = vah_val['VAL']
    df_day = df[df.index.date == pd.Timestamp(date).date()]

    ghost_zone = calculate_ghost_zone(df_day, vah, val)
    ghost_zones.append(ghost_zone)

# Convert list of series to DataFrame
ghost_zones_df = pd.DataFrame(ghost_zones, index=daily_vah_val.index)

# Combine with the existing result DataFrame
result_with_ghost_zones = result.join(ghost_zones_df)
result_with_ghost_zones

                  VAH        VAL  Highest Above VAH  Lowest Below VAL
2018-01-01  25660.200  25545.300           25675.70          25481.30
2018-01-02  25529.000  25422.450           25554.60          25360.00
2018-01-03  25544.500  25488.900           25550.00          25432.80
2018-01-04  25565.700  25510.000           25573.30          25436.30
2018-01-05  25711.500  25624.950           25720.00          25575.00
...               ...        ...                ...               ...
2023-02-22  40788.050  40354.125           40850.00          40177.00
2023-02-23  40392.800  40189.025           40437.60          39870.00
2023-02-24  40783.300  40425.000           40841.55          40308.05
2023-02-27  40805.650  40558.500           40815.00          40228.05
2023-02-28  40813.525  40695.000           40900.00          40513.00

[1275 rows x 4 columns]

In [34]:
merged_df = df.merge(result_with_ghost_zones[['Highest Above VAH', 'Lowest Below VAL']], left_on=df.index.date, right_index=True, how='left')
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,MACD,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL
DateTime,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,0.000000,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,1.770940,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,2.324572,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,2.141525,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,1.917867,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 15:10:00,BANKNIFTY_F2,2023-02-28,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,-3.280036,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0
2023-02-28 15:15:00,BANKNIFTY_F2,2023-02-28,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,-1.197626,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0
2023-02-28 15:20:00,BANKNIFTY_F2,2023-02-28,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,1.723892,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0
2023-02-28 15:25:00,BANKNIFTY_F2,2023-02-28,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,4.228513,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0
2023-02-28 15:30:00,BANKNIFTY_F2,2023-02-28,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,6.461724,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0

In [35]:
merged_df['Previous Day VAH'] = merged_df['VAH'].shift(1)
merged_df['Previous Day VAL'] = merged_df['VAL'].shift(1)

# Function to determine gap up or gap down
def gap_type(row):
    if row['Open'] >= row['Previous Day VAH']:
        return 'Gap Up'
    elif row['Close'] <= row['Previous Day VAL']:
        return 'Gap Down'
    else:
        return ''

# Apply the function to each row
merged_df['Gap Type'] = merged_df.apply(gap_type, axis=1)

# Handle consecutive missing days
merged_df['Date'] = pd.to_datetime(merged_df['Date'])
merged_df['Date_diff'] = merged_df['Date'].diff().dt.days
merged_df.loc[merged_df['Date_diff'] > 1, 'Gap Type'] = ''

merged_df['Gap Type'] = merged_df.groupby('Date')['Gap Type'].transform(lambda x: x.iloc[0]).fillna('')

# Drop the auxiliary columns if needed
merged_df.drop(['Previous Day VAH', 'Previous Day VAL', 'Date_diff'], axis=1, inplace=True)
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Point of Control,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL,Gap Type
DateTime,,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,...,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,...,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,...,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,...,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,...,25659.9,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 15:10:00,BANKNIFTY_F2,2023-02-28,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,...,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up
2023-02-28 15:15:00,BANKNIFTY_F2,2023-02-28,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,...,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up
2023-02-28 15:20:00,BANKNIFTY_F2,2023-02-28,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,...,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up
2023-02-28 15:25:00,BANKNIFTY_F2,2023-02-28,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,...,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up
2023-02-28 15:30:00,BANKNIFTY_F2,2023-02-28,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,...,40600.0,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up

In [36]:
def is_gap_filled(row):
    if row['Open'] >= row['Previous Day Low'] and row['Open'] <= row['High']:
        return 'Yes'
    else:
        return 'No'

merged_df['Previous Day Low'] = merged_df['Low'].shift(1)
merged_df['Gap Filled'] = merged_df.apply(is_gap_filled, axis=1)
merged_df.drop('Previous Day Low', axis=1, inplace=True)
merged_df

,Symbol,Date,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,Local Maximum,Local Minimum,VAH,VAL,POC,Value Area Width (%),Highest Above VAH,Lowest Below VAL,Gap Type,Gap Filled
DateTime,,,,,,,,,,,,,,,,,,,,,
2018-01-01 09:15:00,BANKNIFTY_F2,2018-01-01,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,...,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,,No
2018-01-01 09:20:00,BANKNIFTY_F2,2018-01-01,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,...,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,,Yes
2018-01-01 09:25:00,BANKNIFTY_F2,2018-01-01,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,...,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,,Yes
2018-01-01 09:30:00,BANKNIFTY_F2,2018-01-01,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,...,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,,No
2018-01-01 09:35:00,BANKNIFTY_F2,2018-01-01,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,...,25675.7,25481.3,25660.200,25545.3,25660.200,0.447775,25675.7,25481.3,,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-02-28 15:10:00,BANKNIFTY_F2,2023-02-28,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,...,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up,Yes
2023-02-28 15:15:00,BANKNIFTY_F2,2023-02-28,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,...,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up,Yes
2023-02-28 15:20:00,BANKNIFTY_F2,2023-02-28,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,...,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up,Yes
2023-02-28 15:25:00,BANKNIFTY_F2,2023-02-28,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,...,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up,Yes
2023-02-28 15:30:00,BANKNIFTY_F2,2023-02-28,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,...,40900.0,40513.0,40813.525,40695.0,40813.525,0.290406,40900.0,40513.0,Gap Up,Yes

In [51]:
merged_df.reset_index(inplace=True)
merged_df['Date'] = merged_df['DateTime'].dt.date
merged_df = pd.merge(merged_df, dff, on='Date', how='left')
merged_df.drop('Date', axis=1, inplace=True)
merged_df.head()

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,POC_5d,VAH_y,VAL_y,VAH_3day,VAL_3day,VAH_5day,VAL_5day,poc,POC_3day,POC_5day
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.0,25643.1,25608.0,25643.1,480.0,0.0,25631.400000,...,25660.2,25660.2,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.5,25675.7,25631.5,25665.3,600.0,0.0,25645.900000,...,25660.2,25660.2,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.3,25665.3,25655.1,25655.1,240.0,0.0,25648.190909,...,25660.2,25660.2,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.7,25647.7,25647.7,25647.7,240.0,0.0,25648.115385,...,25660.2,25660.2,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.7,25647.7,25647.0,25647.0,440.0,0.0,25647.921333,...,25660.2,25660.2,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN

In [52]:
merged_df

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,POC_5d,VAH_y,VAL_y,VAH_3day,VAL_3day,VAH_5day,VAL_5day,poc,POC_3day,POC_5day
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,...,25660.200,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,...,25660.200,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,...,25660.200,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,...,25660.200,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,...,25660.200,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96895,2023-02-28 15:10:00,BANKNIFTY_F2,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,...,40716.665,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84
96896,2023-02-28 15:15:00,BANKNIFTY_F2,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,...,40716.665,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84
96897,2023-02-28 15:20:00,BANKNIFTY_F2,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,...,40716.665,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84
96898,2023-02-28 15:25:00,BANKNIFTY_F2,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,...,40716.665,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84
96899,2023-02-28 15:30:00,BANKNIFTY_F2,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,...,40716.665,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84

In [53]:
'''merged_df.index = pd.to_datetime(merged_df.index)

# Step 2: Group by Date
merged_df['Date'] = merged_df.index.date

# Define a helper function to calculate the rolling values and expand them for the whole day
def calculate_rolling(df, window):
    rolling_df = df[['VAH', 'VAL', 'POC']].rolling(window=window).mean()
    for date in df['Date'].unique():
        df.loc[df['Date'] == date, f'VAH_{window}d'] = rolling_df.loc[df['Date'] == date, 'VAH']
        df.loc[df['Date'] == date, f'VAL_{window}d'] = rolling_df.loc[df['Date'] == date, 'VAL']
        df.loc[df['Date'] == date, f'POC_{window}d'] = rolling_df.loc[df['Date'] == date, 'POC']

# Step 3: Calculate 3-day rolling and 5-day rolling
calculate_rolling(merged_df, 3)
calculate_rolling(merged_df, 5)

# Drop the Date column as it's no longer needed
merged_df.drop(columns=['Date'], inplace=True)
merged_df'''

"merged_df.index = pd.to_datetime(merged_df.index)\n\n# Step 2: Group by Date\nmerged_df['Date'] = merged_df.index.date\n\n# Define a helper function to calculate the rolling values and expand them for the whole day\ndef calculate_rolling(df, window):\n    rolling_df = df[['VAH', 'VAL', 'POC']].rolling(window=window).mean()\n    for date in df['Date'].unique():\n        df.loc[df['Date'] == date, f'VAH_{window}d'] = rolling_df.loc[df['Date'] == date, 'VAH']\n        df.loc[df['Date'] == date, f'VAL_{window}d'] = rolling_df.loc[df['Date'] == date, 'VAL']\n        df.loc[df['Date'] == date, f'POC_{window}d'] = rolling_df.loc[df['Date'] == date, 'POC']\n\n# Step 3: Calculate 3-day rolling and 5-day rolling\ncalculate_rolling(merged_df, 3)\ncalculate_rolling(merged_df, 5)\n\n# Drop the Date column as it's no longer needed\nmerged_df.drop(columns=['Date'], inplace=True)\nmerged_df"

In [ ]:
'''grouped_df = merged_df.groupby('Date')

# Calculate the desired metrics for each group (date)
merged_df['3_day_VAH'] = grouped_df['VAH'].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)
merged_df['5_day_VAH'] = grouped_df['VAH'].rolling(window=5, min_periods=1).mean().reset_index(level=0, drop=True)

merged_df['3_day_VAL'] = grouped_df['VAL'].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)
merged_df['5_day_VAL'] = grouped_df['VAL'].rolling(window=5, min_periods=1).mean().reset_index(level=0, drop=True)

merged_df['3_day_POC'] = grouped_df['POC'].rolling(window=3, min_periods=1).mean().reset_index(level=0, drop=True)
merged_df['5_day_POC'] = grouped_df['POC'].rolling(window=5, min_periods=1).mean().reset_index(level=0, drop=True)

merged_df['3_day_VP_high'] = grouped_df['Volume'].rolling(window=3, min_periods=1).max().reset_index(level=0, drop=True)
merged_df['3_day_VP_low'] = grouped_df['Volume'].rolling(window=3, min_periods=1).min().reset_index(level=0, drop=True)

merged_df['5_day_VP_high'] = grouped_df['Volume'].rolling(window=5, min_periods=1).max().reset_index(level=0, drop=True)
merged_df['5_day_VP_low'] = grouped_df['Volume'].rolling(window=5, min_periods=1).min().reset_index(level=0, drop=True)

# Forward fill the calculated values for each day
merged_df = merged_df.groupby('Date').ffill()

# Print the DataFrame to check the results
merged_df'''

In [56]:
'''import pandas as pd

# Step 1: Ensure the DateTime index is set correctly
#merged_df.index = pd.to_datetime(merged_df.index)

# Step 2: Group by Date
merged_df['Date'] = merged_df.index.date

# Step 3: Create a function to calculate the rolling values considering non-trading days
def custom_rolling(df, window):
    # Get unique dates in the DataFrame
    unique_dates = df['Date'].unique()

    # Initialize columns for the rolling values
    df[f'VAH_{window}d'] = pd.Series(dtype='float64')
    df[f'VAL_{window}d'] = pd.Series(dtype='float64')
    df[f'POC_{window}d'] = pd.Series(dtype='float64')

    # Loop through each unique date
    for current_date in unique_dates:
        # Find the index of the current date
        date_index = list(unique_dates).index(current_date)

        # Get the previous trading dates considering the window
        start_index = max(0, date_index - window + 1)
        previous_dates = unique_dates[start_index:date_index + 1]

        # Filter the dataframe for the previous trading dates
        previous_df = df[df['Date'].isin(previous_dates)]

        # Calculate the rolling mean for VAH, VAL, and POC
        rolling_means = previous_df[['VAH', 'VAL', 'POC']].mean()

        # Assign the rolling means to the entire current day
        df.loc[df['Date'] == current_date, f'VAH_{window}d'] = rolling_means['VAH']
        df.loc[df['Date'] == current_date, f'VAL_{window}d'] = rolling_means['VAL']
        df.loc[df['Date'] == current_date, f'POC_{window}d'] = rolling_means['POC']

    return df

# Step 4: Calculate 3-day rolling and 5-day rolling using the custom rolling function
merged_df = custom_rolling(merged_df, 3)
merged_df = custom_rolling(merged_df, 5)

# Drop the Date column as it's no longer needed
merged_df.drop(columns=['Date'], inplace=True)

# If you want to inspect the first few rows to ensure correctness
merged_df.head()
'''

"import pandas as pd\n\n# Step 1: Ensure the DateTime index is set correctly\n#merged_df.index = pd.to_datetime(merged_df.index)\n\n# Step 2: Group by Date\nmerged_df['Date'] = merged_df.index.date\n\n# Step 3: Create a function to calculate the rolling values considering non-trading days\ndef custom_rolling(df, window):\n    # Get unique dates in the DataFrame\n    unique_dates = df['Date'].unique()\n    \n    # Initialize columns for the rolling values\n    df[f'VAH_{window}d'] = pd.Series(dtype='float64')\n    df[f'VAL_{window}d'] = pd.Series(dtype='float64')\n    df[f'POC_{window}d'] = pd.Series(dtype='float64')\n    \n    # Loop through each unique date\n    for current_date in unique_dates:\n        # Find the index of the current date\n        date_index = list(unique_dates).index(current_date)\n        \n        # Get the previous trading dates considering the window\n        start_index = max(0, date_index - window + 1)\n        previous_dates = unique_dates[start_index:date_index + 1]\n        \n        # Filter the dataframe for the previous trading dates\n        previous_df = df[df['Date'].isin(previous_dates)]\n        \n        # Calculate the rolling mean for VAH, VAL, and POC\n        rolling_means = previous_df[['VAH', 'VAL', 'POC']].mean()\n        \n        # Assign the rolling means to the entire current day\n        df.loc[df['Date'] == current_date, f'VAH_{window}d'] = rolling_means['VAH']\n        df.loc[df['Date'] == current_date, f'VAL_{window}d'] = rolling_means['VAL']\n        df.loc[df['Date'] == current_date, f'POC_{window}d'] = rolling_means['POC']\n    \n    return df\n\n# Step 4: Calculate 3-day rolling and 5-day rolling using the custom rolling function\nmerged_df = custom_rolling(merged_df, 3)\nmerged_df = custom_rolling(merged_df, 5)\n\n# Drop the Date column as it's no longer needed\nmerged_df.drop(columns=['Date'], inplace=True)\n\n# If you want to inspect the first few rows to ensure correctness\nmerged_df.head()\n"

In [61]:
import pandas as pd
fut_df1 = pd.DataFrame(merged_df)

fut_df1.reset_index(drop=True, inplace=True)
fut_df1['DateTime'] = pd.to_datetime(fut_df1['DateTime'])

# Identify the first day of each weekly expiry (assuming weekly expiry is every Thursday)
fut_df1['Week_Start'] = fut_df1['DateTime'].dt.to_period('W').apply(lambda r: r.start_time)
week_starts = fut_df1['Week_Start'].unique()

fut_df1['AWAP'] = pd.Series(dtype='float64')
for week_start in week_starts:
    mask = fut_df1['Week_Start'] == week_start
    weekly_data = fut_df1[mask]
    fut_df1.loc[mask, 'AWAP'] = (weekly_data['Close'] * weekly_data['Volume']).cumsum() / weekly_data['Volume'].cumsum()

fut_df1['AWAP'] = fut_df1.groupby('Week_Start')['AWAP'].ffill()
fut_df1.drop(columns=['Week_Start'], inplace=True)

                 DateTime        Symbol      Time      Open      High  \
0     2018-01-01 09:15:00  BANKNIFTY_F2  09:15:00  25634.00  25643.10
1     2018-01-01 09:20:00  BANKNIFTY_F2  09:20:00  25631.50  25675.70
2     2018-01-01 09:25:00  BANKNIFTY_F2  09:25:00  25665.30  25665.30
3     2018-01-01 09:30:00  BANKNIFTY_F2  09:30:00  25647.70  25647.70
4     2018-01-01 09:35:00  BANKNIFTY_F2  09:35:00  25647.70  25647.70
...                   ...           ...       ...       ...       ...
96895 2023-02-28 15:10:00  BANKNIFTY_F2  15:10:00  40699.55  40699.55
96896 2023-02-28 15:15:00  BANKNIFTY_F2  15:15:00  40700.00  40700.00
96897 2023-02-28 15:20:00  BANKNIFTY_F2  15:20:00  40696.30  40721.95
96898 2023-02-28 15:25:00  BANKNIFTY_F2  15:25:00  40715.20  40715.20
96899 2023-02-28 15:30:00  BANKNIFTY_F2  15:30:00  40706.00  40710.00

           Low     Close  Volume  Open Interest          VWAP  ...      VAH_y  \
0      25608.0  25643.10   480.0            0.0  25631.400000  ...  25660.200
1      25631.5  25665.30   600.0            0.0  25645.900000  ...  25660.200
2      25655.1  25655.10   240.0            0.0  25648.190909  ...  25660.200
3      25647.7  25647.70   240.0            0.0  25648.115385  ...  25660.200
4      25647.0  25647.00   440.0            0.0  25647.921333  ...  25660.200
...        ...       ...     ...            ...           ...  ...        ...
96895  40671.3  40691.00  1250.0      1170525.0  31839.317288  ...  40813.525
96896  40670.0  40687.05  1850.0      1170650.0  31839.331858  ...  40813.525
96897  40695.0  40703.05  6000.0      1171475.0  31839.379226  ...  40813.525
96898  40694.1  40706.00  4700.0      1173225.0  31839.416324  ...  40813.525
96899  40705.0  40710.00  1100.0      1173225.0  31839.425009  ...  40813.525

         VAL_y   VAH_3day  VAL_3day   VAH_5day  VAL_5day      poc  \
0      25545.3        NaN       NaN        NaN       NaN  25659.9
1      25545.3        NaN       NaN        NaN       NaN  25659.9
2      25545.3        NaN       NaN        NaN       NaN  25659.9
3      25545.3        NaN       NaN        NaN       NaN  25659.9
4      25545.3        NaN       NaN        NaN       NaN  25659.9
...        ...        ...       ...        ...       ...      ...
96895  40695.0  40800.825   40559.5  40716.665  40444.33  40600.0
96896  40695.0  40800.825   40559.5  40716.665  40444.33  40600.0
96897  40695.0  40800.825   40559.5  40716.665  40444.33  40600.0
96898  40695.0  40800.825   40559.5  40716.665  40444.33  40600.0
96899  40695.0  40800.825   40559.5  40716.665  40444.33  40600.0

           POC_3day  POC_5day          AWAP
0               NaN       NaN  25643.100000
1               NaN       NaN  25655.433333
2               NaN       NaN  25655.372727
3               NaN       NaN  25654.192308
4               NaN       NaN  25652.610000
...             ...       ...           ...
96895  40539.633333  40511.84  40608.156720
96896  40539.633333  40511.84  40608.252836
96897  40539.633333  40511.84  40608.625931
96898  40539.633333  40511.84  40608.925210
96899  40539.633333  40511.84  40608.997864

[96900 rows x 38 columns]

In [62]:
fut_df1

,DateTime,Symbol,Time,Open,High,Low,Close,Volume,Open Interest,VWAP,...,VAH_y,VAL_y,VAH_3day,VAL_3day,VAH_5day,VAL_5day,poc,POC_3day,POC_5day,AWAP
0,2018-01-01 09:15:00,BANKNIFTY_F2,09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,...,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN,25643.100000
1,2018-01-01 09:20:00,BANKNIFTY_F2,09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,...,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN,25655.433333
2,2018-01-01 09:25:00,BANKNIFTY_F2,09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,...,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN,25655.372727
3,2018-01-01 09:30:00,BANKNIFTY_F2,09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,...,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN,25654.192308
4,2018-01-01 09:35:00,BANKNIFTY_F2,09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,...,25660.200,25545.3,NaN,NaN,NaN,NaN,25659.9,NaN,NaN,25652.610000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96895,2023-02-28 15:10:00,BANKNIFTY_F2,15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,...,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84,40608.156720
96896,2023-02-28 15:15:00,BANKNIFTY_F2,15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,...,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84,40608.252836
96897,2023-02-28 15:20:00,BANKNIFTY_F2,15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,...,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84,40608.625931
96898,2023-02-28 15:25:00,BANKNIFTY_F2,15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,...,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84,40608.925210
96899,2023-02-28 15:30:00,BANKNIFTY_F2,15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,...,40813.525,40695.0,40800.825,40559.5,40716.665,40444.33,40600.0,40539.633333,40511.84,40608.997864

In [63]:
#fut_df1 = pd.DataFrame(merged_df)

# Convert 'Date' and 'Time' columns to a single datetime column
#df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], format='%d-%m-%Y %H:%M')
#df.set_index('Datetime', inplace=True)
'''
# Identify the first day of each weekly expiry (assuming weekly expiry is every Thursday)
fut_df1['Week_Start'] = fut_df1.index.to_period('W').start_time
week_starts = fut_df1['Week_Start'].unique()

# Initialize a new column for Anchored VWAP
fut_df1['AWAP'] = pd.Series(dtype='float64')

# Calculate Anchored VWAP for each week
for week_start in week_starts:
    mask = fut_df1['Week_Start'] == week_start
    weekly_data = fut_df1[mask]
    fut_df1.loc[mask, 'AWAP'] = (weekly_data['Close'] * weekly_data['Volume']).cumsum() / weekly_data['Volume'].cumsum()

# Forward fill the calculated values for each week
fut_df1['AWAP'] = fut_df1.groupby('Week_Start')['AWAP'].ffill()

# Drop the helper columns
fut_df1.drop(columns=['Week_Start'], inplace=True)

# Display the DataFrame'''
#fut_df1.reset_index(inplace=True)

# Assuming you want to combine 'Date' and 'Time' columns into a single 'DateTime' column
#fut_df1['Datetime'] = pd.to_datetime(fut_df1['Date'] + ' ' + fut_df1['Time'], format='%Y-%m-%d %H:%M:%S')

# Set 'Datetime' column as the index
#fut_df1.set_index('Datetime', inplace=True)

# Identify the first day of each weekly expiry (assuming weekly expiry is every Thursday)
'''fut_df1['Week_Start'] = fut_df1.index.to_period('W').start_time
week_starts = fut_df1['Week_Start'].unique()

# Initialize a new column for Anchored VWAP
fut_df1['AWAP'] = pd.Series(dtype='float64')

# Calculate Anchored VWAP for each week
for week_start in week_starts:
    mask = fut_df1['Week_Start'] == week_start
    weekly_data = fut_df1[mask]
    fut_df1.loc[mask, 'AWAP'] = (weekly_data['Close'] * weekly_data['Volume']).cumsum() / weekly_data['Volume'].cumsum()

# Forward fill the calculated values for each week
fut_df1['AWAP'] = fut_df1.groupby('Week_Start')['AWAP'].ffill()

# Drop the helper columns
fut_df1.drop(columns=['Week_Start'], inplace=True)
fut_df1'''

"fut_df1['Week_Start'] = fut_df1.index.to_period('W').start_time\nweek_starts = fut_df1['Week_Start'].unique()\n\n# Initialize a new column for Anchored VWAP\nfut_df1['AWAP'] = pd.Series(dtype='float64')\n\n# Calculate Anchored VWAP for each week\nfor week_start in week_starts:\n    mask = fut_df1['Week_Start'] == week_start\n    weekly_data = fut_df1[mask]\n    fut_df1.loc[mask, 'AWAP'] = (weekly_data['Close'] * weekly_data['Volume']).cumsum() / weekly_data['Volume'].cumsum()\n\n# Forward fill the calculated values for each week\nfut_df1['AWAP'] = fut_df1.groupby('Week_Start')['AWAP'].ffill()\n\n# Drop the helper columns\nfut_df1.drop(columns=['Week_Start'], inplace=True)\nfut_df1"

In [65]:
fut_df1.columns

Index(['DateTime', 'Symbol', 'Time', 'Open', 'High', 'Low', 'Close', 'Volume',
       'Open Interest', 'VWAP', 'MACD', 'Point of Control', 'Local Maximum',
       'Local Minimum', 'VAH_x', 'VAL_x', 'POC', 'Value Area Width (%)',
       'Highest Above VAH', 'Lowest Below VAL', 'Gap Type', 'Gap Filled',
       'VAH_3d', 'VAL_3d', 'POC_3d', 'VAH_5d', 'VAL_5d', 'POC_5d', 'VAH_y',
       'VAL_y', 'VAH_3day', 'VAL_3day', 'VAH_5day', 'VAL_5day', 'poc',
       'POC_3day', 'POC_5day', 'AWAP'],
      dtype='object')

In [78]:
testing=fut_df1.copy()
testing.drop(columns=['Symbol',	'Time'], inplace=True)
testing.rename(columns={'DateTime':'datetime','Open': 'open', 'Close': 'close','High':'high',	'Low':'low',	'Close':'close',	'Volume':'volume',	'Open Interest':'oi',	'VWAP':'vwap',
                   'MACD':'macd',
 'Point of Control':'poc',
 'Local Maximum':'local_max',
 'Local Minimum':'local_min',
 'VAH_x':'vah',
 'VAL_x':'val',
 'POC':'poc',
 'Value Area Width (%)':'value_area_width(%)',
 'Highest Above VAH':'highest_above_vah',
 'Lowest Below VAL':'lowest_below_val',
 'Gap Type':'gap_type',
 'Gap Filled':'gap_filled',
 'VAH_3d':'3_day_vah',
 'VAH_5d':'5_day_vah',
 'VAL_3d':'3_day_val',
 'VAL_5d':'5_day_val',
 'POC_3d':'3_day_poc',
 'POC_5d':'5_day_poc',
 'AWAP':'awap'}, inplace=True)
new_column_order = ['datetime','open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

# Reorder the DataFrame columns
fut_reordered = testing[new_column_order]
fut_reordered

,datetime,open,high,low,close,volume,oi,vwap,awap,macd,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-01-01 09:15:00,25634.00,25643.10,25608.0,25643.10,480.0,0.0,25631.400000,25643.100000,0.000000,...,25675.7,25481.3,,No,25660.200,25660.200,25545.3,25545.30,25660.200,25660.200
1,2018-01-01 09:20:00,25631.50,25675.70,25631.5,25665.30,600.0,0.0,25645.900000,25655.433333,1.770940,...,25675.7,25481.3,,Yes,25660.200,25660.200,25545.3,25545.30,25660.200,25660.200
2,2018-01-01 09:25:00,25665.30,25665.30,25655.1,25655.10,240.0,0.0,25648.190909,25655.372727,2.324572,...,25675.7,25481.3,,Yes,25660.200,25660.200,25545.3,25545.30,25660.200,25660.200
3,2018-01-01 09:30:00,25647.70,25647.70,25647.7,25647.70,240.0,0.0,25648.115385,25654.192308,2.141525,...,25675.7,25481.3,,No,25660.200,25660.200,25545.3,25545.30,25660.200,25660.200
4,2018-01-01 09:35:00,25647.70,25647.70,25647.0,25647.00,440.0,0.0,25647.921333,25652.610000,1.917867,...,25675.7,25481.3,,Yes,25660.200,25660.200,25545.3,25545.30,25660.200,25660.200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96895,2023-02-28 15:10:00,40699.55,40699.55,40671.3,40691.00,1250.0,1170525.0,31839.317288,40608.156720,-3.280036,...,40900.0,40513.0,Gap Up,Yes,40800.825,40716.665,40559.5,40444.33,40800.825,40716.665
96896,2023-02-28 15:15:00,40700.00,40700.00,40670.0,40687.05,1850.0,1170650.0,31839.331858,40608.252836,-1.197626,...,40900.0,40513.0,Gap Up,Yes,40800.825,40716.665,40559.5,40444.33,40800.825,40716.665
96897,2023-02-28 15:20:00,40696.30,40721.95,40695.0,40703.05,6000.0,1171475.0,31839.379226,40608.625931,1.723892,...,40900.0,40513.0,Gap Up,Yes,40800.825,40716.665,40559.5,40444.33,40800.825,40716.665
96898,2023-02-28 15:25:00,40715.20,40715.20,40694.1,40706.00,4700.0,1173225.0,31839.416324,40608.925210,4.228513,...,40900.0,40513.0,Gap Up,Yes,40800.825,40716.665,40559.5,40444.33,40800.825,40716.665
96899,2023-02-28 15:30:00,40706.00,40710.00,40705.0,40710.00,1100.0,1173225.0,31839.425009,40608.997864,6.461724,...,40900.0,40513.0,Gap Up,Yes,40800.825,40716.665,40559.5,40444.33,40800.825,40716.665

In [ ]:
#df_reordered.to_csv('fut_testing.csv', index=True)

In [79]:
import pandas as pd
final_opt_df['datetime'] = pd.to_datetime(final_opt_df['datetime'])

fut_reordered = fut_reordered.reset_index()
fut_reordered['datetime'] = pd.to_datetime(fut_reordered['datetime'])
finals = pd.merge(final_opt_df, fut_reordered, left_on='datetime', right_on='datetime', how='inner')
finals

<ipython-input-79-ca3a87083fba>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_opt_df['datetime'] = pd.to_datetime(final_opt_df['datetime'])

,datetime,atm,max_pain_strike,intraday_pcr,cumulative_pcr,most_active_strikes,index,open,high,low,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-12-03 09:15:00,27055.5,26500,0.683871,0.683871,"25000PE, 26000PE, 26000CE, 25500PE, 26600PE, 2...",17100,27100.00,27138.40,27069.80,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
1,2018-12-03 09:20:00,27055.5,26500,0.849990,0.746159,"25000PE, 26000PE, 26000CE, 25500PE, 27200CE, 2...",17101,27091.00,27094.75,27046.25,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
2,2018-12-03 09:25:00,27055.5,26600,0.962676,0.802238,"25000PE, 26000PE, 25500PE, 26600PE, 26400PE, 2...",17102,27053.95,27053.95,27030.00,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
3,2018-12-03 09:30:00,27055.5,26800,0.811316,0.804080,"26000PE, 25500PE, 26600PE, 26400PE, 26500PE, 2...",17103,27036.85,27040.00,27010.45,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
4,2018-12-03 09:35:00,27055.5,26800,0.693757,0.788170,"25000PE, 26000PE, 27200CE, 25500PE, 26600PE, 2...",17104,27010.45,27055.00,27010.45,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2018-12-31 15:10:00,27400.0,27000,0.956274,0.859714,"27500PE, 26900PE, 27000CE, 27000PE, 26800PE, 2...",18615,27400.00,27405.70,27400.00,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1506,2018-12-31 15:15:00,27400.0,27000,0.858456,0.859713,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2...",18616,27405.70,27416.00,27405.70,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1507,2018-12-31 15:20:00,27400.0,27000,0.711615,0.859632,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2...",18617,27416.00,27416.50,27405.00,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1508,2018-12-31 15:25:00,27400.0,27000,0.658744,0.861610,"27500PE, 27000CE, 27000PE, 27500CE, 26500PE, 2...",18618,27405.60,27412.25,27403.80,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1509,2018-12-31 15:30:00,27400.0,27200,0.720339,0.861610,"27500CE, 27400CE, 27300CE, 27000PE, 26900PE, 2...",18619,27405.10,27405.10,27401.05,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180

In [80]:
finals.columns.tolist()

['datetime',
 'atm',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'index',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'poc',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [84]:
column_order = [
    'datetime', 'atm', 'open', 'high', 'low', 'close', 'volume', 'oi',
    'max_pain_strike', 'intraday_pcr', 'cumulative_pcr', 'most_active_strikes',
    'vwap', 'awap', 'macd', 'local_max', 'local_min', 'vah', 'val', 'poc',
    'value_area_width(%)', 'highest_above_vah', 'lowest_below_val', 'gap_type',
    'gap_filled', '3_day_vah', '5_day_vah', '3_day_val', '5_day_val', '3_day_poc',
    '5_day_poc'
]

final_columns = [col for col in column_order if col in finals.columns]
final_s = finals[final_columns]
final_s

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-12-03 09:15:00,27055.5,27100.00,27138.40,27069.80,27085.00,4040.0,29500.0,26500,0.683871,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
1,2018-12-03 09:20:00,27055.5,27091.00,27094.75,27046.25,27049.00,2520.0,29660.0,26500,0.849990,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
2,2018-12-03 09:25:00,27055.5,27053.95,27053.95,27030.00,27036.85,700.0,30100.0,26600,0.962676,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
3,2018-12-03 09:30:00,27055.5,27036.85,27040.00,27010.45,27011.15,2300.0,30240.0,26800,0.811316,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
4,2018-12-03 09:35:00,27055.5,27010.45,27055.00,27010.45,27027.25,1320.0,30700.0,26800,0.693757,...,27138.40,26970.0,,Yes,27038.333333,26853.505,26906.775000,26736.535,27038.333333,26853.505
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2018-12-31 15:10:00,27400.0,27400.00,27405.70,27400.00,27405.70,260.0,40520.0,27000,0.956274,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1506,2018-12-31 15:15:00,27400.0,27405.70,27416.00,27405.70,27416.00,340.0,40600.0,27000,0.858456,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1507,2018-12-31 15:20:00,27400.0,27416.00,27416.50,27405.00,27407.10,400.0,40580.0,27000,0.711615,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1508,2018-12-31 15:25:00,27400.0,27405.60,27412.25,27403.80,27403.80,340.0,40540.0,27000,0.658744,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180
1509,2018-12-31 15:30:00,27400.0,27405.10,27405.10,27401.05,27401.05,240.0,40540.0,27200,0.720339,...,27511.15,27319.2,,Yes,27401.225000,27287.180,27276.008333,27083.970,27401.225000,27287.180

In [87]:
final_s.columns.tolist()

['datetime',
 'atm',
 'open',
 'high',
 'low',
 'close',
 'volume',
 'oi',
 'max_pain_strike',
 'intraday_pcr',
 'cumulative_pcr',
 'most_active_strikes',
 'vwap',
 'awap',
 'macd',
 'local_max',
 'local_min',
 'vah',
 'val',
 'poc',
 'poc',
 'poc',
 'value_area_width(%)',
 'highest_above_vah',
 'lowest_below_val',
 'gap_type',
 'gap_filled',
 '3_day_vah',
 '5_day_vah',
 '3_day_val',
 '5_day_val',
 '3_day_poc',
 '5_day_poc']

In [88]:
columns_to_round2 = ['vwap', 'awap', 'macd', 'val','3_day_vah' , '3_day_val', '5_day_vah','5_day_val','3_day_poc',	'5_day_poc'
]
columns_to_round4 = [
    'intraday_pcr', 'cumulative_pcr',
    'value_area_width(%)'
]
final_s[columns_to_round2] = final_s[columns_to_round2].round(2)
final_s[columns_to_round4] = final_s[columns_to_round4].round(4)
final_s

<ipython-input-88-ccdccdc428d7>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_s[columns_to_round2] = final_s[columns_to_round2].round(2)
<ipython-input-88-ccdccdc428d7>:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_s[columns_to_round4] = final_s[columns_to_round4].round(4)

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-12-03 09:15:00,27055.5,27100.00,27138.40,27069.80,27085.00,4040.0,29500.0,26500,0.6839,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
1,2018-12-03 09:20:00,27055.5,27091.00,27094.75,27046.25,27049.00,2520.0,29660.0,26500,0.8500,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
2,2018-12-03 09:25:00,27055.5,27053.95,27053.95,27030.00,27036.85,700.0,30100.0,26600,0.9627,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
3,2018-12-03 09:30:00,27055.5,27036.85,27040.00,27010.45,27011.15,2300.0,30240.0,26800,0.8113,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
4,2018-12-03 09:35:00,27055.5,27010.45,27055.00,27010.45,27027.25,1320.0,30700.0,26800,0.6938,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2018-12-31 15:10:00,27400.0,27400.00,27405.70,27400.00,27405.70,260.0,40520.0,27000,0.9563,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1506,2018-12-31 15:15:00,27400.0,27405.70,27416.00,27405.70,27416.00,340.0,40600.0,27000,0.8585,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1507,2018-12-31 15:20:00,27400.0,27416.00,27416.50,27405.00,27407.10,400.0,40580.0,27000,0.7116,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1508,2018-12-31 15:25:00,27400.0,27405.60,27412.25,27403.80,27403.80,340.0,40540.0,27000,0.6587,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1509,2018-12-31 15:30:00,27400.0,27405.10,27405.10,27401.05,27401.05,240.0,40540.0,27200,0.7203,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18

In [89]:
f=final_s
filled_dates = f.groupby(f['datetime'].dt.date)['gap_filled'].transform(lambda x: 'Yes' if 'Yes' in x.values else 'No')
f['gap_filled'] = filled_dates
f

<ipython-input-89-5120df778c81>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  f['gap_filled'] = filled_dates

,datetime,atm,open,high,low,close,volume,oi,max_pain_strike,intraday_pcr,...,highest_above_vah,lowest_below_val,gap_type,gap_filled,3_day_vah,5_day_vah,3_day_val,5_day_val,3_day_poc,5_day_poc
0,2018-12-03 09:15:00,27055.5,27100.00,27138.40,27069.80,27085.00,4040.0,29500.0,26500,0.6839,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
1,2018-12-03 09:20:00,27055.5,27091.00,27094.75,27046.25,27049.00,2520.0,29660.0,26500,0.8500,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
2,2018-12-03 09:25:00,27055.5,27053.95,27053.95,27030.00,27036.85,700.0,30100.0,26600,0.9627,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
3,2018-12-03 09:30:00,27055.5,27036.85,27040.00,27010.45,27011.15,2300.0,30240.0,26800,0.8113,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
4,2018-12-03 09:35:00,27055.5,27010.45,27055.00,27010.45,27027.25,1320.0,30700.0,26800,0.6938,...,27138.40,26970.0,,Yes,27038.33,26853.50,26906.77,26736.53,27038.33,26853.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1505,2018-12-31 15:10:00,27400.0,27400.00,27405.70,27400.00,27405.70,260.0,40520.0,27000,0.9563,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1506,2018-12-31 15:15:00,27400.0,27405.70,27416.00,27405.70,27416.00,340.0,40600.0,27000,0.8585,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1507,2018-12-31 15:20:00,27400.0,27416.00,27416.50,27405.00,27407.10,400.0,40580.0,27000,0.7116,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1508,2018-12-31 15:25:00,27400.0,27405.60,27412.25,27403.80,27403.80,340.0,40540.0,27000,0.6587,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18
1509,2018-12-31 15:30:00,27400.0,27405.10,27405.10,27401.05,27401.05,240.0,40540.0,27200,0.7203,...,27511.15,27319.2,,Yes,27401.22,27287.18,27276.01,27083.97,27401.22,27287.18

In [ ]:
#final_s.columns.tolist()

In [ ]:
#f.columns.tolist()

In [ ]:
#final_s.to_csv('opt_fut_combined.csv', index=True)

In [90]:
final_s.to_csv('1.csv', index=True)

In [93]:
f.to_csv('2.csv', index=True)